# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cracktools as ct
from helpers.layout import Ui_MainWindow
from helpers.metrics import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import Qt
import skimage
import numpy as np
import cv2
import matplotlib
matplotlib.use("Agg")   # fastest non-GUI backend for PNG/PDF/SVG export
matplotlib.rcParams.update({
    "figure.max_open_warning": 0,
    "text.kerning_factor": 0,
    "font.family": "DejaVu Sans",
    "axes.unicode_minus": False,
})
import matplotlib.pyplot as plt
plt.ioff()   # no interactive figure updates

import json
import os
import sys
from skimage.segmentation import mark_boundaries
import os
from PyQt5.QtWidgets import QListWidgetItem
from shapely import geometry, ops
import pandas as pd

from crackutils import *
from manual_drawing import *
from track_segment_pipeline import *
from helpers.crackhelpers import *
#from helpers import *
from helpers import plot_metrics
from helpers import metrics
from helpers import save_load_files
from combine_clear_segments import *
from metrics_engine import *
import cracktools as ct

from concurrent.futures import ProcessPoolExecutor, as_completed
import itertools, pandas as pd, os
from edge_workers import *

from rs3_split import run_rs3_variants_split
from edge_workers import *
from combiner import *


#from crackutils import CrackUtils
DEBUG_SAVE_LIGHT = True   # True → only high-res compact outputs
from helpers.endpoint_annotator import CrackAnnotator
min_crop_size = 16   

def _force_pyqt5_qt_plugin_paths():
    """OpenCV wheels may overwrite Qt plugin paths to cv2/qt/plugins; restore PyQt5 paths."""
    py_ver = f"python{sys.version_info.major}.{sys.version_info.minor}"
    plugin_root = os.path.join(sys.prefix, "lib", py_ver, "site-packages", "PyQt5", "Qt5", "plugins")
    platform_dir = os.path.join(plugin_root, "platforms")

    if os.path.isdir(plugin_root):
        os.environ["QT_PLUGIN_PATH"] = plugin_root
    if os.path.isdir(platform_dir):
        os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = platform_dir


def debug_plot_all_atomics(image, atomic_cracks, title="DEBUG ATOMICS", out_png=None, show=False):
    """
    Visualize raw atomic truth directly on the full image:
      - bbox in cyan
      - midline in lime
      - endpoints in red
      - bbox center in yellow
      - midline centroid in magenta
    """
    if image is None:
        return
    img = np.asarray(image)
    if img.ndim < 2:
        return
    H, W = img.shape[:2]

    fig, ax = plt.subplots(figsize=(10, 12), dpi=180)
    ax.imshow(img)

    for cr in (atomic_cracks or []):
        if not isinstance(cr, dict):
            continue
        scid = cr.get("id", "?")
        bbox = cr.get("mask_bbox", None)
        mid = cr.get("midline", None)
        color_mid = plt.cm.tab10(int(scid) % 10) if str(scid).isdigit() else "lime"

        if isinstance(bbox, (list, tuple)) and len(bbox) == 4:
            try:
                x, y, bw, bh = [int(v) for v in bbox]
                rect = plt.Rectangle((x, y), bw, bh, edgecolor="cyan", facecolor="none", linewidth=2)
                ax.add_patch(rect)
                ax.text(x, y - 5, f"ID {scid}", color="cyan", fontsize=9, weight="bold")
                ax.scatter(x + bw / 2.0, y + bh / 2.0, c="yellow", s=18)
            except Exception:
                pass

        try:
            arr = np.asarray(mid, float)
            if arr.ndim == 2 and arr.shape[0] > 0 and arr.shape[1] == 2:
                ax.plot(arr[:, 0], arr[:, 1], color=color_mid, linewidth=2)
                ax.scatter(arr[0, 0], arr[0, 1], c="red", s=25)
                ax.scatter(arr[-1, 0], arr[-1, 1], c="red", s=25)
                ax.scatter(float(np.mean(arr[:, 0])), float(np.mean(arr[:, 1])), c="magenta", s=18)
        except Exception:
            pass

    ax.set_title(title)
    ax.set_xlim([0, W])
    ax.set_ylim([H, 0])
    ax.axis("off")
    plt.tight_layout()

    if out_png:
        try:
            os.makedirs(os.path.dirname(out_png), exist_ok=True)
            fig.savefig(out_png, bbox_inches="tight")
            print(f"[DEBUG ATOMICS] wrote {out_png}")
        except Exception as e:
            print(f"[DEBUG ATOMICS] failed to write {out_png}: {e}")

    if show:
        plt.show()
    plt.close(fig)

class CrackToolsApplication(MetricsEngine, ManualDrawing, TrackSegmentPipeline, CombineClearSegments, CrackUtils, Ui_MainWindow):
    def setupUi(self, MainWindow):
        super().setupUi(MainWindow)
        
        #Select Image Tab
        self.MainWindow = MainWindow
        self.SelectFolderButton.clicked.connect(self.select_folder)
        self.PreviousImageButton.clicked.connect(self.previous_image)
        self.NextImageButton.clicked.connect(self.next_image)
        self.files_list.itemSelectionChanged.connect(self.name_selected)
        
        self.combine_segments_button.clicked.connect(self.combine_segments)
        #self.man_only_metrics_button.clicked.connect(lambda: self.run_mask_metrics(display=True))
        self.man_only_metrics_button.clicked.connect(lambda: self.run_et_metrics_current_image_quick(tau_px=3.0, crack_id=None))
        #self.man_auto_metrics_button.clicked.connect(lambda: self.batch_run_metrics_global(sample_frac=.2,max_images=10,seed=0,cpu_max_workers=8,apply_to_sample=False,edges_only=False))
        self.man_auto_metrics_button.clicked.connect(
            lambda: self.run_full_metrics_current_image(
                edge_grid=None,
                g_variants=None,
                cpu_max_workers=8,
                do_edge_calibrate=True
            )
        )
        self.full_dataset_metrics_button.clicked.connect(
            lambda: self.batch_run_metrics_global(
                sample_frac=0.10,
                max_images=10,
                seed=0,
                cpu_max_workers=8,
                apply_to_sample=False,
                edges_only=False,
            )
        )
        self.summarize_dataset_button.clicked.connect(
            lambda: self.summarize_dataset_metrics()
        )

        
        
        self.draw_box_button.clicked.connect(self.draw_box)
        self.clear_pending_boxes_button.clicked.connect(self.clear_pending_boxes)
        self.save_b_button.clicked.connect(self.save_boxes)
        
        self.clear_boxes_button.clicked.connect(self.clear_boxes)
        self.clear_segmentation_button.clicked.connect(self.clear_segmentation)
        self.clear_combined_cracks_button.clicked.connect(self.clear_combined_cracks)
        self.create_modified_gt_button.clicked.connect(self.create_or_edit_modified_gt)
        self.delete_modified_gt_button.clicked.connect(self.delete_modified_gt)
        self.tabWidget.currentChanged.connect(self.on_main_tab_changed)
        if hasattr(self, "gt_modify_preview"):
            self.gt_modify_preview.setAlignment(Qt.AlignLeft | Qt.AlignTop)




        #Tracking Tab
        self.select_points_button.clicked.connect(self.select_save_end_points)
        self.export_gt_supervision.clicked.connect(self.export_gt_supervision_for_current_image)
        self.update_image_crop_button.clicked.connect(self.update_image_crop)
        self.wavelet_button.clicked.connect(self.check_wavelet)
        self.BatchPipelineButton.clicked.connect(self.batch_run_pipeline)
        self.update_os_button.clicked.connect(self.update_os)
        self.update_cost_button.clicked.connect(self.update_os_cost)
        self.midline_track_button.clicked.connect(self.midline_tracking)

        # Remove unused midpoint-check UI controls from the Tracking tab.
        if hasattr(self, "middle_point_button"):
            self.middle_point_button.hide()
        if hasattr(self, "middpoint_update_button"):
            self.middpoint_update_button.hide()
        if hasattr(self, "middlepoint_display"):
            self.middlepoint_display.hide()

        # Repurpose the OS button for full pipeline
        try:
            self.update_os_button.clicked.disconnect()
        except Exception:
            pass
        self.update_os_button.setText("Run Pipeline")
        self.update_os_button.clicked.connect(self.run_pipeline)




        #Segmentation Tab
        self.edge_mask_button.clicked.connect(self.edge_mask)
        self.edge_tracks_button.clicked.connect(self.edge_tracking)
        self.update_track_display_button.clicked.connect(self.update_track_display)
        self.track_full_screen_button.clicked.connect(self.track_full_screen)
        self.edge_tracks_full_screen_button.clicked.connect(self.edge_tracks_full_screen)
        self.save_current_segment_button.clicked.connect(self.save_current_segment)
 
       
       
        
        #Add segment manually tab
        self.draw_segment_button.clicked.connect(lambda: self.draw_segment('add'))
        self.erase_segment_button.clicked.connect(self.erase_segment)
        self.reset_segment_button.clicked.connect(self.reset_canvas)
        self.save_manuall_segment_button.clicked.connect(self.save_manual_segment)
        self.manual_segment_full_screen_button.clicked.connect(self.manual_segment_full_screen)

        self.n = -1
        self.saved = False

        self.update_image_crop_button.setStyleSheet("background-color : red")
        self.update_os_button.setStyleSheet("background-color : red")
        self.update_cost_button.setStyleSheet("background-color : red")
        self.midline_track_button.setStyleSheet("background-color : red")
        self.update_track_display_button.setStyleSheet("background-color : red")
        self.track_full_screen_button.setStyleSheet("background-color : red")
        self.edge_mask_button.setStyleSheet("background-color : red")
        self.edge_tracks_button.setStyleSheet("background-color : red")
        self.edge_tracks_full_screen_button.setStyleSheet("background-color : red")
        self.save_current_segment_button.setStyleSheet("background-color : red")
        self.draw_segment_button.setStyleSheet("background-color : red")
        self.erase_segment_button.setStyleSheet("background-color : orange")
        self.reset_segment_button.setStyleSheet("background-color : lightblue")
        self.save_manuall_segment_button.setStyleSheet("background-color : lightgreen")
        
        self.show_os_button.setStyleSheet("background-color : red")
        
        #self.mask_pipeline_button.setStyleSheet("background-color : red")
        
    def _purge_metrics_for_current_image(self):
        """
        Remove metrics artifacts for the CURRENT image only.
        Safe: does not touch other images.
        """
        import os, shutil

        base = self._image_base()   # canonical image key
        metrics_root = os.path.join(self.save_folder, "metrics")
        image_dir = os.path.join(metrics_root, base)

        if os.path.isdir(image_dir):
            try:
                shutil.rmtree(image_dir)
                print(f"[METRICS] 🧠¹ Purged metrics for image '{base}'")
            except Exception as e:
                print(f"[METRICS] ⚠ Failed to purge metrics for '{base}': {e}")
    
    def run_pipeline(self, multirun=False):
        import gc, json
        import numpy as np
        from PyQt5.QtWidgets import QMessageBox
        from time import time

        # ---- helpers ---------------------------------------------------------
        def _ensure_ann():
            # make sure base structure exists
            if not hasattr(self, "annotation") or not isinstance(self.annotation, dict):
                self.annotation = {}
            ann = self.annotation.setdefault("annotations", {})
            ann.setdefault("atomic_cracks", {})
            ann.setdefault("combined_cracks", {})
            # scrub stray non-numeric keys
            bad_keys = [k for k in ann["atomic_cracks"].keys() if not str(k).isdigit()]
            for bk in bad_keys:
                ann["atomic_cracks"].pop(bk, None)
            return ann

        def _next_crack_id_str():
            """
            Return the lowest non-negative id that is NOT used in saved atomic_cracks.
            This ignores any in-memory caches so deleted ids are reused.
            """
            ann = self.annotation.get("annotations", {})
            ac = ann.get("atomic_cracks", {})
            used = sorted(int(k) for k in ac.keys() if str(k).isdigit())
            nxt = 0
            for k in used:
                if k == nxt:
                    nxt += 1
                elif k > nxt:
                    break
            return str(nxt)

        # ---- start -----------------------------------------------------------
        gc.collect()
        print("✅ GPU memory freed from CuPy pool")
        print("Running midline pipeline (auto + manual)...")

        # reset scratch between runs so ids don't leak/inflate
        self.current_crack_id = None
        self.crack_tracks = {}        # in-memory geodesic paths per id (scratch only)

        ann = _ensure_ann()
        ac_store = ann["atomic_cracks"]

        # Keep crack bbox assignments coherent with current user boxes before grouping pairs.
        if hasattr(self, "_rematch_crack_bboxes_to_boxes"):
            try:
                self._rematch_crack_bboxes_to_boxes()
            except Exception as e:
                print(f"[bbox rematch] run_pipeline preflight failed: {e}")

        boxes = self.get_all_bounding_boxes()
        print(f"Loaded {len(boxes)} bounding boxes: {boxes}")
        if not boxes:
            QMessageBox.critical(None, "No Bounding Boxes",
                "Please draw at least one bounding box before running the pipeline.")
            return

        if not multirun:
            # Let the user pick points/connections/midlines
            self.endpoint_pairs = None
            self.user_connections = None
            self.user_points = None
            self.manual_endpoint_pairs = None
            self.all_selected_points = None  # reset before each run
            print("Calling select_end_points_manmidlines()...")
            self.select_end_points_manmidlines(metrics=False)

        # Merge auto + manual endpoint pairs (global, from annotator)
        all_pairs = []
        if getattr(self, "endpoint_pairs", None):
            print(f"Auto endpoint_pairs: {self.endpoint_pairs}")
            all_pairs.extend([(p, "auto") for p in self.endpoint_pairs])

        if getattr(self, "manual_endpoint_pairs", None):
            print(f"Manual endpoint_pairs: {self.manual_endpoint_pairs}")
            all_pairs.extend([(p, "manual") for p in self.manual_endpoint_pairs])

        if not all_pairs:
            QMessageBox.critical(
                None, "No Endpoint Pairs",
                "No endpoint pairs selected!\n\nPlease use 'Select Endpoints' and create at least one connection or manual midline before running the pipeline."
            )
            return

        # Group by bbox (so OS/cost is reused per box)
        box_to_pairs = {}
        dropped_pairs = []
        for (pair, src) in all_pairs:
            candidates = []
            for bbox in boxes:
                xmin, ymin, xmax, ymax = bbox
                p0, p1 = pair
                if (xmin <= p0[0] <= xmax and ymin <= p0[1] <= ymax and
                    xmin <= p1[0] <= xmax and ymin <= p1[1] <= ymax):
                    area = abs((xmax - xmin) * (ymax - ymin))
                    candidates.append((area, bbox))
            if candidates:
                _, chosen_bbox = min(candidates, key=lambda x: x[0])
                key = tuple(chosen_bbox)
                box_to_pairs.setdefault(key, []).append((pair, src))
            else:
                dropped_pairs.append((pair, src))

        if dropped_pairs:
            print("[PIPELINE] Skipping endpoint pairs with no corresponding bounding box:")
            for (p0, p1), src in dropped_pairs:
                print(f"  - source={src} pair={p0}->{p1}")

        if not box_to_pairs:
            QMessageBox.critical(
                None,
                "No Valid Endpoint Pairs",
                "All selected endpoint pairs are outside bounding boxes.\n\n"
                "Please draw/fix boxes so each crack pair is contained in at least one box.",
            )
            return

        errors = []

        # Make sure we don't blow away memory of previous masks
        if not hasattr(self, "mask"):
            self.mask = []

        for bbox_key, pairs in box_to_pairs.items():
            xmin, ymin, xmax, ymax = bbox_key
            print(f"\n=== Processing bbox {bbox_key} ===")
            print(f"Pairs in this box: {pairs}")

            try:
                # Precompute OS/cost once per box for auto pairs
                auto_pairs = [p for p, s in pairs if s == "auto"]
                if auto_pairs:
                    first_pair = auto_pairs[0]
                    print(f"Precomputing OS/cost for auto pair {first_pair}")
                    self.pts = [np.array(first_pair[0]), np.array(first_pair[1])]
                    self.end_points = self.pts
                    self.active_bbox = list(bbox_key)
                    self.update_image_crop()
                    if getattr(self, "skip_current_segment", False):
                        continue
                    print("os (once per box)")
                    self.update_os_cost()
                    #t0 = time(); self.update_os(); print(f"os time: {time()-t0:.2f}s")
                    #print("cost (once per box)")
                    #t0 = time(); self.update_cost(); print(f"cost time: {time()-t0:.2f}s")

                # Process each pair -> one atomic crack per pair
                for (p0, p1), src in pairs:
                    try:
                        self.active_bbox = list(bbox_key)
                        print(f"\n--- Processing pair {(p0, p1)} (source={src}) ---")

                        # Per-crack, pair-local endpoints for saving
                        pair_user_points = [tuple(p0), tuple(p1)]
                        pair_user_connections = [[0, 1]]  # exactly one connection per crack

                        if src in ("manual", "manual_poly"):
                            # For manual, we reuse the drawn polyline as midline (full-image coords)
                            manual_midlines_dict = getattr(self, "manual_midlines_tmp", {})
                            found_key = None

                            # Durable copy of selection points from earlier
                            all_points = getattr(self, "all_selected_points", None)
                            if all_points is None:
                                all_points = getattr(self, "user_points", [])

                            print("\n[DEBUG] --- Matching manual midline ---")
                            print(f"[DEBUG] manual_midlines_tmp keys at runtime: {list(manual_midlines_dict.keys())}")
                            print(f"[DEBUG] all_points at runtime: {all_points}")
                            print(f"[DEBUG] Trying to match p0={p0}  p1={p1}")

                            # manual_midlines_tmp keys are "i_j" from annotator indices; match geometrically     
                            for k, poly in manual_midlines_dict.items():
                                try:
                                    # handle both tuple keys (2,3) and string keys "2_3"
                                    if isinstance(k, tuple) and len(k) == 2:
                                        i1, i2 = map(int, k)
                                    elif isinstance(k, str) and "_" in k:
                                        i1, i2 = map(int, k.split("_"))
                                    else:
                                        print(f"[DEBUG] Unrecognized key format: {k!r}")
                                        continue

                                    c_i = tuple(all_points[i1])
                                    c_j = tuple(all_points[i2])
                                    print(f"[DEBUG] Checking key={k}, c_i={c_i}, c_j={c_j}")
                                    if (c_i, c_j) == (p0, p1) or (c_i, c_j) == (p1, p0):
                                        print(f"[DEBUG] Found match for key={k}")
                                        found_key = k
                                        break
                                except Exception as e:
                                    print(f"[DEBUG] Error parsing key={k}: {e}")

                            print(f"[MANUAL] Found key: {found_key}")
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.update_image_crop()
                            if getattr(self, "skip_current_segment", False):
                                continue

                            if found_key:
                                # Convert full-image manual polyline to crop coords and set as self.track
                                poly = np.array(manual_midlines_dict[found_key], dtype=float)  # [[x,y],...]

                                """print("\n[DBG MANUAL POLYLINE] first 20 (FULL IMAGE COORDS):")
                                for i, (x, y) in enumerate(poly[:20]):
                                    print(f"  {i:02d}: ({x:.6f}, {y:.6f})")"""

                                cy = poly[:, 1] - ymin
                                cx = poly[:, 0] - xmin

                                """print("\n[DBG AFTER CROP OFFSET] first 20:")
                                for i in range(min(20, len(cx))):
                                    print(f"  {i:02d}: cx={cx[i]:.6f}, cy={cy[i]:.6f}")"""

                                self.track = np.vstack([cy, cx])

                                """print("\n[DBG TRACK ARRAY]")
                                print(f"  dtype: {self.track.dtype}")
                                print(f"  shape: {self.track.shape}")

                                print("[DBG TRACK first 20]:")
                                for i in range(min(20, self.track.shape[1])):
                                    print(f"  {i:02d}: (y={self.track[0, i]:.6f}, x={self.track[1, i]:.6f})")"""

                                # ---- endpoint bookkeeping (unchanged) ----
                                self.pts_crop = [
                                    np.array(self.pts[0]) - np.array([xmin, ymin]),
                                    np.array(self.pts[1]) - np.array([xmin, ymin])
                                ]

                                downsample = self.downsample_factor_box.value()
                                self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            else:
                                msg = f"No manual polyline found for manual crack {p0}→{p1}"
                                print("ERROR:", msg)
                                errors.append(msg)
                                continue
                        else:
                            # Auto mode
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.pts_crop = [np.array(pt) - np.array([xmin, ymin]) for pt in self.pts]
                            downsample = self.downsample_factor_box.value()
                            self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            t0 = time(); self.midline_tracking(); print(f"    midline tracking time: {time()-t0:.2f}s")

                            # --- normalize track like generate_auto_variant_for_manual ---
                            if getattr(self, "track", None) is not None:
                                try:
                                    tr = np.asarray(self.track, float)
                                    if tr.shape[0] == 2:
                                        track_xy = tr.T
                                    else:
                                        track_xy = tr

                                    p0g = np.asarray(p0, float)
                                    p1g = np.asarray(p1, float)

                                    # reverse if needed (ensure start = p0)
                                    d_start_p0 = np.linalg.norm(track_xy[0] - p0g)
                                    d_start_p1 = np.linalg.norm(track_xy[0] - p1g)
                                    if d_start_p1 < d_start_p0:
                                        track_xy = track_xy[::-1]
                                        print(f"[PIPE ALIGN] reversed path so first sample anchors at p0 (d_start_p0={d_start_p0:.2f}, d_start_p1={d_start_p1:.2f})")
                                    else:
                                        print(f"[PIPE ALIGN] path already starts near p0 (d_start_p0={d_start_p0:.2f}, d_start_p1={d_start_p1:.2f})")

                                    # translate so first point == p0
                                    delta = p0g - track_xy[0]
                                    track_xy = track_xy + delta

                                    # convert to local coords (crop relative)
                                    xmin, ymin, xmax, ymax = bbox_key
                                    track_local = track_xy - np.array([xmin, ymin])
                                    track_local[:,0] = np.clip(track_local[:,0], 0, xmax - xmin - 1)
                                    track_local[:,1] = np.clip(track_local[:,1], 0, ymax - ymin - 1)
                                    self.track = track_local.T

                                    print(f"[PIPE ALIGN] normalized track: start Δ={np.linalg.norm(track_local[0] - (p0g - np.array([xmin, ymin]))):.2f}px")
                                except Exception as e:
                                    print(f"[PIPE ALIGN] ⚠ failed to normalize: {e}")

                        # Canonicalize spacing before geometry consumers (edge_mask/edge_tracking).
                        try:
                            if getattr(self, "track", None) is not None:
                                self.track, rs_info = canonicalize_track_for_edges(
                                    self.track,
                                    ds_target=1.0,
                                    min_spacing_auto=0.8,
                                    min_spacing_manual=0.3,
                                    preserve_endpoints=True,
                                    source=src,
                                )
                                med_txt = (
                                    f"{rs_info['med_before']:.3f}"
                                    if rs_info.get("med_before") is not None
                                    else "None"
                                )
                                print(
                                    f"[PIPE RESAMPLE {src}] med={med_txt}, "
                                    f"resampled={rs_info.get('did_resample')}, "
                                    f"len={rs_info.get('n_before')}→{rs_info.get('n_after')}"
                                )
                        except Exception as e:
                            print(f"[PIPE RESAMPLE] ⚠ canonicalization failed: {e}")
                        
                        # ======= Assign a brand-new crack ID for THIS pair (gap-free) =======
                        new_cid = _next_crack_id_str()
                        self.current_crack_id = int(new_cid)

                        def _dbg_track(label, track, n=20):
                            print(f"\n[DBG {label}]")
                            if track is None:
                                print("  track is None")
                                return
                            print(f"  dtype={track.dtype}, shape={track.shape}")
                            pts = track[:, :min(n, track.shape[1])]
                            for i in range(pts.shape[1]):
                                y, x = pts[:, i]
                                print(f"  {i:02d}: (y={y:.6f}, x={x:.6f})")

                        #_dbg_track("PRE edge_mask (track)", self.track)

                        # Geodesic edges & masks for this pair
                        self.current_source = src
                        start_time = time()
                        self.edge_mask()
                        edgemask_time = time()
                        #_dbg_track("EXIT edge_mask (track)", self.track)
                        print()
                        print(f"[TIME] Edge mask time: {edgemask_time - start_time}")
                        self.edge_tracking()
                        print()
                        print(f"[TIME] Edge tracking time: {time() - edgemask_time}")
                        #_dbg_track("EXIT edge_tracking (track)", self.track)

                        # Pair-local globals so save_current_segment writes them into that crack
                        self.user_points = pair_user_points
                        self.user_connections = pair_user_connections
                        
                        # === QUICK TEST TRIPWIRE ===
                        print(f"[TRIPWIRE] about to save crack with src={src}, p0={p0}, p1={p1}")
                        print(f"   track shape: {getattr(self, 'track', None).shape if hasattr(self, 'track') else None}")
                        print(f"   current_crack_id={self.current_crack_id}")
                        print(f"   manual_midlines_tmp keys: {list(getattr(self, 'manual_midlines_tmp', {}).keys())}")
                        print(f"   total atomic before save: {len(self.annotation['annotations']['atomic_cracks'])}")

                        # 🧠   For now, bail early to inspect what’s going on — no file write, no mutation
                        #return

                        # Save segment (midline + edges + mask + per-crack endpoints)
                        savetime = time()
                        self.save_current_segment()
                        print()
                        print(f"[TIME] Save current segment time: {time() - savetime}")

                        # Clear pair-local globals so next crack doesn't inherit them
                        self.user_points = None
                        self.user_connections = None

                    except Exception as e:
                        errors.append(f"Failed midline for {(p0, p1)}: {e}")
                        continue

            except Exception as e:
                errors.append(f"Failed for bbox {bbox_key}: {e}")
                continue

        # Done with all boxes/pairs
        if errors:
            print("\n".join(errors))
        else:
            print("✔ All endpoint groups processed.")

        # Clear UI temp state (per-run scratch)
        self.endpoint_pairs = None
        self.manual_endpoint_pairs = None

        # Persist JSON
        #self.save_annotation()
            
        
        self.auto_combine_segments()

        # Debug print & refresh view
        self._debug_print_atomic_cracks("run_pipeline END")
        self.change_image()
            
    def batch_run_pipeline(self):
        """
        Runs the pipeline (full segment generation, clearing endpoints/connections) on EVERY image in the selected folder.
        """
        from PyQt5.QtWidgets import QMessageBox
        import os
        
        # Check existence and content
        if not hasattr(self, "image_names") or not self.image_names:
            QMessageBox.warning(self.MainWindow, "Batch Run", "No images loaded. Please select a folder with images first.")
            print("Batch run aborted: no images loaded.")
            return
        
        total = len(self.image_names)
        errors = []
        n_success = 0
        orig_n = self.n

        def _extract_pairs_from_annotation():
            """
            Build endpoint pairs + manual midlines from the currently loaded annotation.
            Returns: (endpoint_pairs, manual_endpoint_pairs, manual_midlines_tmp,
                      user_points, user_connections)
            """
            ann = (self.annotation or {}).get("annotations", {}) or {}
            atomic = ann.get("atomic_cracks", {}) or {}
            if not atomic:
                return [], [], {}, [], []

            points = []
            point_index = {}

            def _add_point(pt):
                try:
                    x = float(pt[0])
                    y = float(pt[1])
                except Exception:
                    return None
                key = (x, y)
                idx = point_index.get(key)
                if idx is None:
                    idx = len(points)
                    point_index[key] = idx
                    points.append([x, y])
                return idx

            auto_conn_idx = []
            manual_conn_idx = []
            manual_midlines = {}
            seen_auto = set()
            seen_manual = set()

            for crack in atomic.values():
                src = str(crack.get("source") or crack.get("src") or "").lower()
                up = crack.get("user_points") or []
                if len(up) >= 2:
                    p1, p2 = up[0], up[1]
                else:
                    ml = crack.get("midline") or []
                    if len(ml) >= 2:
                        p1, p2 = ml[0], ml[-1]
                    else:
                        continue

                i1 = _add_point(p1)
                i2 = _add_point(p2)
                if i1 is None or i2 is None or i1 == i2:
                    continue

                if src in ("manual", "manual_poly", "manual_midline"):
                    mid = crack.get("midline") or []
                    if len(mid) < 2:
                        continue
                    key = (i1, i2)
                    if key not in seen_manual and (i2, i1) not in seen_manual:
                        seen_manual.add(key)
                        seen_manual.add((i2, i1))
                        manual_conn_idx.append((i1, i2))
                    manual_midlines[key] = [(float(x), float(y)) for (x, y) in mid]
                else:
                    key = (i1, i2)
                    if key in seen_auto or (i2, i1) in seen_auto:
                        continue
                    seen_auto.add(key)
                    seen_auto.add((i2, i1))
                    auto_conn_idx.append((i1, i2))

            endpoint_pairs = [(points[i1], points[i2]) for (i1, i2) in auto_conn_idx]
            manual_endpoint_pairs = [(points[i1], points[i2]) for (i1, i2) in manual_conn_idx]
            return endpoint_pairs, manual_endpoint_pairs, manual_midlines, points, auto_conn_idx

        for idx, fname in enumerate(self.image_names):
            try:
                base_name = os.path.splitext(os.path.basename(fname))[0]
                ann_path = os.path.join(self.save_folder, f"{base_name}.json")
                if not os.path.exists(ann_path):
                    print(f"  [SKIP] No annotation JSON for {base_name}.")
                    continue

                self.n = idx
                self.change_image()

                endpoint_pairs, manual_endpoint_pairs, manual_midlines_tmp, pts, conns = (
                    _extract_pairs_from_annotation()
                )

                # Only run if endpoints/connections are present
                if endpoint_pairs or manual_endpoint_pairs:
                    self.user_points = pts
                    self.user_connections = [list(c) for c in conns]
                    self.endpoint_pairs = endpoint_pairs
                    self.manual_endpoint_pairs = manual_endpoint_pairs
                    self.manual_midlines_tmp = manual_midlines_tmp
                    self.all_selected_points = list(pts)

                    print(f"\n======= Processing image {idx+1}/{total}: {fname} =======")
                    self.run_pipeline(multirun=True)  # Will clear endpoints on success
                    n_success += 1
                    #return
                else:
                    print(f"  [SKIP] No endpoints/connections for this image.")
            except Exception as e:
                errors.append(f"Image {fname}: {e}")

        self.n = orig_n
        self.change_image()
        summary = f"Batch pipeline run complete.\nSuccessful: {n_success}/{total}\n"
        if errors:
            summary += f"\nErrors:\n" + "\n".join(errors)
        print(summary)
        QMessageBox.information(self.MainWindow, "Batch pipeline finished", summary)
  
    #####################################
    # New functions
    #####################################

    '''def batch_run_metrics_global(
            self,
            sample_frac=0.20,          # % of images to use for global calibration
            max_images=10,             # cap for calibration phase
            seed=0,
            edge_grid=None,            # if None → sensible default below
            g_variants=None,           # if None → defaults inside generate_auto_variants_for_et_parallel
            cpu_max_workers=4,
            apply_to_sample=False,     # False → apply global params to ALL images; True → sampled set only
            edges_only=False,          # True → skip RS3; parallelize edge masks/tracking per crack
            edge_parallel_workers=None # override worker count for the edge-only branch
        ):
        """
        GLOBAL METRICS DRIVER (one image in memory at a time, no manual edge precompute needed).
        - Prefilters calibration pool to images that actually have manual midlines (≥2 pts).
        - Includes timing for calibration + per-image application.
        - If `edges_only=True`, skips RS3 variants and runs parallel edge tracking per crack.

        Writes:
        metrics/_summary/global_edge_sweep_all.csv
        metrics/_summary/global_best_edge_params.json
        metrics/_summary/global_per_image_runtime.csv
        metrics/_summary/global_runtime.csv
        metrics/_summary/global_runtime_summary.txt
        """
        import os, json, random, time
        import numpy as np, pandas as pd

        if not getattr(self, "image_names", []):
            print("[global-metrics] no images loaded")
            return

        # -------------- build an eligible calibration pool (must have manual midlines) --------------
        def _ann_path_for_image(idx: int) -> str:
            """Derive the expected annotation JSON path for image index `idx`."""
            import os
            img_path  = self.image_names[idx]
            base_name = os.path.splitext(os.path.basename(img_path))[0]
            # Your code stores annotations directly under `self.save_folder` as `<base>.json`
            # e.g. .../Outputs/1.json (as seen in your logs)
            return os.path.join(self.save_folder, f"{base_name}.json")

            ann    = (data or {}).get("annotations", {}) or {}
            atomic = ann.get("atomic_cracks", {}) or {}
            if not atomic:
                return False

            for crack in atomic.values():
                src = (crack.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue
                mid = crack.get("midline", [])
                # Enough points to be meaningful
                if isinstance(mid, list) and len(mid) >= 2:
                    return True
            return False

        """def _has_manual_midlines_for_index(idx: int) -> bool:
            """
            Fast path:
            (1) if per-image JSON doesn't exist → False (skip)
            (2) if JSON exists and has manual ≥2-pt midlines → True (no change_image() cost)
            (3) else, do a final in-memory check via change_image() (robustness)
            """
            import contextlib
            ann_path = _ann_path_for_image(idx)
            if not os.path.exists(ann_path):
                return False
            if _json_has_manual_midlines(ann_path):
                return True"""
        # Fallback: load
        def _has_manual_midlines_for_index(idx: int) -> bool:
            """
            Fast path:
            (1) if per-image JSON doesn't exist → False (skip)
            (2) if JSON exists and has manual ≥2-pt midlines → True (no change_image() cost)
            (3) else, do a final in-memory check via change_image() → True/False
            """
            ann_path = _ann_path_for_image(idx)
            if not os.path.exists(ann_path):
                return False
            if metrics._json_has_manual_midlines(ann_path):
                return True

            # Final in-memory check (robust against any stale/legacy JSON)
            orig_n = getattr(self, "n", 0)
            try:
                self.n = idx
                self.change_image()
                ann = (self.annotation or {}).get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    return False
                for crack in atomic.values():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    mid = crack.get("midline", [])
                    if isinstance(mid, list) and len(mid) >= 2:
                        return True
                return False
            except Exception:
                return False
            finally:
                # restore original index
                try:
                    self.n = orig_n
                    self.change_image()
                except Exception:
                    pass


        rng = random.Random(seed)
        all_idxs = list(range(len(self.image_names)))
        eligible_idxs = [i for i in all_idxs if _has_manual_midlines_for_index(i)]
        if not eligible_idxs:
            print("[global-metrics] ❌ No images with manual midlines found — aborting.")
            # try to restore a reasonable state
            if all_idxs:
                self.n = 0
                self.change_image()
            return

        rng.shuffle(eligible_idxs)
        k = max(1, int(len(eligible_idxs) * float(sample_frac)))
        idxs_sample = eligible_idxs[:min(k, max_images)]
        print(f"[global-metrics] calibration on {len(idxs_sample)} images "
            f"(from {len(eligible_idxs)} eligible / {len(all_idxs)} total)")

        if edge_grid is None:
            edge_grid = [
                {"window_half_size": 45, "mu": 0, "l": 5, "p": 14, "seg_mode": "old"},
                {"window_half_size": 45, "mu": 0, "l": 5, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 0, "l": 2, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 0, "l": 8, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 2, "l": 5, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 5, "l": 5, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 2, "l": 5, "p": 2, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 2, "l": 5, "p": 20, "seg_mode": "new"},
            ]

        sweep_rows = []
        orig_n = self.n
        calib_dir = os.path.join(self.save_folder, "metrics", "_calibration")
        os.makedirs(calib_dir, exist_ok=True)

        # --- PHASE A: Calibration timer ---
        tA_start = time.perf_counter()
        try:
            for t, i in enumerate(idxs_sample, 1):
                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [calibrate] {t}/{len(idxs_sample)}: {base_name} ======")

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    print("  [skip] no atomic cracks in annotation")
                    continue

                n_manual = 0
                for cid, crack in atomic.items():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    man_xy = metrics._finite_xy(crack.get("midline", []))
                    if len(man_xy) < 2:
                        continue
                    n_manual += 1

                    df_sweep = self.sweep_edges_with_executor(
                        cid, grid=edge_grid, max_workers=cpu_max_workers
                    )
                    if df_sweep is None or df_sweep.empty:
                        print(f"    [cid {cid}] sweep returned empty (no payload or worker error)")
                        continue

                    df_sweep = df_sweep.copy()
                    df_sweep["image"]    = base_name
                    df_sweep["crack_id"] = cid
                    sweep_rows.append(df_sweep)

                if n_manual == 0:
                    print("  [skip] no manual midlines ≥2 points in this image")

            # Either choose best from sweeps or fall back
            if sweep_rows:
                df_all = pd.concat(sweep_rows, ignore_index=True)
                df_all.to_csv(os.path.join(summ_dir, "global_edge_sweep_all.csv"), index=False)

                param_cols = ["param_window_half_size", "param_mu", "param_l", "param_p"]
                keep_cols  = param_cols + ["nn_mean_bidirectional", "hausdorff_max", "coverage_min"]
                sub = df_all[[c for c in keep_cols if c in df_all.columns]].dropna()

                g = (sub.groupby(param_cols, as_index=False)
                        .agg({"nn_mean_bidirectional":"mean","hausdorff_max":"mean","coverage_min":"mean"}))
                g = g.sort_values(["nn_mean_bidirectional","hausdorff_max","coverage_min"],
                                ascending=[True, True, False])

                best = g.iloc[0].to_dict()
                global_best_edge = {
                    "window_half_size": int(best["param_window_half_size"]),
                    "mu": float(best["param_mu"]),
                    "l":  int(best["param_l"]),
                    "p":  int(best["param_p"]),
                }
            else:
                print("[global-metrics] ⚠ no sweep rows gathered — using default edge params")
                global_best_edge = {"window_half_size": 45, "mu": 0.0, "l": 5, "p": 14}

            with open(os.path.join(summ_dir, "global_best_edge_params.json"), "w") as f:
                json.dump(global_best_edge, f)
            print(f"[global-metrics] ✅ global best edge params = {global_best_edge}")

        finally:
            self.n = orig_n
            self.change_image()

        tA = time.perf_counter() - tA_start
        print(f"[global-metrics] ⏱ calibration phase took {tA:.2f} s")
        
            # --- PHASE B: Apply timer ---
        tB_start = time.perf_counter()

        print("[global-metrics] applying global params to images...")
        apply_idxs = idxs_sample if apply_to_sample else list(range(len(self.image_names)))

        per_image_times = []

        try:
            for t, i in enumerate(apply_idxs, 1):
                # ---------- NEW: ultra-early skips ----------
                # 1) Skip if the per-image annotation JSON doesn't exist
                base_name = os.path.splitext(os.path.basename(self.image_names[i]))[0]
                ann_path  = os.path.join(self.save_folder, f"{base_name}.json")
                if not os.path.exists(ann_path):
                    print(f"[apply] ⚠ Skipping {base_name} — no JSON found.")
                    continue

                # 2) Skip if JSON exists but has no manual midlines with ≥2 points
                if not metrics._json_has_manual_midlines(ann_path):
                    print(f"[apply] ⚠ Skipping {base_name} — JSON has no manual midlines.")
                    continue

                # 3) Skip if already completed earlier
                image_dir = os.path.join(self.save_folder, "metrics", base_name)
                done_flag = os.path.join(image_dir, "DONE.ok")
                if os.path.exists(done_flag):
                    print(f"[apply] ✅ Already complete — {base_name} (found DONE.ok)")
                    continue

                # -------------------------------------------
                t_img_start = time.perf_counter()

                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [apply] {t}/{len(apply_idxs)}: {base_name} ======")
                os.makedirs(image_dir, exist_ok=True)

                # log edge params used
                try:
                    with open(os.path.join(image_dir, "edge_params_used.json"), "w") as f:
                        json.dump(global_best_edge, f)
                except Exception as e:
                    print(f"[apply] could not write edge_params_used.json: {e}")

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    # nothing to do (but still record a stub and move on)
                    with open(os.path.join(image_dir, "status.json"), "w") as f:
                        json.dump({"image": base_name, "processed_cracks": [], "note": "no atomic cracks"}, f)
                    # mark done to avoid re-entering
                    open(done_flag, "a").close()
                    t_img_total = time.perf_counter() - t_img_start
                    per_image_times.append({
                        "image": base_name,
                        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                        "total_image_s": round(t_img_total, 2),
                        "metrics_s": 0.0,
                        "auto_variants_s": 0.0,
                        "mask_build_s": 0.0,
                        "supervision_s": 0.0,
                        "mode": "full" if not edges_only else "edges_only"
                    })
                    continue

                # --- Subphase timers ---
                t_auto = 0.0
                t_edge_parallel = 0.0

                processed_cracks = []  # for status.json

                if edges_only:
                    # ----------------- EDGE-ONLY FAST PATH -----------------
                    t_edge_parallel_start = time.perf_counter()
                    try:
                        _ = self.run_edge_tracking_parallel(
                            crack_ids=list(atomic.keys()),
                            cpu_max_workers=edge_parallel_workers,
                            edge_params_fixed=global_best_edge,
                        )
                        processed_cracks = list(atomic.keys())
                    except Exception as e:
                        print(f"[apply] edge-only parallel run failed: {e}")
                    t_edge_parallel = time.perf_counter() - t_edge_parallel_start

                    # No RS3 / no auto masks build; just compute manual mask/width metrics
                    t_mask = 0.0

                    t_metrics_start = time.perf_counter()
                    try:
                        self.compute_mask_and_width_metrics_for_image(
                            display=False,
                            export_supervision=True,
                        )
                    except Exception as e:
                        print(f"[apply] mask/width stage failed: {e}")
                    t_metrics = time.perf_counter() - t_metrics_start

                    t_sup = 0.0  # supervision export relies on auto artifacts; skip in edge-only

                else:
                    # --------------- FULL RS3 VARIANTS PATH ----------------
                    # Build autos only for cracks with manual midlines (≥2 pts)
                    valid_manual_ids = []
                    for cid, crack in atomic.items():
                        src = (crack.get("source") or "").lower()
                        if src.startswith("auto") or src == "combined":
                            continue
                        man_xy = metrics._finite_xy(crack.get("midline", []))
                        if len(man_xy) >= 2:
                            valid_manual_ids.append(cid)

                    t_auto_start = time.perf_counter()
                    auto_packs_for_image = {}   # NEW: collect packs for this image

                    for cid in valid_manual_ids:
                        try:
                            pack = self.generate_auto_variants_for_et_parallel(
                                crack_id=cid,
                                g_variants=g_variants,
                                edge_params_fixed=global_best_edge,
                                cpu_max_workers=cpu_max_workers,
                                force_recompute=True,
                            )
                            if pack is not None:
                                auto_packs_for_image[cid] = pack
                            processed_cracks.append(cid)
                        except Exception as e:
                            print(f"[apply] RS3 variants failed for cid={cid}: {e}")

                    t_auto = time.perf_counter() - t_auto_start

                    # ---- NEW: global selection over all subcracks in this image ----
                    self._select_best_rs3_across_subcracks(auto_packs_for_image)


                    # --- Build combined masks ---
                    t_mask_start = time.perf_counter()
                    try:
                        self._build_combined_auto_masks_same_indices(cache_key=metrics._auto_cache_key(self))
                    except Exception as e:
                        print(f"[apply] combined auto-mask build failed: {e}")
                    t_mask = time.perf_counter() - t_mask_start

                    # --- Compute mask/width metrics ---
                    t_metrics_start = time.perf_counter()
                    try:
                        self.compute_mask_and_width_metrics_for_image(
                            display=False,
                            export_supervision=True,
                        )
                    except Exception as e:
                        print(f"[apply] mask/width stage failed: {e}")
                    t_metrics = time.perf_counter() - t_metrics_start

                    # --- Export training supervision ---
                    t_sup_start = time.perf_counter()
                    try:
                        self.export_training_supervision_for_image(cache_key=metrics._auto_cache_key(self))
                    except Exception as e:
                        print(f"[apply] supervision export failed: {e}")
                    t_sup = time.perf_counter() - t_sup_start

                # --- per-image log row ---
                t_img_total = time.perf_counter() - t_img_start
                row = {
                    "image": base_name,
                    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                    "total_image_s": round(t_img_total, 2),
                    "metrics_s": round(t_metrics, 2),
                }

                if edges_only:
                    row.update({
                        "edge_parallel_s": round(t_edge_parallel, 2),
                        "mask_build_s": 0.0,
                        "auto_variants_s": 0.0,
                        "supervision_s": 0.0,
                        "mode": "edges_only"
                    })
                    print(f"[apply] ⏱ total {t_img_total:.2f}s (edge_parallel={t_edge_parallel:.2f}s, "
                          f"metrics={t_metrics:.2f}s)")
                else:
                    row.update({
                        "auto_variants_s": round(t_auto, 2),
                        "mask_build_s": round(t_mask, 2),
                        "supervision_s": round(t_sup, 2),
                        "mode": "full"
                    })
                    print(f"[apply] ⏱ total {t_img_total:.2f}s (auto={t_auto:.2f}s, mask={t_mask:.2f}s, "
                          f"metrics={t_metrics:.2f}s, sup={t_sup:.2f}s)")

                per_image_times.append(row)

                # --- NEW: persist simple per-image status + DONE marker for resumability ---
                try:
                    with open(os.path.join(image_dir, "status.json"), "w") as f:
                        json.dump({
                            "image": base_name,
                            "processed_cracks": processed_cracks,
                            "mode": ("edges_only" if edges_only else "full"),
                            "edge_params_used": global_best_edge
                        }, f)
                    # touch a DONE flag so future runs auto-skip this image
                    open(done_flag, "a").close()
                except Exception as e:
                    print(f"[apply] could not write status/DONE for {base_name}: {e}")

            # --- summary per-image CSV ---
            if per_image_times:
                df_times = pd.DataFrame(per_image_times)
                df_times.to_csv(os.path.join(summ_dir, "global_per_image_runtime.csv"), index=False)
                print(f"[global-metrics] 🕒 per-image runtimes logged ({len(per_image_times)} images)")

            self.summarize_dataset_metrics()
            print("[global-metrics] ✅ finished")

            # --- aggregate all runtime logs from single-image runs ---
            all_logs = []
            for img in self.image_names:
                base = os.path.splitext(os.path.basename(img))[0]
                log_path = os.path.join(self.save_folder, "metrics", base, "runtime_log.csv")
                if os.path.exists(log_path):
                    df = pd.read_csv(log_path)
                    df["image"] = base
                    all_logs.append(df)
            if all_logs:
                df_all = pd.concat(all_logs, ignore_index=True)
                df_all.to_csv(os.path.join(summ_dir, "global_runtime.csv"), index=False)
                print(f"[global-metrics] 🕒 global_runtime.csv written ({len(all_logs)} images)")

        finally:
            self.n = orig_n
            self.change_image()

        tB = time.perf_counter() - tB_start
        t_total = tA + tB
        # --- final global runtime summary ---
        with open(os.path.join(summ_dir, "global_runtime_summary.txt"), "w") as f:
            f.write(f"Phase A (calibration): {tA:.2f} s\n")
            f.write(f"Phase B (application): {tB:.2f} s\n")
            f.write(f"Total runtime: {t_total:.2f} s\n")
            f.write(f"Mode: {'edges_only' if edges_only else 'full'}\n")
            f.write(f"Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")

        print(f"[global-metrics] ⏱ total runtime = {t_total:.2f}s (A={tA:.2f}s, B={tB:.2f}s)")'''

    def batch_run_metrics_global(
        self,
        sample_frac=0.10,
        max_images=10,
        seed=42,
        edge_grid=None,
        g_variants=None,
        cpu_max_workers=8,
        apply_to_sample=False,
        edges_only=False,
        edge_parallel_workers=None,
        rs3_strategy="full",
        rs3_fixed_family=None,
        image_indices=None,
        base_names=None,
        recompute_best_non_dt=True,
    ):
        return super().batch_run_metrics_global(
            sample_frac=sample_frac,
            max_images=max_images,
            seed=seed,
            edge_grid=edge_grid,
            g_variants=g_variants,
            cpu_max_workers=cpu_max_workers,
            apply_to_sample=apply_to_sample,
            edges_only=edges_only,
            edge_parallel_workers=edge_parallel_workers,
            rs3_strategy=rs3_strategy,
            rs3_fixed_family=rs3_fixed_family,
            image_indices=image_indices,
            base_names=base_names,
            recompute_best_non_dt=recompute_best_non_dt,
        )

    def export_gt_supervision_for_current_image(self):
        """
        One-click GT export:
        - Loads main annotation x.json (no snapshots)
        - Takes ONLY manual atomics
        - Groups atomics using pure GT logic (gt_groups_from_midlines_and_gtmask)
        - Calls export_gt_supervision_for_image(...) with GT mask
        """

        import os, json
        import numpy as np
        import cv2

        from helpers.supervision import (
            export_gt_supervision_for_image as _export_gt_sup,
        )
        from combiner import gt_groups_from_midlines_and_gtmask

        base_name = self._image_base()

        if getattr(self, "original_image", None) is None:
            print("[GT_SUP] no image loaded.")
            return

        if getattr(self, "current_mask", None) is None:
            print("[GT_SUP] no GT mask loaded.")
            return

        H, W = self.original_image.shape[:2]
        gt_mask = (self.current_mask > 0).astype(np.uint8)

        # -------------------------------
        # Load the main annotation JSON
        # -------------------------------
        ann_path = getattr(self, "ann_name", None)
        if not ann_path or not os.path.exists(ann_path):
            print(f"[GT_SUP] no annotation JSON for {base_name}")
            return

        def _bbox_snapshot_from_atomic(atomic_map):
            out = {}
            for _cid, _cr in (atomic_map or {}).items():
                if not isinstance(_cr, dict):
                    continue
                bb = _cr.get("mask_bbox", [])
                if isinstance(bb, (list, tuple)):
                    out[str(_cid)] = tuple(bb)
                else:
                    out[str(_cid)] = tuple()
            return out

        def _check_bbox_mutation(stage_name, atomic_map, ref_snapshot):
            mutated = []
            for _cid, _cr in (atomic_map or {}).items():
                if not isinstance(_cr, dict):
                    continue
                curr = tuple((_cr.get("mask_bbox", []) or []))
                prev = tuple(ref_snapshot.get(str(_cid), tuple()))
                if curr != prev:
                    mutated.append((str(_cid), prev, curr))
            if mutated:
                print(f"\n[ERROR] BBOX MUTATION DETECTED @ {stage_name}")
                for _cid, _prev, _curr in mutated:
                    print(f"  atomic {_cid}: {_prev} -> {_curr}")
            else:
                print(f"[CHECK] No bbox mutation @ {stage_name}")

        # Optional one-shot bbox repair called from GT supervision export.
        DEBUG_CALL_BBOX_REPAIR_IN_GT_SUP = True
        repaired_ann_json = None
        if DEBUG_CALL_BBOX_REPAIR_IN_GT_SUP:
            try:
                from pathlib import Path
                from tools.repair_atomic_bboxes import repair_bboxes as _repair_atomic_bboxes

                gt_sup_root = os.path.join(self.save_folder, "supervision", base_name)
                gt_sup_analysis = os.path.join(gt_sup_root, "analysis")
                os.makedirs(gt_sup_analysis, exist_ok=True)

                image_path = None
                try:
                    if hasattr(self, "image_names") and isinstance(getattr(self, "image_names", None), list):
                        image_path = self.image_names[self.n]
                except Exception:
                    image_path = None

                before_png = os.path.join(gt_sup_analysis, "bbox_repair_before.png")
                after_png = os.path.join(gt_sup_analysis, "bbox_repair_after.png")

                repaired_count, repaired_data = _repair_atomic_bboxes(
                    json_path=Path(ann_path),
                    contain_thresh=0.8,
                    weak_thresh=0.3,
                    image_path=(Path(image_path) if image_path else None),
                    before_png=Path(before_png),
                    after_png=Path(after_png),
                    return_data=True,
                )
                print(
                    f"[GT_SUP] bbox repair executed from export_gt_supervision_for_current_image "
                    f"(changed={int(repaired_count)})"
                )

                # Commit repaired state into live in-memory annotation (no heavy change_image()).
                if isinstance(repaired_data, dict):
                    repaired_ann_json = repaired_data
                    self.annotation = repaired_data
                    ann_root_live = self.annotation.setdefault("annotations", {})
                    self.combined_cracks = ann_root_live.get("combined_cracks", {}) or {}
                    try:
                        # Refresh light-weight snapshot structures from repaired authoring state.
                        self._sync_metrics_snapshot_from_authoring(
                            refresh_combine=False,
                            persist=False,
                        )
                    except Exception as _se:
                        print(f"[GT_SUP] snapshot refresh after bbox repair skipped: {_se}")
            except Exception as _e:
                print(f"[GT_SUP] bbox repair skipped/fail: {_e}")

        if isinstance(repaired_ann_json, dict):
            ann_json = repaired_ann_json
        else:
            with open(ann_path, "r", encoding="utf-8") as f:
                ann_json = json.load(f)

        authoring_atomic = (
            ann_json.get("annotations", {}) or {}
        ).get("atomic_cracks", {}) or {}

        # -----------------------------------------
        # Filter manual atomics ONLY (no snapshots)
        # -----------------------------------------
        def _is_manual(cr):
            src = (cr.get("source") or "").lower()
            return src in ("manual", "manual_poly", "manual_midline")

        atomic = {
            str(cid): cr
            for cid, cr in authoring_atomic.items()
            if _is_manual(cr)
        }

        try:
            atomic_debug_list = []
            for _cid, _cr in atomic.items():
                if not isinstance(_cr, dict):
                    continue
                atomic_debug_list.append({
                    "id": str(_cid),
                    "mask_bbox": _cr.get("mask_bbox"),
                    "midline": _cr.get("midline", []),
                })
            raw_dbg_png = os.path.join(self.save_folder, f"{base_name}_raw_json_atomics_debug.png")
            debug_plot_all_atomics(
                self.original_image,
                atomic_debug_list,
                title=f"RAW JSON DEBUG - {base_name}",
                out_png=raw_dbg_png,
                show=False,
            )
        except Exception as _e:
            print(f"[DEBUG ATOMICS] failed to render raw json view: {_e}")

        print(f"[GT_SUP] using {len(atomic)} manual atomics for {base_name}")

        if not atomic:
            print("[GT_SUP] no manual atomics, aborting.")
            return

        bbox_snapshot = _bbox_snapshot_from_atomic(atomic)
        _check_bbox_mutation("post-repair", atomic, bbox_snapshot)

        # -----------------------------------------
        # GT grouping (midlines + GT mask + endpoints)
        # -----------------------------------------
        combined_groups = gt_groups_from_midlines_and_gtmask(
            atomic=atomic,
            gt_mask=gt_mask,
            H=H,
            W=W,
        )
        _check_bbox_mutation("after-midline", atomic, bbox_snapshot)

        print(f"[GT_SUP] GT grouping produced {len(combined_groups)} combined groups.")

        # -----------------------------------------
        # Export manual GT supervision (atomic+combined)
        # -----------------------------------------
        _check_bbox_mutation("before-export", atomic, bbox_snapshot)
        # Temporarily set supervision debug target to current image.
        try:
            import helpers.supervision as _sup_mod
            _sup_mod.DEBUG_TARGET = str(base_name)
        except Exception:
            pass
        _export_gt_sup(
            base_name=base_name,
            save_root=self.save_folder,
            original_image=self.original_image,
            H=H,
            W=W,
            atomic=atomic,
            combined_groups=combined_groups,
            gt_mask=gt_mask,
            depth_full=getattr(self, "current_depth", None),
        )

        print(f"[EXPORT] GT supervision -> {len(atomic)} cracks ({base_name})")
     
    def run_et_metrics_current_image_quick(
        self, tau_px=3.0, crack_id=None, display=True, do_param_sweep=True,
        *, best_method_key=None, reexport=True, run_atomic_width_eval: bool = False,
    ):
        """
        Single-image DT/BEST/ET runner using the shared batch-compatible path.
        """
        import time

        if not getattr(self, "name", None):
            print("[metrics] no image loaded")
            return

        t0 = time.perf_counter()
        idx = int(getattr(self, "n", 0))
        edge_params = {"window_half_size": 45, "mu": 0.0, "l": 5, "p": 14, "seg_mode": "new"}

        res = self._run_metrics_for_image_idx(
            idx,
            edge_params=edge_params,
            export_supervision=bool(reexport),
            display=bool(display),
            best_method_key=best_method_key,
            edge_parallel_workers=None,
            run_atomic_width_eval=bool(run_atomic_width_eval),
        )
        print(f"[SMOKE] result={res}")
        try:
            tb = res.get("timing_breakdown", {}) if isinstance(res, dict) else {}
            if isinstance(tb, dict) and tb:
                print("[SMOKE TIMING] major groups (s):")
                for k in ("snapshot_sync_s", "edge_tracking_s", "metrics_total_s"):
                    if k in tb:
                        try:
                            print(f"  - {k}: {float(tb[k]):.3f}")
                        except Exception:
                            print(f"  - {k}: {tb[k]}")
                gt_sup = tb.get("gt_supervision", {})
                if isinstance(gt_sup, dict) and gt_sup:
                    print("[SMOKE TIMING] gt_supervision:")
                    for k, v in gt_sup.items():
                        try:
                            print(f"  - {k}: {float(v):.3f}")
                        except Exception:
                            print(f"  - {k}: {v}")
                core = tb.get("width_mask_core_by_supervision_s", {})
                if isinstance(core, dict) and core:
                    print("[SMOKE TIMING] core by supervision:")
                    for sup, sec in sorted(core.items(), key=lambda kv: str(kv[0])):
                        try:
                            print(f"  - {sup}: {float(sec):.3f}")
                        except Exception:
                            print(f"  - {sup}: {sec}")
                drv = tb.get("width_driver_step_s", {})
                if isinstance(drv, dict) and drv:
                    print("[SMOKE TIMING] width driver step totals:")
                    for step, sec in sorted(drv.items(), key=lambda kv: str(kv[0])):
                        try:
                            print(f"  - {step}: {float(sec):.3f}")
                        except Exception:
                            print(f"  - {step}: {sec}")
                try:
                    mtotal = float(tb.get("metrics_total_s", 0.0))
                    rows = tb.get("width_driver_rows", [])
                    if isinstance(rows, list) and rows:
                        known = float(
                            sum(
                                float(r.get("seconds", 0.0))
                                for r in rows
                                if str(r.get("step", "")) not in ("compare_widths_for_aligned_cracks_s",)
                            )
                        )
                    else:
                        known = float(sum(float(v) for v in (drv or {}).values()))
                    metrics_unaccounted = float(mtotal - known)
                    print(f"[SMOKE TIMING] metrics_unaccounted_s ~= {max(0.0, metrics_unaccounted):.3f}")
                except Exception:
                    pass
        except Exception as _tim_e:
            print(f"[SMOKE TIMING] parse failed: {_tim_e}")
        print(f"[SMOKE] elapsed={time.perf_counter() - t0:.2f}s")

    # Backward-compatible alias
    def run_manual_metrics_current_image_quick(
        self, tau_px=3.0, crack_id=None, display=True, do_param_sweep=True,
        *, best_method_key=None, reexport=True, run_atomic_width_eval: bool = False,
    ):
        return self.run_et_metrics_current_image_quick(
            tau_px=tau_px,
            crack_id=crack_id,
            display=display,
            do_param_sweep=do_param_sweep,
            best_method_key=best_method_key,
            reexport=reexport,
            run_atomic_width_eval=run_atomic_width_eval,
        )

    def _rs3_cache_complete_for_image(self, g_variants=None) -> bool:
        """
        Strict cache completeness check for quick-mode RS3 skip.
        Returns True only if every relevant manual crack has a canonical per-cid
        snapshot containing an auto-best result (or auto variants).
        """
        import os
        import json
        import numpy as np

        base_name = self._image_base()
        base_dir = os.path.join(self.save_folder, "metrics", base_name)

        atomic = {}
        try:
            atomic = dict(self._metric_atomic() or {})
        except Exception:
            atomic = {}

        # Fallback to authoring annotations if snapshot is not yet synced.
        if not atomic:
            ann = (getattr(self, "annotation", {}) or {}).get("annotations", {}) or {}
            atomic = dict(ann.get("atomic_cracks", {}) or {})

        required_cids = []
        for cid, cr in atomic.items():
            src = str((cr or {}).get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue

            mid = np.asarray((cr or {}).get("midline", []), float)
            if mid.ndim != 2 or mid.shape[1] != 2 or len(mid) < 2:
                continue

            required_cids.append(cid)

        if not required_cids:
            print("[RS3 CACHE] no eligible manual cracks for cache check")
            return False

        for cid in required_cids:
            canonical_json = os.path.join(base_dir, f"cid{cid}", f"cid{cid}.json")
            if not os.path.exists(canonical_json):
                print(f"[RS3 CACHE] missing file for cid={cid}: {canonical_json}")
                return False

            try:
                with open(canonical_json, "r", encoding="utf-8") as f:
                    snap = json.load(f) or {}
            except Exception:
                print(f"[RS3 CACHE] unreadable snapshot for cid={cid}")
                return False

            auto_best = snap.get("auto_best", None)
            has_auto_best = False
            if isinstance(auto_best, dict):
                ab_mid = np.asarray(auto_best.get("midline", []), float)
                has_auto_best = (ab_mid.ndim == 2 and ab_mid.shape[1] == 2 and len(ab_mid) >= 2)
            elif str(snap.get("source", "")).lower() == "auto_best":
                top_mid = np.asarray(snap.get("midline", []), float)
                has_auto_best = (top_mid.ndim == 2 and top_mid.shape[1] == 2 and len(top_mid) >= 2)

            has_auto_variants = isinstance(snap.get("variants"), (dict, list)) or isinstance(snap.get("auto_variants"), (dict, list))

            if not (has_auto_best or has_auto_variants):
                print(f"[RS3 CACHE] no auto_best/variants for cid={cid}")
                return False

        return True

    # ---- 8) Quick metrics driver (unified; snapshot-only) ----------------------
    def run_full_metrics_current_image(
        self,
        edge_grid=None,
        g_variants=None,
        cpu_max_workers=8,
        do_edge_calibrate=False,
        rs3_strategy="full",
        rs3_fixed_family=None,
        *,
        skip_recomputing_midlines=False,
    ):
        """
        Fast single-image execution of:
            - snapshot sync from AUTHORING
            - (optional) edge param sweep
            - edge tracking for MANUAL midlines (edge_param_worker + debug)
            - RS3 auto-variants per manual subcrack
            - global RS3 family selection
            - edge tracking for AUTO best (if present)
            - full mask/width metrics + supervision

        Uses the same snapshot structure as batch_run, but without global calibration.
        """
        
        # stopgap measure (leave edge calibration off unless explicitly re-enabled)
        do_edge_calibrate = False
        

        import os, time, numpy as np, pandas as pd
        from helpers import metrics
        from helpers.save_load_files import load_snapshot_from_files
        from helpers.variant_optimizer import apply_family_to_image

        if getattr(self, "original_image", None) is None:
            print("[quick] ❌ no image loaded")
            return {}

        def _resolve_fixed_rs3_family():
            if isinstance(rs3_fixed_family, dict):
                fam = dict(rs3_fixed_family)
            else:
                g0 = (g_variants[0] if isinstance(g_variants, (list, tuple)) and len(g_variants) else {}) or {}
                fam = {
                    "os_mode": "new",
                    "g11": float(g0.get("g11", 1.0)),
                    "g22": float(g0.get("g22", 25.0)),
                    "g33": float(g0.get("g33", 25.0)),
                }
            fam["os_mode"] = str(fam.get("os_mode", "new"))
            fam["g11"] = float(fam.get("g11", 1.0))
            fam["g22"] = float(fam.get("g22", 25.0))
            fam["g33"] = float(fam.get("g33", 25.0))
            return fam

        rs3_strategy_norm = str(rs3_strategy or "full").strip().lower()
        fixed_rs3_family = _resolve_fixed_rs3_family() if rs3_strategy_norm in {"default_only", "fixed"} else None

        base_name = self._image_base()
        print(f"\n[quick] metrics for current image: {base_name}")

        if skip_recomputing_midlines:
            if not self._rs3_cache_complete_for_image(g_variants):
                print("[quick] RS3 cache incomplete — forcing recompute")
                skip_recomputing_midlines = False
            else:
                print("[quick] RS3 cache complete — skipping recompute")

        # ------------------------------------------------------------
        # SAFETY CHECK — must have ≥2-pt manual midlines in AUTHORING
        # ------------------------------------------------------------
        ann = (getattr(self, "annotation", {}) or {}).get("annotations", {}) or {}
        atomic_authoring = ann.get("atomic_cracks", {}) or {}

        def _has_valid_manual_midlines(atomic_dict):
            for crack in atomic_dict.values():
                src = (crack.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue
                mid = crack.get("midline", [])
                if isinstance(mid, list) and len(mid) >= 2:
                    return True
            return False

        if not atomic_authoring or not _has_valid_manual_midlines(atomic_authoring):
            print(f"[DEBUG QUICK] 🧠¹ No valid manual midlines — purging snapshot for {base_name}")

            metrics_dir = os.path.join(self.save_folder, "metrics")
            snap_path = os.path.join(metrics_dir, f"{base_name}.json")
            if os.path.exists(snap_path):
                try:
                    os.remove(snap_path)
                    print(f"[DEBUG QUICK] Removed stale snapshot: {snap_path}")
                except Exception as e:
                    print(f"[DEBUG QUICK] ⚠ failed removing {snap_path}: {e}")

            if hasattr(self, "metric_annotations"):
                self.metric_annotations.clear()
                print("[DEBUG QUICK] Cleared in-memory metric_annotations")

            return {}

        # ------------------------------------------------------------
        # SNAPSHOT SYNC (CRITICAL for per-cid files + _metric_atomic)
        # ------------------------------------------------------------
        try:
            if not skip_recomputing_midlines:
                self._purge_metrics_for_current_image()
            else:
                print("[quick] preserving existing RS3 midlines + edges (no recompute)")
            # Builds metrics/<base>/cid*/cid*.json and sets self.metric_annotations
            self._sync_metrics_snapshot_from_authoring(
                refresh_combine=True,
                persist=True
            )
        except Exception as e:
            print(f"[quick] ⚠ snapshot sync failed: {e}")

        # ------------------------------------------------------------
        # SETUP
        # ------------------------------------------------------------
        image_dir = self._metrics_dir()
        os.makedirs(image_dir, exist_ok=True)
        t_total_start = time.perf_counter()

        # ------------------------------------------------------------
        # (OPTIONAL) EDGE PARAM CALIBRATION
        # ------------------------------------------------------------
        if edge_grid is None:
            edge_grid = [
                {"window_half_size": 45, "mu": 0, "l": 5, "p": 14, "seg_mode": "old"},
                {"window_half_size": 45, "mu": 0, "l": 5, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 0, "l": 2, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 0, "l": 8, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 2, "l": 5, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 5, "l": 5, "p": 14, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 2, "l": 5, "p": 2, "seg_mode": "new"},
                {"window_half_size": 45, "mu": 2, "l": 5, "p": 20, "seg_mode": "new"},
            ]

        # default params (always valid)
        best_edge = {"window_half_size": 45, "mu": 0.0, "l": 5, "p": 14, "seg_mode": "new"}

        t_edge_calib_start = time.perf_counter()

        # ------------------------------------------------------------
        # EDGE PARAM CALIBRATION (NO RECOMPUTE)
        # ------------------------------------------------------------
        if do_edge_calibrate:
            print("[quick] edge calibration sweep...")

            edge_packs = {}

            for cid, cr in self._metric_atomic().items():
                src = (cr.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue

                mid = np.asarray(cr.get("midline", []), float)
                if mid.ndim != 2 or len(mid) < 2:
                    continue

                df = self.sweep_edges_with_executor(
                    cid,
                    grid=edge_grid,
                    max_workers=cpu_max_workers,
                )

                if df is not None and not df.empty:
                    d = df.copy()
                    d["crack_id"] = cid
                    edge_packs[cid] = d

            sel = self.select_best_edge_family_across_subcracks(edge_packs)

            # --------------------------------------------------------
            # Normalize selector return shape (IMPORTANT)
            #   - old selector: returns {window_half_size, mu, l, p, seg_mode}
            #   - new selector: returns {"params": {...}, "per_crack_geom": {...}}
            # --------------------------------------------------------
            if sel is None:
                print("[quick] ⚠ edge family selection returned None — fallback to defaults")
                sel = {
                    "params": dict(window_half_size=45, mu=0.0, l=5, p=14, seg_mode="new"),
                    "per_crack_geom": {},
                }

            if isinstance(sel, dict) and "params" in sel:
                # NEW SHAPE
                best_edge_bundle = sel
                best_edge = dict(best_edge_bundle.get("params") or best_edge)
            else:
                # OLD SHAPE
                best_edge_bundle = {"params": dict(sel), "per_crack_geom": {}}
                best_edge = dict(sel)

        else:
            # no calibration → no bundle/caches
            best_edge_bundle = {"params": dict(best_edge), "per_crack_geom": {}}

        # ------------------------------------------------------------
        # APPLY EDGES FROM CACHE (ONLY if calibration produced caches)
        # ------------------------------------------------------------
        used_cache = False
        per_crack_geom = (best_edge_bundle or {}).get("per_crack_geom", {}) or {}

        if do_edge_calibrate and per_crack_geom:
            print("[quick] loading cached edges (no recompute)...")
            used_cache = True

            n_applied = 0
            for cid, info in per_crack_geom.items():
                geom_path = (info or {}).get("geom_cache_path", None)
                if not geom_path:
                    continue

                try:
                    data = np.load(geom_path, allow_pickle=True)

                    # Update the live crack dict directly (safest)
                    cr = self._metric_atomic().get(cid, None)
                    if cr is None:
                        continue

                    # Use .tolist() so JSON snapshot writing stays stable
                    # (np arrays inside dicts will bite you later)
                    if "mask_crop" in data:
                        cr["mask_crop"] = data["mask_crop"].tolist() if hasattr(data["mask_crop"], "tolist") else data["mask_crop"]

                    if "track_e1" in data:
                        cr["edge1"] = data["track_e1"].tolist() if hasattr(data["track_e1"], "tolist") else data["track_e1"]

                    if "track_e2" in data:
                        cr["edge2"] = data["track_e2"].tolist() if hasattr(data["track_e2"], "tolist") else data["track_e2"]

                    # normals
                    n1 = data["normals_e1"] if "normals_e1" in data else None
                    n2 = data["normals_e2"] if "normals_e2" in data else None
                    if n1 is not None or n2 is not None:
                        cr["normals"] = {
                            "edge1": n1.tolist() if hasattr(n1, "tolist") else n1,
                            "edge2": n2.tolist() if hasattr(n2, "tolist") else n2,
                        }

                    # record params used
                    cr["edge_params"] = dict(best_edge)
                    cr["edge_source"] = "cached_calibration"

                    n_applied += 1

                except Exception as e:
                    print(f"[quick] ⚠ cache load failed for cid={cid}: {e}")

            print(f"[quick] cached edges applied to {n_applied} cracks")
        else:
            if do_edge_calibrate:
                print("[quick] no cache map present — will recompute edges in Phase 1")

        t_edge_calib = time.perf_counter() - t_edge_calib_start
        if isinstance(best_edge, dict) and best_edge:
            print(f"[quick] edge selection: best_edge={best_edge}")
        print(f"[quick] ⏱ edge calibration total: {t_edge_calib:.2f}s")

        # ------------------------------------------------------------
        # PHASE 1: EDGE TRACKING FOR MANUAL CRACKS
        #   - If cache was applied: SKIP recompute
        #   - Else: run_edge_tracking_parallel (existing behavior)
        # ------------------------------------------------------------
        if used_cache:
            print("[quick] manual edge tracking skipped (cache already applied)")
            t_manual_edges = 0.0
        else:
            print("[quick] running edge tracking for MANUAL cracks (debug plots)...")
            t_manual_edges_start = time.perf_counter()

            manual_ids = []
            for cid, cr in self._metric_atomic().items():
                src = (cr.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue

                mid = np.asarray(cr.get("midline", []), float)
                if mid.ndim != 2 or mid.shape[1] != 2 or len(mid) < 2:
                    continue

                manual_ids.append(cid)

            print(f"[quick] manual cracks to edge-track: {manual_ids}")

            if manual_ids:
                try:
                    _ = self.run_edge_tracking_parallel(
                        crack_ids=manual_ids,
                        cpu_max_workers=cpu_max_workers,
                        edge_params_fixed=best_edge,  # <-- normalized plain params dict
                    )
                except Exception as e:
                    print(f"[quick] ⚠ manual edge tracking failed: {e}")

                # reload snapshot to ensure new edges are visible
                self.metric_annotations = load_snapshot_from_files(self.save_folder, base_name)

            t_manual_edges = time.perf_counter() - t_manual_edges_start
            print(f"[quick] manual-edge generation time = {t_manual_edges:.2f}s")
        
        #return
        # ------------------------------------------------------------
        # PHASE 1.5: RS3 AUTO VARIANTS (this image only)
        # ------------------------------------------------------------
        auto_packs = {}
        t_auto = 0.0
        if not skip_recomputing_midlines:
            print("[quick] running RS3 auto variants...")
            t_auto_start = time.perf_counter()
            rs3_g_variants_run = g_variants
            if fixed_rs3_family is not None:
                rs3_g_variants_run = [{
                    "g11": fixed_rs3_family["g11"],
                    "g22": fixed_rs3_family["g22"],
                    "g33": fixed_rs3_family["g33"],
                }]
                print(f"[quick] RS3 strategy={rs3_strategy_norm} using fixed family: {fixed_rs3_family}")

            for cid, cr in self._metric_atomic().items():
                src = (cr.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue

                mid = np.asarray(cr.get("midline", []), float)
                if mid.ndim != 2 or mid.shape[1] != 2 or len(mid) < 2:
                    continue

                pack = self.generate_auto_variants_for_et_parallel(
                    crack_id=cid,
                    g_variants=rs3_g_variants_run,
                    edge_params_fixed=best_edge,
                    cpu_max_workers=cpu_max_workers,
                    force_recompute=False,
                    os_ablation=False,
                    smoke_test=False
                )
                if pack:
                    auto_packs[cid] = pack

            t_auto = time.perf_counter() - t_auto_start

            # ------------------------------------------------------------
            # PHASE 1.6: SELECT BEST RS3 FAMILY (IMAGE-LEVEL)
            # ------------------------------------------------------------
            print("[quick] selecting/applying RS3 family for this image...")
            if auto_packs:
                try:
                    if fixed_rs3_family is not None:
                        apply_family_to_image(
                            fixed_rs3_family,
                            auto_packs,
                            base_name=base_name,
                            save_folder=self.save_folder,
                        )
                        print(f"[quick] applied fixed RS3 family (skipped selection): {fixed_rs3_family}")
                    else:
                        self._select_best_rs3_across_subcracks(auto_packs)
                except Exception as e:
                    print(f"[quick] ⚠ RS3 family selection failed: {e}")
            else:
                print("[quick] ⚠ no auto_packs; skipping RS3 family selection.")
        else:
            print("[quick] ⏩ skipping RS3 recomputation (using cached midlines)")

        #return
        # ------------------------------------------------------------
        # PHASE 2: GEODESIC EDGES FOR AUTO BEST MIDLINES
        # ------------------------------------------------------------
        print("[quick] generating geodesic edges for AUTO best midlines...")
        t_auto_edges_start = time.perf_counter()

        auto_ids = []
        for cid, cr in self._metric_atomic().items():
            # Depending on how _select_best_rs3_across_subcracks writes back,
            # this may be either a separate 'auto_best' source or just nested under manual.
            # Here we look for cracks explicitly marked as auto_best.
            src = (cr.get("source") or "").lower()
            if src == "auto_best":
                auto_ids.append(cid)

        print(f"[quick] auto cracks needing edges: {auto_ids}")

        if auto_ids:
            try:
                _ = self.run_edge_tracking_parallel(
                    crack_ids=auto_ids,
                    cpu_max_workers=cpu_max_workers,
                    edge_params_fixed=best_edge,
                    prefer_auto_best=True
                )
            except Exception as e:
                print(f"[quick] ⚠ auto-edgegen failed: {e}")

            # reload snapshot to include AUTO edges
            self.metric_annotations = load_snapshot_from_files(self.save_folder, base_name)

        t_auto_edges = time.perf_counter() - t_auto_edges_start
        print(f"[quick] auto-edge generation time = {t_auto_edges:.2f}s")
        
        #return

        # ------------------------------------------------------------
        # PHASE 3: MASK + WIDTH METRICS + SUPERVISION
        # ------------------------------------------------------------
        t_metrics_start = time.perf_counter()
        try:
            self.compute_mask_and_width_metrics_for_image(
                display=False,
                export_supervision=True,
                include_auto=True
            )
        except Exception as e:
            print(f"[quick] ❌ compute_mask_and_width_metrics_for_image failed: {e}")
            import traceback
            traceback.print_exc()
        t_metrics = time.perf_counter() - t_metrics_start

        # ------------------------------------------------------------
        # LOGGING
        # ------------------------------------------------------------
        total_time = time.perf_counter() - t_total_start
        log_path = os.path.join(image_dir, "runtime_log.csv")

        row = {
            "image": base_name,
            "edge_calibration_s": round(t_edge_calib, 2),
            "edge_generation_manual_s": round(t_manual_edges, 2),
            "auto_variants_s": round(t_auto, 2),
            "auto_edgegen_s": round(t_auto_edges, 2),
            "mask_width_s": round(t_metrics, 2),
            "total_s": round(total_time, 2),
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        }

        try:
            if os.path.exists(log_path):
                df = pd.read_csv(log_path)
                df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
            else:
                df = pd.DataFrame([row])
            df.to_csv(log_path, index=False)
        except Exception as e:
            print(f"[quick] ⚠ failed to write runtime_log.csv: {e}")

        print(
            f"[quick] ⏱ total = {total_time:.2f}s "
            f"(edge_calib={t_edge_calib:.2f}s, manual-edgegen={t_manual_edges:.2f}s, "
            f"auto={t_auto:.2f}s, auto-edgegen={t_auto_edges:.2f}s, mask_width={t_metrics:.2f}s)"
        )

        return {"image": base_name, "best_edge": best_edge}
    
    
    
    
if __name__ == "__main__":
    from time import time
    _force_pyqt5_qt_plugin_paths()
    try:
        # Ensure Windows taskbar groups this app with our custom icon.
        if sys.platform.startswith("win"):
            import ctypes
            ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(
                "cracktool.app.mainwindow"
            )
    except Exception as e:
        print(f"[ICON] warning: failed to set AppUserModelID: {e}")

    app = QtWidgets.QApplication(sys.argv)
    try:
        app_root = os.path.dirname(os.path.abspath(__file__))
        icon_candidates = [
            os.path.join(app_root, "images", "6.png"),
            os.path.join(app_root, "cracktools", "Picture2.png"),
            os.path.join(app_root, "images", "TUe_logo.png"),
            os.path.join(app_root, "images", "TUe_logo.ico"),
        ]
        for icon_path in icon_candidates:
            if os.path.isfile(icon_path):
                icon = QtGui.QIcon(icon_path)
                if not icon.isNull():
                    app.setWindowIcon(icon)
                    break
    except Exception as e:
        print(f"[ICON] warning: failed to set app icon: {e}")
    font = QtGui.QFont()
    font.setPointSize(7)
    app.setFont(font)
    MainWindow = QtWidgets.QMainWindow()
    try:
        MainWindow.setWindowIcon(app.windowIcon())
    except Exception:
        pass
    ui = CrackToolsApplication()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


