# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cracktools as ct
from helpers.layout import Ui_MainWindow
from helpers.metrics import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import Qt
import skimage
import numpy as np
import cv2
import matplotlib
matplotlib.use("Agg")   # fastest non-GUI backend for PNG/PDF/SVG export
matplotlib.rcParams.update({
    "figure.max_open_warning": 0,
    "text.kerning_factor": 0,
    "font.family": "DejaVu Sans",
    "axes.unicode_minus": False,
})
import matplotlib.pyplot as plt
plt.ioff()   # no interactive figure updates

import json
import os
from skimage.segmentation import mark_boundaries
import os
from PyQt5.QtWidgets import QListWidgetItem
from shapely import geometry, ops
import pandas as pd

from crackutils import *
from manual_drawing import *
from track_segment_pipeline import *
from helpers.crackhelpers import *
#from helpers import *
from helpers import plot_metrics
from helpers import metrics
from helpers import save_load_files
from combine_clear_segments import *
from metrics_engine import *
import cracktools as ct

from concurrent.futures import ProcessPoolExecutor, as_completed
import itertools, pandas as pd, os
from edge_workers import *

from rs3_split import run_rs3_variants_split
from edge_workers import *
from combiner import *


#from crackutils import CrackUtils
DEBUG_SAVE_LIGHT = True   # True → only high-res compact outputs
from helpers.endpoint_annotator import CrackAnnotator
min_crop_size = 16   
class CrackToolsApplication(MetricsEngine, ManualDrawing, TrackSegmentPipeline, CombineClearSegments, CrackUtils, Ui_MainWindow):
    def setupUi(self, MainWindow):
        super().setupUi(MainWindow)
        
        #Select Image Tab
        self.MainWindow = MainWindow
        self.SelectFolderButton.clicked.connect(self.select_folder)
        self.PreviousImageButton.clicked.connect(self.previous_image)
        self.NextImageButton.clicked.connect(self.next_image)
        self.files_list.itemSelectionChanged.connect(self.name_selected)
        
        self.combine_segments_button.clicked.connect(self.combine_segments)
        #self.calculate_metrics_button.clicked.connect(lambda: self.run_mask_metrics(display=True))
        self.calculate_metrics_button.clicked.connect(lambda: self.run_manual_metrics_current_image_quick(tau_px=3.0, crack_id=None))
        #self.batch_metrics_button.clicked.connect(lambda: self.batch_run_metrics_global(sample_frac=.2,max_images=10,seed=0,cpu_max_workers=8,apply_to_sample=False,edges_only=False))
        self.batch_metrics_button.clicked.connect(
            lambda: self.run_full_metrics_current_image(
                edge_grid=None,
                g_variants=None,
                cpu_max_workers=8,
                do_edge_calibrate=True
            )
        )

        
        
        self.draw_box_button.clicked.connect(self.draw_box)
        self.save_b_button.clicked.connect(self.save_boxes)
        
        self.clear_boxes_button.clicked.connect(self.clear_boxes)
        self.clear_segmentation_button.clicked.connect(self.clear_segmentation)
        self.clear_combined_cracks_button.clicked.connect(self.clear_combined_cracks)




        #Tracking Tab
        self.select_points_button.clicked.connect(self.select_save_end_points)
        self.export_gt_supervision.clicked.connect(self.export_gt_supervision_for_current_image)
        self.update_image_crop_button.clicked.connect(self.update_image_crop)
        self.wavelet_button.clicked.connect(self.check_wavelet)
        self.middle_point_button.clicked.connect(self.select_middle_point)
        self.middpoint_update_button.clicked.connect(self.update_midpoint_image)
        self.BatchPipelineButton.clicked.connect(self.batch_run_pipeline)
        self.update_os_button.clicked.connect(self.update_os)
        self.update_cost_button.clicked.connect(self.update_os_cost)
        self.midline_track_button.clicked.connect(self.midline_tracking)

        # Repurpose the OS button for full pipeline
        try:
            self.update_os_button.clicked.disconnect()
        except Exception:
            pass
        self.update_os_button.setText("Run Pipeline")
        self.update_os_button.clicked.connect(self.run_pipeline)




        #Segmentation Tab
        self.edge_mask_button.clicked.connect(self.edge_mask)
        self.edge_tracks_button.clicked.connect(self.edge_tracking)
        self.update_track_display_button.clicked.connect(self.update_track_display)
        self.track_full_screen_button.clicked.connect(self.track_full_screen)
        self.edge_tracks_full_screen_button.clicked.connect(self.edge_tracks_full_screen)
        self.save_current_segment_button.clicked.connect(self.save_current_segment)
 
       
       
        
        #Add segment manually tab
        self.draw_segment_button.clicked.connect(lambda: self.draw_segment('add'))
        self.erase_segment_button.clicked.connect(self.erase_segment)
        self.reset_segment_button.clicked.connect(self.reset_canvas)
        self.save_manuall_segment_button.clicked.connect(self.save_manual_segment)
        self.manual_segment_full_screen_button.clicked.connect(self.manual_segment_full_screen)

        self.n = -1
        self.saved = False

        self.update_image_crop_button.setStyleSheet("background-color : red")
        self.middle_point_button.setStyleSheet("background-color : red")
        self.middpoint_update_button.setStyleSheet("background-color : red")
        self.update_os_button.setStyleSheet("background-color : red")
        self.update_cost_button.setStyleSheet("background-color : red")
        self.midline_track_button.setStyleSheet("background-color : red")
        self.update_track_display_button.setStyleSheet("background-color : red")
        self.track_full_screen_button.setStyleSheet("background-color : red")
        self.edge_mask_button.setStyleSheet("background-color : red")
        self.edge_tracks_button.setStyleSheet("background-color : red")
        self.edge_tracks_full_screen_button.setStyleSheet("background-color : red")
        self.save_current_segment_button.setStyleSheet("background-color : red")
        self.draw_segment_button.setStyleSheet("background-color : red")
        self.erase_segment_button.setStyleSheet("background-color : orange")
        self.reset_segment_button.setStyleSheet("background-color : lightblue")
        self.save_manuall_segment_button.setStyleSheet("background-color : lightgreen")
        
        self.show_os_button.setStyleSheet("background-color : red")
        
        #self.mask_pipeline_button.setStyleSheet("background-color : red")
        
    def _purge_metrics_for_current_image(self):
        """
        Remove metrics artifacts for the CURRENT image only.
        Safe: does not touch other images.
        """
        import os, shutil

        base = self._image_base()   # canonical image key
        metrics_root = os.path.join(self.save_folder, "metrics")
        image_dir = os.path.join(metrics_root, base)

        if os.path.isdir(image_dir):
            try:
                shutil.rmtree(image_dir)
                print(f"[METRICS] 🧹 Purged metrics for image '{base}'")
            except Exception as e:
                print(f"[METRICS] ⚠ Failed to purge metrics for '{base}': {e}")
    
    def run_pipeline(self, multirun=False):
        import gc, json
        import numpy as np
        from PyQt5.QtWidgets import QMessageBox
        from time import time

        # ---- helpers ---------------------------------------------------------
        def _ensure_ann():
            # make sure base structure exists
            if not hasattr(self, "annotation") or not isinstance(self.annotation, dict):
                self.annotation = {}
            ann = self.annotation.setdefault("annotations", {})
            ann.setdefault("atomic_cracks", {})
            ann.setdefault("combined_cracks", {})
            # scrub stray non-numeric keys
            bad_keys = [k for k in ann["atomic_cracks"].keys() if not str(k).isdigit()]
            for bk in bad_keys:
                ann["atomic_cracks"].pop(bk, None)
            return ann

        def _next_crack_id_str():
            """
            Return the lowest non-negative id that is NOT used in saved atomic_cracks.
            This ignores any in-memory caches so deleted ids are reused.
            """
            ann = self.annotation.get("annotations", {})
            ac = ann.get("atomic_cracks", {})
            used = sorted(int(k) for k in ac.keys() if str(k).isdigit())
            nxt = 0
            for k in used:
                if k == nxt:
                    nxt += 1
                elif k > nxt:
                    break
            return str(nxt)

        # ---- start -----------------------------------------------------------
        gc.collect()
        print("✅ GPU memory freed from CuPy pool")
        print("Running midline pipeline (auto + manual)...")

        # reset scratch between runs so ids don't leak/inflate
        self.current_crack_id = None
        self.crack_tracks = {}        # in-memory geodesic paths per id (scratch only)

        ann = _ensure_ann()
        ac_store = ann["atomic_cracks"]

        # Keep crack bbox assignments coherent with current user boxes before grouping pairs.
        if hasattr(self, "_rematch_crack_bboxes_to_boxes"):
            try:
                self._rematch_crack_bboxes_to_boxes()
            except Exception as e:
                print(f"[bbox rematch] run_pipeline preflight failed: {e}")

        boxes = self.get_all_bounding_boxes()
        print(f"Loaded {len(boxes)} bounding boxes: {boxes}")
        if not boxes:
            QMessageBox.critical(None, "No Bounding Boxes",
                "Please draw at least one bounding box before running the pipeline.")
            return

        if not multirun:
            # Let the user pick points/connections/midlines
            self.endpoint_pairs = None
            self.user_connections = None
            self.user_points = None
            self.manual_endpoint_pairs = None
            self.all_selected_points = None  # reset before each run
            print("Calling select_end_points_manmidlines()...")
            self.select_end_points_manmidlines(metrics=False)

        # Merge auto + manual endpoint pairs (global, from annotator)
        all_pairs = []
        if getattr(self, "endpoint_pairs", None):
            print(f"Auto endpoint_pairs: {self.endpoint_pairs}")
            all_pairs.extend([(p, "auto") for p in self.endpoint_pairs])

        if getattr(self, "manual_endpoint_pairs", None):
            print(f"Manual endpoint_pairs: {self.manual_endpoint_pairs}")
            all_pairs.extend([(p, "manual") for p in self.manual_endpoint_pairs])

        if not all_pairs:
            QMessageBox.critical(
                None, "No Endpoint Pairs",
                "No endpoint pairs selected!\n\nPlease use 'Select Endpoints' and create at least one connection or manual midline before running the pipeline."
            )
            return

        # Group by bbox (so OS/cost is reused per box)
        box_to_pairs = {}
        for (pair, src) in all_pairs:
            candidates = []
            for bbox in boxes:
                xmin, ymin, xmax, ymax = bbox
                p0, p1 = pair
                if (xmin <= p0[0] <= xmax and ymin <= p0[1] <= ymax and
                    xmin <= p1[0] <= xmax and ymin <= p1[1] <= ymax):
                    area = abs((xmax - xmin) * (ymax - ymin))
                    candidates.append((area, bbox))
            if candidates:
                _, chosen_bbox = min(candidates, key=lambda x: x[0])
                key = tuple(chosen_bbox)
                box_to_pairs.setdefault(key, []).append((pair, src))

        errors = []

        # Make sure we don't blow away memory of previous masks
        if not hasattr(self, "mask"):
            self.mask = []

        for bbox_key, pairs in box_to_pairs.items():
            xmin, ymin, xmax, ymax = bbox_key
            print(f"\n=== Processing bbox {bbox_key} ===")
            print(f"Pairs in this box: {pairs}")

            try:
                # Precompute OS/cost once per box for auto pairs
                auto_pairs = [p for p, s in pairs if s == "auto"]
                if auto_pairs:
                    first_pair = auto_pairs[0]
                    print(f"Precomputing OS/cost for auto pair {first_pair}")
                    self.pts = [np.array(first_pair[0]), np.array(first_pair[1])]
                    self.end_points = self.pts
                    self.active_bbox = list(bbox_key)
                    self.update_image_crop()
                    if getattr(self, "skip_current_segment", False):
                        continue
                    print("os (once per box)")
                    self.update_os_cost()
                    #t0 = time(); self.update_os(); print(f"os time: {time()-t0:.2f}s")
                    #print("cost (once per box)")
                    #t0 = time(); self.update_cost(); print(f"cost time: {time()-t0:.2f}s")

                # Process each pair -> one atomic crack per pair
                for (p0, p1), src in pairs:
                    try:
                        self.active_bbox = list(bbox_key)
                        print(f"\n--- Processing pair {(p0, p1)} (source={src}) ---")

                        # Per-crack, pair-local endpoints for saving
                        pair_user_points = [tuple(p0), tuple(p1)]
                        pair_user_connections = [[0, 1]]  # exactly one connection per crack

                        if src in ("manual", "manual_poly"):
                            # For manual, we reuse the drawn polyline as midline (full-image coords)
                            manual_midlines_dict = getattr(self, "manual_midlines_tmp", {})
                            found_key = None

                            # Durable copy of selection points from earlier
                            all_points = getattr(self, "all_selected_points", None)
                            if all_points is None:
                                all_points = getattr(self, "user_points", [])

                            print("\n[DEBUG] --- Matching manual midline ---")
                            print(f"[DEBUG] manual_midlines_tmp keys at runtime: {list(manual_midlines_dict.keys())}")
                            print(f"[DEBUG] all_points at runtime: {all_points}")
                            print(f"[DEBUG] Trying to match p0={p0}  p1={p1}")

                            # manual_midlines_tmp keys are "i_j" from annotator indices; match geometrically     
                            for k, poly in manual_midlines_dict.items():
                                try:
                                    # handle both tuple keys (2,3) and string keys "2_3"
                                    if isinstance(k, tuple) and len(k) == 2:
                                        i1, i2 = map(int, k)
                                    elif isinstance(k, str) and "_" in k:
                                        i1, i2 = map(int, k.split("_"))
                                    else:
                                        print(f"[DEBUG] Unrecognized key format: {k!r}")
                                        continue

                                    c_i = tuple(all_points[i1])
                                    c_j = tuple(all_points[i2])
                                    print(f"[DEBUG] Checking key={k}, c_i={c_i}, c_j={c_j}")
                                    if (c_i, c_j) == (p0, p1) or (c_i, c_j) == (p1, p0):
                                        print(f"[DEBUG] Found match for key={k}")
                                        found_key = k
                                        break
                                except Exception as e:
                                    print(f"[DEBUG] Error parsing key={k}: {e}")

                            print(f"[MANUAL] Found key: {found_key}")
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.update_image_crop()
                            if getattr(self, "skip_current_segment", False):
                                continue

                            if found_key:
                                # Convert full-image manual polyline to crop coords and set as self.track
                                poly = np.array(manual_midlines_dict[found_key], dtype=float)  # [[x,y],...]

                                """print("\n[DBG MANUAL POLYLINE] first 20 (FULL IMAGE COORDS):")
                                for i, (x, y) in enumerate(poly[:20]):
                                    print(f"  {i:02d}: ({x:.6f}, {y:.6f})")"""

                                cy = poly[:, 1] - ymin
                                cx = poly[:, 0] - xmin

                                """print("\n[DBG AFTER CROP OFFSET] first 20:")
                                for i in range(min(20, len(cx))):
                                    print(f"  {i:02d}: cx={cx[i]:.6f}, cy={cy[i]:.6f}")"""

                                self.track = np.vstack([cy, cx])

                                """print("\n[DBG TRACK ARRAY]")
                                print(f"  dtype: {self.track.dtype}")
                                print(f"  shape: {self.track.shape}")

                                print("[DBG TRACK first 20]:")
                                for i in range(min(20, self.track.shape[1])):
                                    print(f"  {i:02d}: (y={self.track[0, i]:.6f}, x={self.track[1, i]:.6f})")"""

                                # ---- endpoint bookkeeping (unchanged) ----
                                self.pts_crop = [
                                    np.array(self.pts[0]) - np.array([xmin, ymin]),
                                    np.array(self.pts[1]) - np.array([xmin, ymin])
                                ]

                                downsample = self.downsample_factor_box.value()
                                self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            else:
                                msg = f"No manual polyline found for manual crack {p0}→{p1}"
                                print("ERROR:", msg)
                                errors.append(msg)
                                continue
                        else:
                            # Auto mode
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.pts_crop = [np.array(pt) - np.array([xmin, ymin]) for pt in self.pts]
                            downsample = self.downsample_factor_box.value()
                            self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            t0 = time(); self.midline_tracking(); print(f"    midline tracking time: {time()-t0:.2f}s")

                            # --- normalize track like generate_auto_variant_for_manual ---
                            if getattr(self, "track", None) is not None:
                                try:
                                    tr = np.asarray(self.track, float)
                                    if tr.shape[0] == 2:
                                        track_xy = tr.T
                                    else:
                                        track_xy = tr

                                    p0g = np.asarray(p0, float)
                                    p1g = np.asarray(p1, float)

                                    # reverse if needed (ensure start = p0)
                                    d_start_p0 = np.linalg.norm(track_xy[0] - p0g)
                                    d_start_p1 = np.linalg.norm(track_xy[0] - p1g)
                                    if d_start_p1 < d_start_p0:
                                        track_xy = track_xy[::-1]
                                        print(f"[PIPE ALIGN] reversed path so first sample anchors at p0 (d_start_p0={d_start_p0:.2f}, d_start_p1={d_start_p1:.2f})")
                                    else:
                                        print(f"[PIPE ALIGN] path already starts near p0 (d_start_p0={d_start_p0:.2f}, d_start_p1={d_start_p1:.2f})")

                                    # translate so first point == p0
                                    delta = p0g - track_xy[0]
                                    track_xy = track_xy + delta

                                    # convert to local coords (crop relative)
                                    xmin, ymin, xmax, ymax = bbox_key
                                    track_local = track_xy - np.array([xmin, ymin])
                                    track_local[:,0] = np.clip(track_local[:,0], 0, xmax - xmin - 1)
                                    track_local[:,1] = np.clip(track_local[:,1], 0, ymax - ymin - 1)
                                    self.track = track_local.T

                                    print(f"[PIPE ALIGN] normalized track: start Δ={np.linalg.norm(track_local[0] - (p0g - np.array([xmin, ymin]))):.2f}px")
                                except Exception as e:
                                    print(f"[PIPE ALIGN] ⚠ failed to normalize: {e}")
                        
                        # ======= Assign a brand-new crack ID for THIS pair (gap-free) =======
                        new_cid = _next_crack_id_str()
                        self.current_crack_id = int(new_cid)

                        def _dbg_track(label, track, n=20):
                            print(f"\n[DBG {label}]")
                            if track is None:
                                print("  track is None")
                                return
                            print(f"  dtype={track.dtype}, shape={track.shape}")
                            pts = track[:, :min(n, track.shape[1])]
                            for i in range(pts.shape[1]):
                                y, x = pts[:, i]
                                print(f"  {i:02d}: (y={y:.6f}, x={x:.6f})")

                        _dbg_track("PRE edge_mask (track)", self.track)

                        # Geodesic edges & masks for this pair
                        self.current_source = src
                        start_time = time()
                        self.edge_mask()
                        edgemask_time = time()
                        _dbg_track("EXIT edge_mask (track)", self.track)
                        print()
                        print(f"[TIME] Edge mask time: {edgemask_time - start_time}")
                        self.edge_tracking()
                        print()
                        print(f"[TIME] Edge tracking time: {time() - edgemask_time}")
                        _dbg_track("EXIT edge_tracking (track)", self.track)

                        # Pair-local globals so save_current_segment writes them into that crack
                        self.user_points = pair_user_points
                        self.user_connections = pair_user_connections
                        
                        # === QUICK TEST TRIPWIRE ===
                        print(f"[TRIPWIRE] about to save crack with src={src}, p0={p0}, p1={p1}")
                        print(f"   track shape: {getattr(self, 'track', None).shape if hasattr(self, 'track') else None}")
                        print(f"   current_crack_id={self.current_crack_id}")
                        print(f"   manual_midlines_tmp keys: {list(getattr(self, 'manual_midlines_tmp', {}).keys())}")
                        print(f"   total atomic before save: {len(self.annotation['annotations']['atomic_cracks'])}")

                        # 🧠  For now, bail early to inspect what’s going on — no file write, no mutation
                        #return

                        # Save segment (midline + edges + mask + per-crack endpoints)
                        savetime = time()
                        self.save_current_segment()
                        print()
                        print(f"[TIME] Save current segment time: {time() - savetime}")

                        # Clear pair-local globals so next crack doesn't inherit them
                        self.user_points = None
                        self.user_connections = None

                    except Exception as e:
                        errors.append(f"Failed midline for {(p0, p1)}: {e}")
                        continue

            except Exception as e:
                errors.append(f"Failed for bbox {bbox_key}: {e}")
                continue

        # Done with all boxes/pairs
        if errors:
            print("\n".join(errors))
        else:
            print("✔ All endpoint groups processed.")

        # Clear UI temp state (per-run scratch)
        self.endpoint_pairs = None
        self.manual_endpoint_pairs = None

        # Persist JSON
        #self.save_annotation()
            
        self.auto_combine_segments()

        # Debug print & refresh view
        self._debug_print_atomic_cracks("run_pipeline END")
        self.change_image()
            
    #TODO: actually implement this
    def batch_run_pipeline(self):
        """
        Runs the pipeline (full segment generation, clearing endpoints/connections) on EVERY image in the selected folder.
        """
        from PyQt5.QtWidgets import QMessageBox
        
        # Check existence and content
        if not hasattr(self, "image_names") or not self.image_names:
            QMessageBox.warning(self.MainWindow, "Batch Run", "No images loaded. Please select a folder with images first.")
            print("Batch run aborted: no images loaded.")
            return
        
        total = len(self.image_names)
        errors = []
        n_success = 0
        orig_n = self.n

        for idx, fname in enumerate(self.image_names):
            try:
                self.n = idx
                self.change_image()
                # Only run if endpoints and connections are present
                endpoints = getattr(self, "user_points", None)
                connections = getattr(self, "user_connections", None)
                if endpoints and connections:
                    print(f"\n======= Processing image {idx+1}/{total}: {fname} =======")
                    self.run_pipeline(multirun=True)  # Will clear endpoints on success
                    n_success += 1
                    #return
                else:
                    print(f"  [SKIP] No endpoints/connections for this image.")
            except Exception as e:
                errors.append(f"Image {fname}: {e}")

        self.n = orig_n
        self.change_image()
        summary = f"Batch pipeline run complete.\nSuccessful: {n_success}/{total}\n"
        if errors:
            summary += f"\nErrors:\n" + "\n".join(errors)
        print(summary)
        QMessageBox.information(self.MainWindow, "Batch pipeline finished", summary)
  
    #####################################
    # New functions
    #####################################

    '''def batch_run_metrics_global(
            self,
            sample_frac=0.20,          # % of images to use for global calibration
            max_images=10,             # cap for calibration phase
            seed=0,
            edge_grid=None,            # if None → sensible default below
            g_variants=None,           # if None → defaults inside generate_auto_variants_for_manual_parallel
            cpu_max_workers=4,
            apply_to_sample=False,     # False → apply global params to ALL images; True → sampled set only
            edges_only=False,          # True → skip RS3; parallelize edge masks/tracking per crack
            edge_parallel_workers=None # override worker count for the edge-only branch
        ):
        """
        GLOBAL METRICS DRIVER (one image in memory at a time, no manual edge precompute needed).
        - Prefilters calibration pool to images that actually have manual midlines (≥2 pts).
        - Includes timing for calibration + per-image application.
        - If `edges_only=True`, skips RS3 variants and runs parallel edge tracking per crack.

        Writes:
        metrics/_summary/global_edge_sweep_all.csv
        metrics/_summary/global_best_edge_params.json
        metrics/_summary/global_per_image_runtime.csv
        metrics/_summary/global_runtime.csv
        metrics/_summary/global_runtime_summary.txt
        """
        import os, json, random, time
        import numpy as np, pandas as pd

        if not getattr(self, "image_names", []):
            print("[global-metrics] no images loaded")
            return

        # -------------- build an eligible calibration pool (must have manual midlines) --------------
        def _ann_path_for_image(idx: int) -> str:
            """Derive the expected annotation JSON path for image index `idx`."""
            import os
            img_path  = self.image_names[idx]
            base_name = os.path.splitext(os.path.basename(img_path))[0]
            # Your code stores annotations directly under `self.save_folder` as `<base>.json`
            # e.g. .../Outputs/1.json (as seen in your logs)
            return os.path.join(self.save_folder, f"{base_name}.json")

            ann    = (data or {}).get("annotations", {}) or {}
            atomic = ann.get("atomic_cracks", {}) or {}
            if not atomic:
                return False

            for crack in atomic.values():
                src = (crack.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue
                mid = crack.get("midline", [])
                # Enough points to be meaningful
                if isinstance(mid, list) and len(mid) >= 2:
                    return True
            return False

        """def _has_manual_midlines_for_index(idx: int) -> bool:
            """
            Fast path:
            (1) if per-image JSON doesn't exist → False (skip)
            (2) if JSON exists and has manual ≥2-pt midlines → True (no change_image() cost)
            (3) else, do a final in-memory check via change_image() (robustness)
            """
            import contextlib
            ann_path = _ann_path_for_image(idx)
            if not os.path.exists(ann_path):
                return False
            if _json_has_manual_midlines(ann_path):
                return True"""
        # Fallback: load
        def _has_manual_midlines_for_index(idx: int) -> bool:
            """
            Fast path:
            (1) if per-image JSON doesn't exist → False (skip)
            (2) if JSON exists and has manual ≥2-pt midlines → True (no change_image() cost)
            (3) else, do a final in-memory check via change_image() → True/False
            """
            ann_path = _ann_path_for_image(idx)
            if not os.path.exists(ann_path):
                return False
            if metrics._json_has_manual_midlines(ann_path):
                return True

            # Final in-memory check (robust against any stale/legacy JSON)
            orig_n = getattr(self, "n", 0)
            try:
                self.n = idx
                self.change_image()
                ann = (self.annotation or {}).get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    return False
                for crack in atomic.values():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    mid = crack.get("midline", [])
                    if isinstance(mid, list) and len(mid) >= 2:
                        return True
                return False
            except Exception:
                return False
            finally:
                # restore original index
                try:
                    self.n = orig_n
                    self.change_image()
                except Exception:
                    pass


        rng = random.Random(seed)
        all_idxs = list(range(len(self.image_names)))
        eligible_idxs = [i for i in all_idxs if _has_manual_midlines_for_index(i)]
        if not eligible_idxs:
            print("[global-metrics] ❌ No images with manual midlines found — aborting.")
            # try to restore a reasonable state
            if all_idxs:
                self.n = 0
                self.change_image()
            return

        rng.shuffle(eligible_idxs)
        k = max(1, int(len(eligible_idxs) * float(sample_frac)))
        idxs_sample = eligible_idxs[:min(k, max_images)]
        print(f"[global-metrics] calibration on {len(idxs_sample)} images "
            f"(from {len(eligible_idxs)} eligible / {len(all_idxs)} total)")

        if edge_grid is None:
            edge_grid = {
                "window_half_size": [35, 45, 55],
                "mu": [0, 5],
                "l": [2, 5],
                "p": [6, 14],
            }

        sweep_rows = []
        orig_n = self.n
        summ_dir = os.path.join(self.save_folder, "metrics", "_summary")
        os.makedirs(summ_dir, exist_ok=True)

        # --- PHASE A: Calibration timer ---
        tA_start = time.perf_counter()
        try:
            for t, i in enumerate(idxs_sample, 1):
                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [calibrate] {t}/{len(idxs_sample)}: {base_name} ======")

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    print("  [skip] no atomic cracks in annotation")
                    continue

                n_manual = 0
                for cid, crack in atomic.items():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    man_xy = metrics._finite_xy(crack.get("midline", []))
                    if len(man_xy) < 2:
                        continue
                    n_manual += 1

                    df_sweep = self.sweep_edges_with_executor(
                        cid, grid=edge_grid, max_workers=cpu_max_workers
                    )
                    if df_sweep is None or df_sweep.empty:
                        print(f"    [cid {cid}] sweep returned empty (no payload or worker error)")
                        continue

                    df_sweep = df_sweep.copy()
                    df_sweep["image"]    = base_name
                    df_sweep["crack_id"] = cid
                    sweep_rows.append(df_sweep)

                if n_manual == 0:
                    print("  [skip] no manual midlines ≥2 points in this image")

            # Either choose best from sweeps or fall back
            if sweep_rows:
                df_all = pd.concat(sweep_rows, ignore_index=True)
                df_all.to_csv(os.path.join(summ_dir, "global_edge_sweep_all.csv"), index=False)

                param_cols = ["param_window_half_size", "param_mu", "param_l", "param_p"]
                keep_cols  = param_cols + ["nn_mean_bidirectional", "hausdorff_max", "coverage_min"]
                sub = df_all[[c for c in keep_cols if c in df_all.columns]].dropna()

                g = (sub.groupby(param_cols, as_index=False)
                        .agg({"nn_mean_bidirectional":"mean","hausdorff_max":"mean","coverage_min":"mean"}))
                g = g.sort_values(["nn_mean_bidirectional","hausdorff_max","coverage_min"],
                                ascending=[True, True, False])

                best = g.iloc[0].to_dict()
                global_best_edge = {
                    "window_half_size": int(best["param_window_half_size"]),
                    "mu": float(best["param_mu"]),
                    "l":  int(best["param_l"]),
                    "p":  int(best["param_p"]),
                }
            else:
                print("[global-metrics] ⚠ no sweep rows gathered — using default edge params")
                global_best_edge = {"window_half_size": 45, "mu": 0.0, "l": 5, "p": 14}

            with open(os.path.join(summ_dir, "global_best_edge_params.json"), "w") as f:
                json.dump(global_best_edge, f)
            print(f"[global-metrics] ✅ global best edge params = {global_best_edge}")

        finally:
            self.n = orig_n
            self.change_image()

        tA = time.perf_counter() - tA_start
        print(f"[global-metrics] ⏱ calibration phase took {tA:.2f} s")
        
            # --- PHASE B: Apply timer ---
        tB_start = time.perf_counter()

        print("[global-metrics] applying global params to images…")
        apply_idxs = idxs_sample if apply_to_sample else list(range(len(self.image_names)))

        per_image_times = []

        try:
            for t, i in enumerate(apply_idxs, 1):
                # ---------- NEW: ultra-early skips ----------
                # 1) Skip if the per-image annotation JSON doesn't exist
                base_name = os.path.splitext(os.path.basename(self.image_names[i]))[0]
                ann_path  = os.path.join(self.save_folder, f"{base_name}.json")
                if not os.path.exists(ann_path):
                    print(f"[apply] ⚠ Skipping {base_name} — no JSON found.")
                    continue

                # 2) Skip if JSON exists but has no manual midlines with ≥2 points
                if not metrics._json_has_manual_midlines(ann_path):
                    print(f"[apply] ⚠ Skipping {base_name} — JSON has no manual midlines.")
                    continue

                # 3) Skip if already completed earlier
                image_dir = os.path.join(self.save_folder, "metrics", base_name)
                done_flag = os.path.join(image_dir, "DONE.ok")
                if os.path.exists(done_flag):
                    print(f"[apply] ✅ Already complete — {base_name} (found DONE.ok)")
                    continue

                # -------------------------------------------
                t_img_start = time.perf_counter()

                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [apply] {t}/{len(apply_idxs)}: {base_name} ======")
                os.makedirs(image_dir, exist_ok=True)

                # log edge params used
                try:
                    with open(os.path.join(image_dir, "edge_params_used.json"), "w") as f:
                        json.dump(global_best_edge, f)
                except Exception as e:
                    print(f"[apply] could not write edge_params_used.json: {e}")

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    # nothing to do (but still record a stub and move on)
                    with open(os.path.join(image_dir, "status.json"), "w") as f:
                        json.dump({"image": base_name, "processed_cracks": [], "note": "no atomic cracks"}, f)
                    # mark done to avoid re-entering
                    open(done_flag, "a").close()
                    t_img_total = time.perf_counter() - t_img_start
                    per_image_times.append({
                        "image": base_name,
                        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                        "total_image_s": round(t_img_total, 2),
                        "metrics_s": 0.0,
                        "auto_variants_s": 0.0,
                        "mask_build_s": 0.0,
                        "supervision_s": 0.0,
                        "mode": "full" if not edges_only else "edges_only"
                    })
                    continue

                # --- Subphase timers ---
                t_auto = 0.0
                t_edge_parallel = 0.0

                processed_cracks = []  # for status.json

                if edges_only:
                    # ----------------- EDGE-ONLY FAST PATH -----------------
                    t_edge_parallel_start = time.perf_counter()
                    try:
                        _ = self.run_edge_tracking_parallel(
                            crack_ids=list(atomic.keys()),
                            cpu_max_workers=edge_parallel_workers,
                            edge_params_fixed=global_best_edge,
                        )
                        processed_cracks = list(atomic.keys())
                    except Exception as e:
                        print(f"[apply] edge-only parallel run failed: {e}")
                    t_edge_parallel = time.perf_counter() - t_edge_parallel_start

                    # No RS3 / no auto masks build; just compute manual mask/width metrics
                    t_mask = 0.0

                    t_metrics_start = time.perf_counter()
                    try:
                        self.compute_mask_and_width_metrics_for_image(display=False)
                    except Exception as e:
                        print(f"[apply] mask/width stage failed: {e}")
                    t_metrics = time.perf_counter() - t_metrics_start

                    t_sup = 0.0  # supervision export relies on auto artifacts; skip in edge-only

                else:
                    # --------------- FULL RS3 VARIANTS PATH ----------------
                    # Build autos only for cracks with manual midlines (≥2 pts)
                    valid_manual_ids = []
                    for cid, crack in atomic.items():
                        src = (crack.get("source") or "").lower()
                        if src.startswith("auto") or src == "combined":
                            continue
                        man_xy = metrics._finite_xy(crack.get("midline", []))
                        if len(man_xy) >= 2:
                            valid_manual_ids.append(cid)

                    t_auto_start = time.perf_counter()
                    auto_packs_for_image = {}   # NEW: collect packs for this image

                    for cid in valid_manual_ids:
                        try:
                            pack = self.generate_auto_variants_for_manual_parallel(
                                crack_id=cid,
                                g_variants=g_variants,
                                edge_params_fixed=global_best_edge,
                                cpu_max_workers=cpu_max_workers,
                                force_recompute=True,
                            )
                            if pack is not None:
                                auto_packs_for_image[cid] = pack
                            processed_cracks.append(cid)
                        except Exception as e:
                            print(f"[apply] RS3 variants failed for cid={cid}: {e}")

                    t_auto = time.perf_counter() - t_auto_start

                    # ---- NEW: global selection over all subcracks in this image ----
                    self._select_best_rs3_across_subcracks(auto_packs_for_image)


                    # --- Build combined masks ---
                    t_mask_start = time.perf_counter()
                    try:
                        self._build_combined_auto_masks_same_indices(cache_key=metrics._auto_cache_key(self))
                    except Exception as e:
                        print(f"[apply] combined auto-mask build failed: {e}")
                    t_mask = time.perf_counter() - t_mask_start

                    # --- Compute mask/width metrics ---
                    t_metrics_start = time.perf_counter()
                    try:
                        self.compute_mask_and_width_metrics_for_image(display=False)
                    except Exception as e:
                        print(f"[apply] mask/width stage failed: {e}")
                    t_metrics = time.perf_counter() - t_metrics_start

                    # --- Export training supervision ---
                    t_sup_start = time.perf_counter()
                    try:
                        self.export_training_supervision_for_image(cache_key=metrics._auto_cache_key(self))
                    except Exception as e:
                        print(f"[apply] supervision export failed: {e}")
                    t_sup = time.perf_counter() - t_sup_start

                # --- per-image log row ---
                t_img_total = time.perf_counter() - t_img_start
                row = {
                    "image": base_name,
                    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                    "total_image_s": round(t_img_total, 2),
                    "metrics_s": round(t_metrics, 2),
                }

                if edges_only:
                    row.update({
                        "edge_parallel_s": round(t_edge_parallel, 2),
                        "mask_build_s": 0.0,
                        "auto_variants_s": 0.0,
                        "supervision_s": 0.0,
                        "mode": "edges_only"
                    })
                    print(f"[apply] ⏱ total {t_img_total:.2f}s (edge_parallel={t_edge_parallel:.2f}s, "
                          f"metrics={t_metrics:.2f}s)")
                else:
                    row.update({
                        "auto_variants_s": round(t_auto, 2),
                        "mask_build_s": round(t_mask, 2),
                        "supervision_s": round(t_sup, 2),
                        "mode": "full"
                    })
                    print(f"[apply] ⏱ total {t_img_total:.2f}s (auto={t_auto:.2f}s, mask={t_mask:.2f}s, "
                          f"metrics={t_metrics:.2f}s, sup={t_sup:.2f}s)")

                per_image_times.append(row)

                # --- NEW: persist simple per-image status + DONE marker for resumability ---
                try:
                    with open(os.path.join(image_dir, "status.json"), "w") as f:
                        json.dump({
                            "image": base_name,
                            "processed_cracks": processed_cracks,
                            "mode": ("edges_only" if edges_only else "full"),
                            "edge_params_used": global_best_edge
                        }, f)
                    # touch a DONE flag so future runs auto-skip this image
                    open(done_flag, "a").close()
                except Exception as e:
                    print(f"[apply] could not write status/DONE for {base_name}: {e}")

            # --- summary per-image CSV ---
            if per_image_times:
                df_times = pd.DataFrame(per_image_times)
                df_times.to_csv(os.path.join(summ_dir, "global_per_image_runtime.csv"), index=False)
                print(f"[global-metrics] 🕒 per-image runtimes logged ({len(per_image_times)} images)")

            self.summarize_dataset_metrics()
            print("[global-metrics] ✅ finished")

            # --- aggregate all runtime logs from single-image runs ---
            all_logs = []
            for img in self.image_names:
                base = os.path.splitext(os.path.basename(img))[0]
                log_path = os.path.join(self.save_folder, "metrics", base, "runtime_log.csv")
                if os.path.exists(log_path):
                    df = pd.read_csv(log_path)
                    df["image"] = base
                    all_logs.append(df)
            if all_logs:
                df_all = pd.concat(all_logs, ignore_index=True)
                df_all.to_csv(os.path.join(summ_dir, "global_runtime.csv"), index=False)
                print(f"[global-metrics] 🕒 global_runtime.csv written ({len(all_logs)} images)")

        finally:
            self.n = orig_n
            self.change_image()

        tB = time.perf_counter() - tB_start
        t_total = tA + tB
        # --- final global runtime summary ---
        with open(os.path.join(summ_dir, "global_runtime_summary.txt"), "w") as f:
            f.write(f"Phase A (calibration): {tA:.2f} s\n")
            f.write(f"Phase B (application): {tB:.2f} s\n")
            f.write(f"Total runtime: {t_total:.2f} s\n")
            f.write(f"Mode: {'edges_only' if edges_only else 'full'}\n")
            f.write(f"Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")

        print(f"[global-metrics] ⏱ total runtime = {t_total:.2f}s (A={tA:.2f}s, B={tB:.2f}s)")'''

    def batch_run_metrics_global(
        self,
        sample_frac=0.20,
        max_images=10,
        seed=0,
        edge_grid=None,
        g_variants=None,
        cpu_max_workers=8,
        apply_to_sample=False,
        edges_only=False,
        edge_parallel_workers=None,
    ):
        """
        GLOBAL METRICS DRIVER

        PHASE A1: Edge sweep → global_best_edge
        PHASE A2: (optional) RS3 midline calibration → global_best_rs3
        PHASE B: Apply to all images

        NEW BEHAVIOR:
        • No per-image RS3 fallback.
        • If global RS3 fails → RS3 completely disabled for batch.
        • Pipeline continues safely using only edge tracking + manual midlines.
        """
        import os, json, random, time
        import numpy as np, pandas as pd
        from helpers import metrics
        from helpers.variant_optimizer import (
            optimize_across_dataset,
            apply_family_to_image,
        )
        
        print("test")

        # ------------------------------------------------------------------
        # Helper functions
        # ------------------------------------------------------------------
        if not getattr(self, "image_names", []):
            print("[global-metrics] no images loaded")
            return

        def _ann_path(idx):
            img_path = self.image_names[idx]
            base = os.path.splitext(os.path.basename(img_path))[0]
            return os.path.join(self.save_folder, f"{base}.json")

        def _has_manual_midlines(idx):
            path = _ann_path(idx)
            if not os.path.exists(path):
                return False
            if metrics._json_has_manual_midlines(path):
                return True
            # Fallback: full load
            orig = getattr(self, "n", 0)
            try:
                self.n = idx
                self.change_image()
                ann = (self.annotation or {}).get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                for cr in atomic.values():
                    src = (cr.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    mid = cr.get("midline", [])
                    if isinstance(mid, list) and len(mid) >= 2:
                        return True
                return False
            except Exception:
                return False
            finally:
                try:
                    self.n = orig
                    self.change_image()
                except Exception:
                    pass

        # ------------------------------------------------------------------
        # Build calibration set
        # ------------------------------------------------------------------
        rng = random.Random(seed)
        idxs_all = list(range(len(self.image_names)))
        eligible = [i for i in idxs_all if _has_manual_midlines(i)]

        if not eligible:
            print("[global-metrics] ❌ No images with manual midlines. Aborting.")
            if idxs_all:
                self.n = 0
                self.change_image()
            return

        rng.shuffle(eligible)
        k = max(1, int(len(eligible) * sample_frac))
        idxs_sample = eligible[:min(k, max_images)]
        print(f"[global-metrics] calibration on {len(idxs_sample)} images")

        if edge_grid is None:
            edge_grid = {
                "window_half_size": [35, 45, 55],
                "mu": [0, 5],
                "l": [2, 5],
                "p": [6, 14],
            }

        orig_n = self.n
        summ_dir = os.path.join(self.save_folder, "metrics", "_summary")
        os.makedirs(summ_dir, exist_ok=True)


        # ============================================================
        # PHASE A1: EDGE SWEEP → IMAGE-LEVEL BEST FAMILY (RS3-STYLE)
        # ============================================================
        tA1_start = time.perf_counter()

        edge_families = []   # one record per image

        try:
            for t, idx in enumerate(idxs_sample, 1):
                self.n = idx
                self.change_image()

                base = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [calibrate-edges] {t}/{len(idxs_sample)}: {base} ======")

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}

                edge_packs = {}

                for cid, cr in atomic.items():
                    src = (cr.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue

                    man = metrics._finite_xy(cr.get("midline", []))
                    if len(man) < 2:
                        continue

                    df = self.sweep_edges_with_executor(
                        cid,
                        grid=edge_grid,
                        max_workers=cpu_max_workers
                    )

                    if df is not None and not df.empty:
                        edge_packs[cid] = df

                if not edge_packs:
                    print("[global-metrics] ⚠ no usable edge sweeps for this image")
                    continue

                best_edge = None
                try:
                    best_edge = self.select_best_edge_family_across_subcracks(edge_packs)
                except Exception as e:
                    print(f"[global-metrics] ⚠ family selection failed: {e}")

                if best_edge is None:
                    print("[global-metrics] ⚠ falling back to defaults for image")
                    best_edge = {
                        "window_half_size": 45,
                        "mu": 0.0,
                        "l": 5,
                        "p": 14,
                        "seg_mode": "new",
                    }

                # record image-level result
                edge_families.append({
                    "image": base,
                    **best_edge,
                })

                # write per-image JSON (mirrors rs3_global_best_family.json)
                try:
                    out_json = os.path.join(
                        summ_dir,
                        f"{base}_edge_global_best_family.json"
                    )
                    with open(out_json, "w", encoding="utf-8") as f:
                        json.dump(edge_families[-1], f, indent=2)
                except Exception as e:
                    print(f"[global-metrics] ⚠ could not write edge family JSON: {e}")

        finally:
            self.n = orig_n
            self.change_image()

        tA1 = time.perf_counter() - tA1_start
        print(f"[global-metrics] ⏱ edge calibration total: {tA1:.2f}s")

        # ============================================================
        # PHASE A2: RS3 MIDLINE CALIBRATION (OPTIONAL)
        # ============================================================
        global_best_rs3 = None
        tA2 = 0.0

        if not edges_only:
            tA2_start = time.perf_counter()
            packs_by_image = {}

            try:
                for t, idx in enumerate(idxs_sample, 1):
                    self.n = idx
                    self.change_image()
                    base = os.path.splitext(os.path.basename(self.name))[0]
                    print(f"\n====== [calibrate-RS3] {t}/{len(idxs_sample)}: {base} ======")

                    ann = self.annotation.get("annotations", {}) or {}
                    atomic = ann.get("atomic_cracks", {}) or {}

                    packs_for_img = {}
                    for cid, cr in atomic.items():
                        src = (cr.get("source") or "").lower()
                        if src.startswith("auto") or src == "combined":
                            continue
                        man = metrics._finite_xy(cr.get("midline", []))
                        if len(man) < 2:
                            continue

                        pack = self.generate_auto_variants_for_manual_parallel(
                            crack_id=cid,
                            g_variants=g_variants,
                            edge_params_fixed=global_best_edge,
                            cpu_max_workers=cpu_max_workers,
                            force_recompute=True,
                        )
                        if pack:
                            packs_for_img[cid] = pack

                    if packs_for_img:
                        packs_by_image[base] = packs_for_img

                if packs_by_image:
                    global_best_rs3 = optimize_across_dataset(
                        packs_by_image,
                        save_global_json=os.path.join(summ_dir, "global_best_rs3_family.json")
                    )
                    if global_best_rs3:
                        print(f"[global-metrics] ✅ global RS3 family: {global_best_rs3}")
                    else:
                        print("[global-metrics] ⚠ RS3 calibration failed — RS3 disabled.")
                else:
                    print("[global-metrics] ⚠ No RS3 packs — RS3 disabled.")

            finally:
                self.n = orig_n
                self.change_image()

            tA2 = time.perf_counter() - tA2_start
            print(f"[global-metrics] ⏱ RS3 calibration: {tA2:.2f}s")

        # RS3 availability flag
        rs3_enabled = (global_best_rs3 is not None) and (not edges_only)

        # ============================================================
        # PHASE B: APPLY
        # ============================================================
        print("[global-metrics] applying global parameters...")
        apply_idxs = idxs_sample if apply_to_sample else idxs_all

        tB_start = time.perf_counter()
        per_image_times = []

        try:
            for t, idx in enumerate(apply_idxs, 1):

                base = os.path.splitext(os.path.basename(self.image_names[idx]))[0]
                ann_path = _ann_path(idx)

                # ---- Skip invalid images ----
                if not os.path.exists(ann_path):
                    print(f"[apply] ⚠ Skipping {base} — no JSON.")
                    continue
                if not metrics._json_has_manual_midlines(ann_path):
                    print(f"[apply] ⚠ Skipping {base} — no manual midlines.")
                    continue

                img_dir = os.path.join(self.save_folder, "metrics", base)
                done_flag = os.path.join(img_dir, "DONE.ok")

                # ---- Skip already processed ----
                if os.path.exists(done_flag):
                    print(f"[apply] ✓ already done: {base}")
                    continue

                # Load image
                self.n = idx
                self.change_image()
                os.makedirs(img_dir, exist_ok=True)

                print(f"\n====== [apply] {t}/{len(apply_idxs)}: {base} ======")

                # Save edge params for reference
                with open(os.path.join(img_dir, "edge_params_used.json"), "w") as f:
                    json.dump(global_best_edge, f)

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    print(f"[apply] no cracks in {base}")
                    open(done_flag, "a").close()
                    continue

                # ---- Timers ----
                t_img_start = time.perf_counter()
                t_auto = 0.0
                t_metrics = 0.0
                t_edge_parallel = 0.0

                processed = []

                # ====================================================
                # MODE 1 — EDGE-ONLY
                # ====================================================
                if edges_only:
                    t_edge_parallel_start = time.perf_counter()
                    try:
                        _ = self.run_edge_tracking_parallel(
                            crack_ids=list(atomic.keys()),
                            cpu_max_workers=edge_parallel_workers,
                            edge_params_fixed=global_best_edge,
                        )
                        processed = list(atomic.keys())
                    except Exception as e:
                        print(f"[apply] edge-only parallel failed: {e}")
                    t_edge_parallel = time.perf_counter() - t_edge_parallel_start

                    # Mask + width metrics (manual → GT only)
                    t_metrics_start = time.perf_counter()
                    try:
                        # no RS3 in edges_only, so auto_best won't exist → manual only
                        self.compute_mask_and_width_metrics_for_image(
                            display=False,
                            export_supervision=True,
                            include_auto=False,
                        )
                    except Exception as e:
                        print(f"[apply] mask/width failed: {e}")
                    t_metrics = time.perf_counter() - t_metrics_start

                # ====================================================
                # MODE 2 — FULL RS3 (requires global_best_rs3)
                # ====================================================
                else:
                    rs3_available = (global_best_rs3 is not None)

                    # ---- Collect only manual cracks with midlines ----
                    valid_ids = []
                    for cid, cr in atomic.items():
                        src = (cr.get("source") or "").lower()
                        if src.startswith("auto") or src == "combined":
                            continue
                        mid = metrics._finite_xy(cr.get("midline", []))
                        if len(mid) >= 2:
                            valid_ids.append(cid)

                    auto_packs = {}

                    # ====================================================
                    # RUN RS3 AUTO VARIANTS (ONLY IF DATASET-LEVEL FAMILY EXISTS)
                    # ====================================================
                    if rs3_available and valid_ids:
                        t_auto_start = time.perf_counter()
                        for cid in valid_ids:
                            try:
                                pack = self.generate_auto_variants_for_manual_parallel(
                                    crack_id=cid,
                                    g_variants=g_variants,
                                    edge_params_fixed=global_best_edge,
                                    cpu_max_workers=cpu_max_workers,
                                    force_recompute=True,
                                )
                                if pack:
                                    auto_packs[cid] = pack
                                processed.append(cid)
                            except Exception as e:
                                print(f"[apply] RS3 variant fail cid={cid}: {e}")
                        t_auto = time.perf_counter() - t_auto_start

                        # ---- Apply global RS3 family to all packs of this image ----
                        try:
                            if auto_packs:
                                apply_family_to_image(
                                    global_best_rs3,
                                    auto_packs,
                                    base_name=base,
                                    save_folder=self.save_folder,
                                )
                        except Exception as e:
                            print(f"[apply] RS3 family apply fail on {base}: {e}")
                            rs3_available = False
                            auto_packs = {}

                    else:
                        print(f"[apply] ⚠ No global RS3 family — skipping auto midlines for {base}")
                        auto_packs = {}

                    # ---- Final mask + width metrics ----
                    # Here we WANT manual vs auto (TOTAL/TOTAL_AUTO, combined vs combined_auto, etc.)
                    t_metrics_start = time.perf_counter()
                    try:
                        self.compute_mask_and_width_metrics_for_image(
                            display=False,
                            export_supervision=True,
                            include_auto=True,
                        )
                    except Exception as e:
                        print(f"[apply] mask/width failed: {e}")
                    t_metrics = time.perf_counter() - t_metrics_start

                # ----------------------------------------------------
                # LOGGING + DONE FLAG
                # ----------------------------------------------------
                t_img = time.perf_counter() - t_img_start

                row = {
                    "image": base,
                    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
                    "total_image_s": round(t_img, 2),
                    "metrics_s": round(t_metrics, 2),
                    "auto_variants_s": round(t_auto, 2),
                    "mask_build_s": 0.0,   # merged inside compute_mask_and_width_metrics_for_image
                    "supervision_s": 0.0,  # done inside metrics function
                    "edge_parallel_s": round(t_edge_parallel, 2),
                    "mode": ("edges_only" if edges_only else "full"),
                }
                per_image_times.append(row)

                try:
                    with open(os.path.join(img_dir, "status.json"), "w") as f:
                        json.dump({
                            "image": base,
                            "processed_cracks": processed,
                            "mode": ("edges_only" if edges_only else "full"),
                            "edge_params_used": global_best_edge,
                            "rs3_available": (not edges_only and rs3_available),
                        }, f)
                    open(done_flag, "a").close()
                except Exception as e:
                    print(f"[apply] could not write DONE: {e}")

            # ---- Write per-image runtime table ----
            if per_image_times:
                df_times = pd.DataFrame(per_image_times)
                df_times.to_csv(os.path.join(summ_dir, "global_per_image_runtime.csv"), index=False)

            # Final dataset-level summarization
            self.summarize_dataset_metrics()

            # ---- Aggregate per-image runtime logs ----
            logs = []
            for img in self.image_names:
                base = os.path.splitext(os.path.basename(img))[0]
                path = os.path.join(self.save_folder, "metrics", base, "runtime_log.csv")
                if os.path.exists(path):
                    df = pd.read_csv(path)
                    df["image"] = base
                    logs.append(df)
            if logs:
                DF = pd.concat(logs, ignore_index=True)
                DF.to_csv(os.path.join(summ_dir, "global_runtime.csv"), index=False)

        finally:
            self.n = orig_n
            self.change_image()

        # Final timing summary
        tB = time.perf_counter() - tB_start
        total = tA1 + tA2 + tB
        with open(os.path.join(summ_dir, "global_runtime_summary.txt"), "w") as f:
            f.write(f"Phase A1 (edge calibration): {tA1:.2f} s\n")
            f.write(f"Phase A2 (RS3 calibration): {tA2:.2f} s\n")
            f.write(f"Phase B (application): {tB:.2f} s\n")
            f.write(f"Total runtime: {total:.2f} s\n")
            f.write(f"Mode: {'edges_only' if edges_only else 'full'}\n")
            f.write(f"Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")

        print(f"[global-metrics] ⏱ total runtime = {total:.2f}s (A1={tA1:.2f}, A2={tA2:.2f}, B={tB:.2f})")
        
    # ===============================================================
    # === Compute mask & width metrics (light / full aware) ===
    # ===============================================================
     
    ####NEW CODE:
    def export_gt_supervision_for_current_image(self):
        """
        One-click GT export:
        - Loads main annotation x.json (no snapshots)
        - Takes ONLY manual atomics
        - Groups atomics using pure GT logic (gt_groups_from_midlines_and_gtmask)
        - Calls export_gt_supervision_for_image(...) with GT mask
        """

        import os, json
        import numpy as np
        import cv2

        from helpers.supervision import (
            export_gt_supervision_for_image as _export_gt_sup,
        )
        from combiner import gt_groups_from_midlines_and_gtmask

        base_name = self._image_base()

        if getattr(self, "original_image", None) is None:
            print("[GT_SUP] no image loaded.")
            return

        if getattr(self, "current_mask", None) is None:
            print("[GT_SUP] no GT mask loaded.")
            return

        H, W = self.original_image.shape[:2]
        gt_mask = (self.current_mask > 0).astype(np.uint8)

        # -------------------------------
        # Load the main annotation JSON
        # -------------------------------
        ann_path = getattr(self, "ann_name", None)
        if not ann_path or not os.path.exists(ann_path):
            print(f"[GT_SUP] no annotation JSON for {base_name}")
            return

        with open(ann_path, "r", encoding="utf-8") as f:
            ann_json = json.load(f)

        authoring_atomic = (
            ann_json.get("annotations", {}) or {}
        ).get("atomic_cracks", {}) or {}

        # -----------------------------------------
        # Filter manual atomics ONLY (no snapshots)
        # -----------------------------------------
        def _is_manual(cr):
            src = (cr.get("source") or "").lower()
            return src in ("manual", "manual_poly", "manual_midline")

        atomic = {
            str(cid): cr
            for cid, cr in authoring_atomic.items()
            if _is_manual(cr)
        }

        print(f"[GT_SUP] using {len(atomic)} manual atomics for {base_name}")

        if not atomic:
            print("[GT_SUP] no manual atomics, aborting.")
            return

        # -----------------------------------------
        # GT grouping (midlines + GT mask + endpoints)
        # -----------------------------------------
        combined_groups = gt_groups_from_midlines_and_gtmask(
            atomic=atomic,
            gt_mask=gt_mask,
            H=H,
            W=W,
        )

        print(f"[GT_SUP] GT grouping produced {len(combined_groups)} combined groups.")

        # -----------------------------------------
        # Export manual GT supervision (atomic+combined)
        # -----------------------------------------
        _export_gt_sup(
            base_name=base_name,
            save_root=self.save_folder,
            original_image=self.original_image,
            H=H,
            W=W,
            atomic=atomic,
            combined_groups=combined_groups,
            gt_mask=gt_mask,
        )

        print(f"[GT_SUP] Finished GT supervision export for {base_name}")
     
    def run_manual_metrics_current_image_quick(self, tau_px=3.0, crack_id=None, display=True, do_param_sweep=True):
        """
        Minimal smoke test for manual cracks.
        Uses helpers.metrics for all real computations.
        Just fixes:
        - combined refresh
        - per-CID overlay path (no top-level clutter)
        - midline drawn on gt_normals
        - total/global summary + midline metrics call
        """
        import os, time, numpy as np, traceback, cv2
        from helpers.metrics import reconstruct_manual_mask_from_edges

        if not getattr(self, "name", None):
            print("[metrics] ⚠ no image loaded — aborting smoke test.")
            return

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        image_dir = os.path.join(self.save_folder, "metrics", base_name)
        os.makedirs(image_dir, exist_ok=True)
        print(f"\n[SMOKE] ===== running minimal metrics for {base_name} =====")
        t_total_start = time.perf_counter()

        # --- 1) refresh combined snapshot ---
        try:
            self._purge_metrics_for_current_image()
            self._sync_metrics_snapshot_from_authoring(refresh_combine=True, persist=False)
        except Exception as e:
            traceback.print_exc()
            print(f"[SMOKE] snapshot sync failed: {e}")
            return

        # 🔍 ADD THIS ↓↓↓
        print("[DEBUG SNAPSHOT] after sync:")
        try:
            ann_json_path = os.path.join(self.save_folder, f"{base_name}.json")
            print(f"[DEBUG SNAPSHOT] expected annotation path: {ann_json_path}")
            if os.path.exists(ann_json_path):
                with open(ann_json_path, "r") as f:
                    ann_json = json.load(f)
                print(f"[DEBUG SNAPSHOT] top-level keys: {list(ann_json.keys())}")
                anns = ann_json.get("annotations", {})
                print(f"[DEBUG SNAPSHOT] annotations keys: {list(anns.keys())}")
                print(f"[DEBUG SNAPSHOT] combined_cracks len = {len(anns.get('combined_cracks', {}))}")
                print(f"[DEBUG SNAPSHOT] combined len = {len(anns.get('combined', {}))}")
            else:
                print("[DEBUG SNAPSHOT] ❌ no annotation JSON found at path")
        except Exception as e:
            print(f"[DEBUG SNAPSHOT] failed to read JSON: {e}")

        atomic = self._metric_atomic()
        if not atomic:
            print("[SMOKE] ❌ no cracks found in snapshot")
            return

        best_edge = {"window_half_size":45, "mu":0.0, "l":5, "p":14}

        # --- 2) run edge workers where needed ---
        need_ids = []
        for cid, cr in atomic.items():
            src = (cr.get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue
            mid = np.asarray(cr.get("midline", []), float)
            if mid.ndim != 2 or mid.shape[1] != 2 or len(mid) < 2:
                continue
            #ge = cr.get("geodesic_edges", {}) or {}
            #has_e1 = isinstance(ge.get("edge1"), list) and len(ge.get("edge1")) > 1
            #has_e2 = isinstance(ge.get("edge2"), list) and len(ge.get("edge2")) > 1
            #if not (has_e1 and has_e2):
            #    need_ids.append(cid)
            need_ids.append(cid)

        print(f"[SMOKE] manual cracks needing edges: {need_ids}")
        for cid in need_ids:
            try:
                self.smoke_test_edges_for_manual(cid, edge_params=best_edge)
            except Exception as e:
                traceback.print_exc()
                print(f"[SMOKE] ❌ edge smoke failed for cid={cid}: {e}")

        # --- 3) use existing metric pipeline ---
        try:
            print("[SMOKE] running mask/width metrics ...")
            self.compute_mask_and_width_metrics_for_image(display=display, export_supervision=True)
        except Exception as e:
            traceback.print_exc()
            print(f"[SMOKE] mask/width stage failed: {e}")

        # --- 4) move per-CID overlay into its folder + redraw midline on gt_normals ---
        '''try:
            H, W = self.original_image.shape[:2]
            gt_full = (self.current_mask > 0).astype(np.uint8) if getattr(self, "current_mask", None) is not None else np.zeros((H, W), np.uint8)
            ann = self._metric_atomic()

            from helpers.plot_metrics import save_gt_vs_manual_overlay

            for cid, crack in ann.items():
                src = (crack.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue

                # ---------------------------------------------------------
                # 1. Get full predicted mask for this atomic crack
                # ---------------------------------------------------------
                pred_mask_full = reconstruct_manual_mask_from_edges(crack, H, W)
                if pred_mask_full is None:
                    continue
                pred_mask_full = (pred_mask_full > 0).astype(np.uint8)

                # ---------------------------------------------------------
                # 2. Compute the true atomic bbox (same logic as combined)
                # ---------------------------------------------------------
                ys, xs = np.where(pred_mask_full > 0)
                if xs.size == 0:
                    continue

                x0 = max(xs.min() - 5, 0)
                y0 = max(ys.min() - 5, 0)
                x1 = min(xs.max() + 5, W)
                y1 = min(ys.max() + 5, H)

                bbox = [x0, y0, x1 - x0, y1 - y0]

                # ---------------------------------------------------------
                # 3. Save into cidXX directory
                # ---------------------------------------------------------
                cid_dir = os.path.join(image_dir, f"cid{cid}")
                os.makedirs(cid_dir, exist_ok=True)

                # ---------------------------------------------------------
                # 4. Unified overlay helper (identical to combined)
                # ---------------------------------------------------------
                save_gt_vs_manual_overlay(
                    H,
                    W,
                    gt_full,             # full GT mask
                    pred_mask_full,      # full predicted mask
                    os.path.join(cid_dir, "gt_vs_manual_mask_global.png"),
                    bbox=bbox,           # <<< SAME BEHAVIOR AS COMBINED
                    original_image=self.original_image,
                )

                # add midline to gt_normals if it exists
                normals_path = os.path.join(cid_dir, "gt_normals.png")
                if os.path.exists(normals_path):
                    ml = np.asarray(crack.get("midline", []), float)
                    if ml.ndim == 2 and len(ml) > 1:
                        img = cv2.imread(normals_path)
                        cv2.polylines(img, [ml.astype(np.int32)], False, (0,0,255), 1, cv2.LINE_AA)
                        cv2.imwrite(normals_path, img)

                print(f"[SMOKE] wrote mask overlay → {cid_dir}")
        except Exception as e:
            print(f"[SMOKE] overlay debug failed: {e}")

        # --- 5) run existing midline metric CSV (in helpers.metrics) ---
        #try:
        #    compute_midline_metrics_for_image(self)
        #except Exception as e:
        #    print(f"[SMOKE] midline metrics failed: {e}")

        self.dump_global_midline_and_mask_overlays(thickness_px=3)
        total_time = time.perf_counter() - t_total_start
        print(f"[SMOKE] ✅ completed minimal metrics in {total_time:.2f}s\n")'''
         
    # ---- 8) Quick metrics driver (unified; snapshot-only) ----------------------
    def run_full_metrics_current_image(
        self,
        edge_grid=None,
        g_variants=None,
        cpu_max_workers=8,
        do_edge_calibrate=False
    ):
        """
        Fast single-image execution of:
            - snapshot sync from AUTHORING
            - (optional) edge param sweep
            - edge tracking for MANUAL midlines (edge_param_worker + debug)
            - RS3 auto-variants per manual subcrack
            - global RS3 family selection
            - edge tracking for AUTO best (if present)
            - full mask/width metrics + supervision

        Uses the same snapshot structure as batch_run, but without global calibration.
        """
        
        #stopgap measure
        do_edge_calibrate=False

        import os, time, numpy as np, pandas as pd
        from helpers import metrics
        from helpers.save_load_files import load_snapshot_from_files

        if getattr(self, "original_image", None) is None:
            print("[quick] ❌ no image loaded")
            return {}

        base_name = self._image_base()
        print(f"\n[quick] metrics for current image: {base_name}")

        # ------------------------------------------------------------
        # SAFETY CHECK — must have ≥2-pt manual midlines in AUTHORING
        # ------------------------------------------------------------
        ann = (getattr(self, "annotation", {}) or {}).get("annotations", {}) or {}
        atomic_authoring = ann.get("atomic_cracks", {}) or {}

        def _has_valid_manual_midlines(atomic_dict):
            for crack in atomic_dict.values():
                src = (crack.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue
                mid = crack.get("midline", [])
                if isinstance(mid, list) and len(mid) >= 2:
                    return True
            return False

        if not atomic_authoring or not _has_valid_manual_midlines(atomic_authoring):
            print(f"[DEBUG QUICK] 🧹 No valid manual midlines — purging snapshot for {base_name}")

            metrics_dir = os.path.join(self.save_folder, "metrics")
            snap_path = os.path.join(metrics_dir, f"{base_name}.json")
            if os.path.exists(snap_path):
                try:
                    os.remove(snap_path)
                    print(f"[DEBUG QUICK] Removed stale snapshot: {snap_path}")
                except Exception as e:
                    print(f"[DEBUG QUICK] ⚠ failed removing {snap_path}: {e}")

            if hasattr(self, "metric_annotations"):
                self.metric_annotations.clear()
                print("[DEBUG QUICK] Cleared in-memory metric_annotations")

            return {}

        # ------------------------------------------------------------
        # SNAPSHOT SYNC (CRITICAL for per-cid files + _metric_atomic)
        # ------------------------------------------------------------
        try:
            self._purge_metrics_for_current_image()
            # Builds metrics/<base>/cid*/cid*.json and sets self.metric_annotations
            self._sync_metrics_snapshot_from_authoring(
                refresh_combine=True,
                persist=True
            )
        except Exception as e:
            print(f"[quick] ⚠ snapshot sync failed: {e}")

        # ------------------------------------------------------------
        # SETUP
        # ------------------------------------------------------------
        image_dir = self._metrics_dir()
        os.makedirs(image_dir, exist_ok=True)
        t_total_start = time.perf_counter()

        # ------------------------------------------------------------
        # (OPTIONAL) EDGE PARAM CALIBRATION
        # ------------------------------------------------------------
        if edge_grid is None:
            edge_grid = {
                "window_half_size": [45],
                "mu": [0],
                "l": [5],
                "p": [14],
                "seg_mode": ["new"],
            }

        # default params (always valid)
        best_edge = {"window_half_size": 45, "mu": 0.0, "l": 5, "p": 14, "seg_mode": "new"}

        t_edge_calib_start = time.perf_counter()

        # ------------------------------------------------------------
        # EDGE PARAM CALIBRATION (NO RECOMPUTE)
        # ------------------------------------------------------------
        if do_edge_calibrate:
            print("[quick] edge calibration sweep...")

            edge_packs = {}

            for cid, cr in self._metric_atomic().items():
                src = (cr.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue

                mid = np.asarray(cr.get("midline", []), float)
                if mid.ndim != 2 or len(mid) < 2:
                    continue

                df = self.sweep_edges_with_executor(
                    cid,
                    grid=edge_grid,
                    max_workers=cpu_max_workers,
                )

                if df is not None and not df.empty:
                    d = df.copy()
                    d["crack_id"] = cid
                    edge_packs[cid] = d

            sel = self.select_best_edge_family_across_subcracks(edge_packs)

            # --------------------------------------------------------
            # Normalize selector return shape (IMPORTANT)
            #   - old selector: returns {window_half_size, mu, l, p, seg_mode}
            #   - new selector: returns {"params": {...}, "per_crack_geom": {...}}
            # --------------------------------------------------------
            if sel is None:
                print("[quick] ⚠ edge family selection returned None — fallback to defaults")
                sel = {
                    "params": dict(window_half_size=45, mu=0.0, l=5, p=14, seg_mode="new"),
                    "per_crack_geom": {},
                }

            if isinstance(sel, dict) and "params" in sel:
                # NEW SHAPE
                best_edge_bundle = sel
                best_edge = dict(best_edge_bundle.get("params") or best_edge)
            else:
                # OLD SHAPE
                best_edge_bundle = {"params": dict(sel), "per_crack_geom": {}}
                best_edge = dict(sel)

        else:
            # no calibration → no bundle/caches
            best_edge_bundle = {"params": dict(best_edge), "per_crack_geom": {}}

        # ------------------------------------------------------------
        # APPLY EDGES FROM CACHE (ONLY if calibration produced caches)
        # ------------------------------------------------------------
        used_cache = False
        per_crack_geom = (best_edge_bundle or {}).get("per_crack_geom", {}) or {}

        if do_edge_calibrate and per_crack_geom:
            print("[quick] loading cached edges (no recompute)...")
            used_cache = True

            n_applied = 0
            for cid, info in per_crack_geom.items():
                geom_path = (info or {}).get("geom_cache_path", None)
                if not geom_path:
                    continue

                try:
                    data = np.load(geom_path, allow_pickle=True)

                    # Update the live crack dict directly (safest)
                    cr = self._metric_atomic().get(cid, None)
                    if cr is None:
                        continue

                    # Use .tolist() so JSON snapshot writing stays stable
                    # (np arrays inside dicts will bite you later)
                    if "mask_crop" in data:
                        cr["mask_crop"] = data["mask_crop"].tolist() if hasattr(data["mask_crop"], "tolist") else data["mask_crop"]

                    if "track_e1" in data:
                        cr["edge1"] = data["track_e1"].tolist() if hasattr(data["track_e1"], "tolist") else data["track_e1"]

                    if "track_e2" in data:
                        cr["edge2"] = data["track_e2"].tolist() if hasattr(data["track_e2"], "tolist") else data["track_e2"]

                    # normals
                    n1 = data["normals_e1"] if "normals_e1" in data else None
                    n2 = data["normals_e2"] if "normals_e2" in data else None
                    if n1 is not None or n2 is not None:
                        cr["normals"] = {
                            "edge1": n1.tolist() if hasattr(n1, "tolist") else n1,
                            "edge2": n2.tolist() if hasattr(n2, "tolist") else n2,
                        }

                    # record params used
                    cr["edge_params"] = dict(best_edge)
                    cr["edge_source"] = "cached_calibration"

                    n_applied += 1

                except Exception as e:
                    print(f"[quick] ⚠ cache load failed for cid={cid}: {e}")

            print(f"[quick] cached edges applied to {n_applied} cracks")
        else:
            if do_edge_calibrate:
                print("[quick] no cache map present — will recompute edges in Phase 1")

        t_edge_calib = time.perf_counter() - t_edge_calib_start
        print(f"[quick] ⏱ edge calibration total: {t_edge_calib:.2f}s")

        # ------------------------------------------------------------
        # PHASE 1: EDGE TRACKING FOR MANUAL CRACKS
        #   - If cache was applied: SKIP recompute
        #   - Else: run_edge_tracking_parallel (existing behavior)
        # ------------------------------------------------------------
        if used_cache:
            print("[quick] manual edge tracking skipped (cache already applied)")
            t_manual_edges = 0.0
        else:
            print("[quick] running edge tracking for MANUAL cracks (debug plots)...")
            t_manual_edges_start = time.perf_counter()

            manual_ids = []
            for cid, cr in self._metric_atomic().items():
                src = (cr.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue

                mid = np.asarray(cr.get("midline", []), float)
                if mid.ndim != 2 or mid.shape[1] != 2 or len(mid) < 2:
                    continue

                manual_ids.append(cid)

            print(f"[quick] manual cracks to edge-track: {manual_ids}")

            if manual_ids:
                try:
                    _ = self.run_edge_tracking_parallel(
                        crack_ids=manual_ids,
                        cpu_max_workers=cpu_max_workers,
                        edge_params_fixed=best_edge,  # <-- normalized plain params dict
                    )
                except Exception as e:
                    print(f"[quick] ⚠ manual edge tracking failed: {e}")

                # reload snapshot to ensure new edges are visible
                self.metric_annotations = load_snapshot_from_files(self.save_folder, base_name)

            t_manual_edges = time.perf_counter() - t_manual_edges_start
            print(f"[quick] manual-edge generation time = {t_manual_edges:.2f}s")
        
        #return
        # ------------------------------------------------------------
        # PHASE 1.5: RS3 AUTO VARIANTS (this image only)
        # ------------------------------------------------------------
        print("[quick] running RS3 auto variants...")
        t_auto_start = time.perf_counter()
        auto_packs = {}

        for cid, cr in self._metric_atomic().items():
            src = (cr.get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue

            mid = np.asarray(cr.get("midline", []), float)
            if mid.ndim != 2 or mid.shape[1] != 2 or len(mid) < 2:
                continue

            pack = self.generate_auto_variants_for_manual_parallel(
                crack_id=cid,
                g_variants=g_variants,
                edge_params_fixed=best_edge,
                cpu_max_workers=cpu_max_workers,
                force_recompute=True,
                os_ablation=False
            )
            if pack:
                auto_packs[cid] = pack

        t_auto = time.perf_counter() - t_auto_start

        # ------------------------------------------------------------
        # PHASE 1.6: SELECT BEST RS3 FAMILY (IMAGE-LEVEL)
        # ------------------------------------------------------------
        print("[quick] selecting best RS3 family for this image...")
        if auto_packs:
            try:
                self._select_best_rs3_across_subcracks(auto_packs)
            except Exception as e:
                print(f"[quick] ⚠ RS3 family selection failed: {e}")
        else:
            print("[quick] ⚠ no auto_packs; skipping RS3 family selection.")
        #return

        # ------------------------------------------------------------
        # PHASE 2: GEODESIC EDGES FOR AUTO BEST MIDLINES
        # ------------------------------------------------------------
        print("[quick] generating geodesic edges for AUTO best midlines...")
        t_auto_edges_start = time.perf_counter()

        auto_ids = []
        for cid, cr in self._metric_atomic().items():
            # Depending on how _select_best_rs3_across_subcracks writes back,
            # this may be either a separate 'auto_best' source or just nested under manual.
            # Here we look for cracks explicitly marked as auto_best.
            src = (cr.get("source") or "").lower()
            if src == "auto_best":
                auto_ids.append(cid)

        print(f"[quick] auto cracks needing edges: {auto_ids}")

        if auto_ids:
            try:
                _ = self.run_edge_tracking_parallel(
                    crack_ids=auto_ids,
                    cpu_max_workers=cpu_max_workers,
                    edge_params_fixed=best_edge,
                    prefer_auto_best=True
                )
            except Exception as e:
                print(f"[quick] ⚠ auto-edgegen failed: {e}")

            # reload snapshot to include AUTO edges
            self.metric_annotations = load_snapshot_from_files(self.save_folder, base_name)

        t_auto_edges = time.perf_counter() - t_auto_edges_start
        print(f"[quick] auto-edge generation time = {t_auto_edges:.2f}s")
        
        #return

        # ------------------------------------------------------------
        # PHASE 3: MASK + WIDTH METRICS + SUPERVISION
        # ------------------------------------------------------------
        t_metrics_start = time.perf_counter()
        try:
            self.compute_mask_and_width_metrics_for_image(
                display=False,
                export_supervision=True,
                include_auto=True
            )
        except Exception as e:
            print(f"[quick] ❌ compute_mask_and_width_metrics_for_image failed: {e}")
            import traceback
            traceback.print_exc()
        t_metrics = time.perf_counter() - t_metrics_start

        # ------------------------------------------------------------
        # LOGGING
        # ------------------------------------------------------------
        total_time = time.perf_counter() - t_total_start
        log_path = os.path.join(image_dir, "runtime_log.csv")

        row = {
            "image": base_name,
            "edge_calibration_s": round(t_edge_calib, 2),
            "edge_generation_manual_s": round(t_manual_edges, 2),
            "auto_variants_s": round(t_auto, 2),
            "auto_edgegen_s": round(t_auto_edges, 2),
            "mask_width_s": round(t_metrics, 2),
            "total_s": round(total_time, 2),
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        }

        try:
            if os.path.exists(log_path):
                df = pd.read_csv(log_path)
                df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
            else:
                df = pd.DataFrame([row])
            df.to_csv(log_path, index=False)
        except Exception as e:
            print(f"[quick] ⚠ failed to write runtime_log.csv: {e}")

        print(
            f"[quick] ⏱ total = {total_time:.2f}s "
            f"(edge_calib={t_edge_calib:.2f}s, manual-edgegen={t_manual_edges:.2f}s, "
            f"auto={t_auto:.2f}s, auto-edgegen={t_auto_edges:.2f}s, mask_width={t_metrics:.2f}s)"
        )

        return {"image": base_name, "best_edge": best_edge}
    
    
    
    
if __name__ == "__main__":
    import sys
    from time import time
    app = QtWidgets.QApplication(sys.argv)
    font = QtGui.QFont()
    font.setPointSize(7)
    app.setFont(font)
    MainWindow = QtWidgets.QMainWindow()
    ui = CrackToolsApplication()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
