# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cracktools as ct
from helpers.layout import Ui_MainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import Qt
import skimage
import numpy as np
import cv2
import matplotlib.pyplot as plt
import json
import os
from skimage.segmentation import mark_boundaries
import os
from PyQt5.QtWidgets import QListWidgetItem

from crackutils import *
from helpers.crackhelpers import *

from helpers.endpoint_annotator import CrackAnnotator
min_crop_size = 16   
class CrackToolsApplication(CrackUtils, Ui_MainWindow):
    def setupUi(self, MainWindow):
        super().setupUi(MainWindow)
        self.MainWindow = MainWindow
        self.SelectFolderButton.clicked.connect(self.select_folder)
        self.PreviousImageButton.clicked.connect(self.previous_image)
        self.NextImageButton.clicked.connect(self.next_image)
        self.draw_box_button.clicked.connect(self.draw_box)
        self.save_b_button.clicked.connect(self.save_box)
        self.clear_boxes_button.clicked.connect(self.clear_boxes)
        self.clear_segmentation_button.clicked.connect(self.clear_segmentation)
        self.clear_combined_cracks_button.clicked.connect(self.clear_combined_cracks)
        self.files_list.itemSelectionChanged.connect(self.name_selected)

        self.select_points_button.clicked.connect(self.select_save_end_points)
        self.update_image_crop_button.clicked.connect(self.update_image_crop)
        self.wavelet_button.clicked.connect(self.check_wavelet)
        self.middle_point_button.clicked.connect(self.select_middle_point)
        self.middpoint_update_button.clicked.connect(self.update_midpoint_image)
        self.BatchPipelineButton.clicked.connect(self.batch_run_pipeline)

        # Replace the following individual step connections
        self.update_os_button.clicked.connect(self.update_os)
        self.update_cost_button.clicked.connect(self.update_os_cost)
        self.midline_track_button.clicked.connect(self.midline_tracking)
        self.edge_mask_button.clicked.connect(self.edge_mask)
        self.edge_tracks_button.clicked.connect(self.edge_tracking)
        # self.save_current_segment_button.clicked.connect(self.save_current_segment)

        # Hide step-by-step buttons not needed anymore
        #self.show_os_button.hide()
        #self.update_cost_button.hide()
        #self.midline_track_button.hide()
        #self.edge_mask_button.hide()
        #self.edge_tracks_button.hide()
        self.save_current_segment_button.hide()

        # Repurpose the OS button for full pipeline
        try:
            self.update_os_button.clicked.disconnect()
        except Exception:
            pass
        self.update_os_button.setText("Run Pipeline")
        self.update_os_button.clicked.connect(self.run_pipeline)

        self.update_track_display_button.clicked.connect(self.update_track_display)
        self.track_full_screen_button.clicked.connect(self.track_full_screen)
        self.edge_tracks_full_screen_button.clicked.connect(self.edge_tracks_full_screen)
        self.draw_segment_button.clicked.connect(self.draw_segment)
        self.save_manuall_segment_button.clicked.connect(self.save_manual_segment)
        self.manual_segment_full_screen_button.clicked.connect(self.manual_segment_full_screen)
        self.combine_segments_button.clicked.connect(self.combine_segments)

        self.n = -1
        self.saved = False

        self.update_image_crop_button.setStyleSheet("background-color : red")
        self.middle_point_button.setStyleSheet("background-color : red")
        self.middpoint_update_button.setStyleSheet("background-color : red")
        self.update_os_button.setStyleSheet("background-color : red")
        self.update_cost_button.setStyleSheet("background-color : red")
        self.midline_track_button.setStyleSheet("background-color : red")
        self.update_track_display_button.setStyleSheet("background-color : red")
        self.track_full_screen_button.setStyleSheet("background-color : red")
        self.edge_mask_button.setStyleSheet("background-color : red")
        self.edge_tracks_button.setStyleSheet("background-color : red")
        self.edge_tracks_full_screen_button.setStyleSheet("background-color : red")
        self.save_current_segment_button.setStyleSheet("background-color : red")
        self.draw_segment_button.setStyleSheet("background-color : red")
        self.show_os_button.setStyleSheet("background-color : red")
        #self.mask_pipeline_button.setStyleSheet("background-color : red")
    
    def select_end_points_manmidlines(self):
        if not hasattr(self, "original_image") or self.original_image is None:
            error("No original image found.")
            return

        from PyQt5.QtWidgets import (
            QDialog, QVBoxLayout, QHBoxLayout, QPushButton,
            QSizePolicy, QApplication, QMessageBox, QScrollArea, QLabel
        )

        boxes = self.get_all_bounding_boxes()

        # --- Separate "read-only" midlines & connections from editable ones ---
        readonly_midlines = {}
        readonly_connections = []
        existing_midlines = {}

        if "annotations" in self.annotation:
            ann = self.annotation["annotations"]

            # Existing manual midlines (global coords) → store for bbox conversion
            ann_midlines = ann.get("midlines", {})
            for k_str, pts in ann_midlines.items():
                try:
                    i1, i2 = map(int, k_str.split("_"))
                    existing_midlines[(min(i1, i2), max(i1, i2))] = [tuple(map(float, xy)) for xy in pts]
                except:
                    pass

            # Existing auto connections (from atomic cracks) — global coords
            for crack in ann.get("atomic_cracks", {}).values():
                if crack.get("source") == "auto":
                    ml = crack.get("midline", [])
                    if len(ml) >= 2:
                        p1, p2 = tuple(ml[0]), tuple(ml[-1])
                        readonly_connections.append((p1, p2))

        # --- Ensure all endpoints exist in initial points ---
        initial_points = list(getattr(self, "user_points", []) or [])
        point_index_map = {tuple(pt): idx for idx, pt in enumerate(initial_points)}

        def ensure_point(pt):
            if tuple(pt) not in point_index_map:
                point_index_map[tuple(pt)] = len(initial_points)
                initial_points.append(pt)
            return point_index_map[tuple(pt)]
        
        # --- Fill read-only midlines (keep in full-image coords) ---
        for (i1, i2), poly in existing_midlines.items():
            start_idx = ensure_point(poly[0])
            end_idx = ensure_point(poly[-1])
            readonly_midlines[(start_idx, end_idx)] = poly

        # --- Fill read-only connections (keep in full-image coords) ---
        readonly_conn_idx = []
        for p1, p2 in readonly_connections:
            idx1 = ensure_point(p1)
            idx2 = ensure_point(p2)
            readonly_conn_idx.append((min(idx1, idx2), max(idx1, idx2)))

        print(readonly_connections, readonly_conn_idx)

        initial_conns = list(getattr(self, "user_connections", []) or [])

        annot = CrackAnnotator(
            image=self.original_image,
            boxes=boxes,
            initial_points=initial_points,
            initial_connections=initial_conns,
            initial_midlines={},  # start fresh editable set
        )

        # Attach read-only sets to annotator
        annot.readonly_midlines = readonly_midlines
        annot.readonly_connections = readonly_conn_idx

        annot.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)

        dlg = QDialog(self.MainWindow)
        dlg.setWindowTitle("Endpoints, Connections & Manual Midlines")
        dlg.setWindowModality(Qt.ApplicationModal)
        dlg.setWindowFlags(dlg.windowFlags() | Qt.WindowMaximizeButtonHint)
        layout = QVBoxLayout(dlg)

        mode_btn = QPushButton("Switch to Connection Mode")
        mode_btn.setCheckable(True)
        layout.addWidget(mode_btn)

        manual_btn = QPushButton("Manual Midlines: OFF")
        manual_btn.setCheckable(True)
        manual_btn.setVisible(False)
        layout.addWidget(manual_btn)

        hint = QLabel(
            "Manual: Left-hold on starting point → draw (hold/click) → finish w/ hold/click endpoint.\n"
            "Read-only cracks shown in gray — can't be deleted."
        )
        layout.addWidget(hint)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(annot)
        layout.addWidget(scroll, 1)

        btn_row = QHBoxLayout()
        btn_done, btn_cancel = QPushButton("Done"), QPushButton("Cancel")
        btn_row.addWidget(btn_done)
        btn_row.addWidget(btn_cancel)
        layout.addLayout(btn_row)

        def all_points_in_boxes():
            def in_any(pt):
                x, y = pt
                for xmin, ymin, xmax, ymax in boxes:
                    if xmin <= x <= xmax and ymin <= y <= ymax:
                        return True
                return False

            # Build set of point indices from read-only items
            readonly_point_idxs = set()
            for (i1, i2) in annot.readonly_connections:
                readonly_point_idxs.update([i1, i2])
            for (i1, i2) in annot.readonly_midlines.keys():
                readonly_point_idxs.update([i1, i2])

            # Only check points that are NOT in readonly sets
            bad = [
                pt for idx, pt in enumerate(annot.points)
                if idx not in readonly_point_idxs and not in_any(pt)
            ]
            return (len(bad) == 0, bad)

        def confirm_discard():
            mb = QMessageBox(dlg)
            mb.setIcon(QMessageBox.Warning)
            mb.setWindowTitle("Discard current midline?")
            mb.setText("You're in the middle of drawing a midline. Discard it?")
            mb.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            return mb.exec_() == QMessageBox.Yes

        def update_controls_visibility():
            if annot.polyline_mode:
                mode_btn.setVisible(False)
                manual_btn.setVisible(True)
                manual_btn.setText("Manual Midlines: ON")
                manual_btn.setStyleSheet("background:#79d2e6;")
            else:
                mode_btn.setVisible(True)
                if annot.connection_mode:
                    mode_btn.setText("Switch to Point Mode")
                    mode_btn.setStyleSheet("background:#97e297;")
                else:
                    mode_btn.setText("Switch to Connection Mode")
                    mode_btn.setStyleSheet("background:#e2c297;")
                manual_btn.setVisible(annot.connection_mode and (not annot.all_pairs_saturated()))
                manual_btn.setText("Manual Midlines: OFF")
                manual_btn.setStyleSheet("")

        mode_btn.clicked.connect(lambda: (annot.toggle_mode(), update_controls_visibility()))
        manual_btn.clicked.connect(lambda checked: (
            annot.set_mode_polyline(checked, confirm_cb=confirm_discard),
            update_controls_visibility()
        ))
        update_controls_visibility()

        def on_done():
            if annot.polyline_mode and annot._is_drawing:
                if not confirm_discard():
                    return
                annot.set_mode_polyline(False)

            ok, bad = all_points_in_boxes()
            if not ok:
                QMessageBox.warning(dlg, "Points outside boxes", "All points must be inside a bounding box.")
                return

            self.user_points = annot.points
            self.all_selected_points = list(self.user_points)  # keep permanent copy for matching later
            self.user_connections = [c for c in annot.connections if c not in annot.readonly_connections]

            self.endpoint_pairs = [
                (self.user_points[i1], self.user_points[i2])
                for (i1, i2) in self.user_connections
            ]

            self.manual_endpoint_pairs = []
            for (i1, i2), poly in annot.midlines.items():
                self.manual_endpoint_pairs.append((self.user_points[i1], self.user_points[i2]))

            self.manual_midlines_tmp = {
                f"{i1}_{i2}": [[float(x), float(y)] for (x, y) in poly]
                for (i1, i2), poly in annot.midlines.items()
            }

            
            print("\n[DEBUG] --- Saving manual midlines from annotator ---")
            print(f"[DEBUG] Annotator midlines count: {len(annot.midlines)}")
            for key, poly in annot.midlines.items():
                print(f"[DEBUG] Key: {key}, FirstPt: {poly[0] if poly else None}, LastPt: {poly[-1] if poly else None}")
            print(f"[DEBUG] Annotator points: {annot.points}")
            print(f"[DEBUG] Annotator connections: {annot.connections}")

            self.manual_midlines_tmp = {
                f"{i1}_{i2}": [[float(x), float(y)] for (x, y) in poly]
                for (i1, i2), poly in annot.midlines.items()
            }

            print(f"[DEBUG] Stored manual_midlines_tmp keys: {list(self.manual_midlines_tmp.keys())}")
            for k, v in self.manual_midlines_tmp.items():
                print(f"[DEBUG]   {k}: first={v[0]}, last={v[-1]}")

            dlg.accept()

        btn_done.clicked.connect(on_done)
        btn_cancel.clicked.connect(lambda: dlg.reject())

        dlg.showMaximized()
        QApplication.processEvents()
        if dlg.exec_() != QDialog.Accepted:
            return

        print(f"Points: {self.user_points}")
        print(f"Connections: {self.user_connections}")
        print(f"Endpoint pairs: {self.endpoint_pairs}")
        print(f"Manual endpoint pairs: {getattr(self, 'manual_endpoint_pairs', [])}")
        print(f"Midlines saved: {len(self.manual_midlines_tmp)}")
        self.update_image_crop_button.setStyleSheet("background-color: lightblue")
         
    def update_image_crop(self):
        try:
            downsample_factor = self.downsample_factor_box.value()
            color_channel = [0 if self.color_chenel_box.currentText()=='R' else 1 if self.color_chenel_box.currentText()=='B' else 2]

            # Use only the bounding box for cropping!
            if not (hasattr(self, "active_bbox") and self.active_bbox is not None):
                raise ValueError("No active bounding box for cropping.")
            xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
            # Sanity check
            if xmax <= xmin or ymax <= ymin:
                print(f"Invalid bounding box cropping window: ({xmin},{ymin}) to ({xmax},{ymax}), skipping.")
                return

            # Crop the image to the bounding box
            self.image_crop = self.original_image[ymin:ymax, xmin:xmax]
            # Ensure the crop is not too small for tracking/segmentation
            h, w = self.image_crop.shape[:2]
            if h < min_crop_size or w < min_crop_size:
                print(f"Skipping segment: Crop too small for processing ({w}x{h})")
                # Optionally set a flag to skip the rest of the pipeline for this segment
                self.skip_current_segment = True
                return
            else:
                self.skip_current_segment = False
            # Shift endpoints relative to bbox origin
            self.pts_crop = [np.array([pt[0]-xmin, pt[1]-ymin]) for pt in self.pts]

            # Sanity check: make sure all shifted points are in bounds
            img_h, img_w = self.image_crop.shape[:2]
            for pt in self.pts_crop:
                if not (0 <= pt[0] < img_w and 0 <= pt[1] < img_h):
                    print(f"Endpoint {pt} not in bbox-cropped image ({img_w},{img_h}), skipping this segment.")
                    return

            # Downsample as before
            black_crack = [0 if self.crack_color_box.currentText() =='Bright crack' else 1 ][0]
            func = np.min if black_crack==1 else np.max
            self.image_crop_down = skimage.measure.block_reduce(
                self.image_crop, block_size=(downsample_factor, downsample_factor, 1),
                func=func, cval=0, func_kwargs=None)
            self.pts_crop_down = [np.array(x) / downsample_factor for x in self.pts_crop]
            self.image_down = skimage.measure.block_reduce(
                self.original_image, block_size=(downsample_factor, downsample_factor, 1),
                func=func, cval=0, func_kwargs=None)
            self.pts_down = [np.array(x) / downsample_factor for x in self.pts]
            gs_image = self.image_crop_down[:,:,color_channel].astype(np.uint8)
            h, w = gs_image.shape[:2]
            for idx, pt in enumerate(self.pts_crop_down):
                x, y = int(round(pt[0])), int(round(pt[1]))
                if 0 <= x < w and 0 <= y < h:
                    gs_image = cv2.circle(gs_image, center=(x, y), radius=2, color=(0,255,0), thickness=2)
                else:
                    print(f"Warning: Skipping drawing point ({x},{y}) out of image bounds ({w},{h})")
            qimage = QImage(gs_image.astype(dtype=np.uint8), gs_image.shape[1], gs_image.shape[0],
                            gs_image.strides[0], QImage.Format_Grayscale8)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.image_crop_down_display.width(), self.image_crop_down_display.height(), Qt.KeepAspectRatio, Qt.FastTransformation)
            self.image_crop_down_display.setPixmap(scaled_pixmap)
            self.x_size_show.display(self.image_crop_down.shape[1])
            self.y_size_show.display(self.image_crop_down.shape[0])
            self.update_os_button.setStyleSheet("background-color : lightblue")
            
            # Debug: Visualize crop and points
        except Exception as e:
            import traceback
            traceback.print_exc()
            error(f"update_image_crop: {e}")
            self.update_os_button.setStyleSheet("background-color : red")

    def check_wavelet(self):
        try:
            size = self.wavelet_size_box.value()
            nOrientations = self.wavelet_norientations_box.value()
            design = "N"
            inflectionPoint = self.wavelet_inflection_point_box.value()
            mnOrder = self.wavelet_mnorder_box.value()
            splineOrder = 3
            overlapFactor = self.wavelet_overlap_factor_box.value()
            dcStdDev = self.wavelet_STD_box.value()
            directional = False
            window_size = self.wavelet_window_size_box.value()

            wavelet = ct.os.CheckWavelet(window_size = window_size, size = size, nOrientations = nOrientations, design = design, 
                            inflectionPoint = inflectionPoint, mnOrder = mnOrder, splineOrder = splineOrder,
                            overlapFactor = overlapFactor, dcStdDev = dcStdDev, directional = directional,
                            display_orientations=[0])[0,:,:]
            wavelet = wavelet - np.min(wavelet)
            wavelet = (wavelet*254/np.max(wavelet)).astype(dtype=np.int8)

            qimage = QImage(wavelet.astype(dtype=np.uint8), wavelet.shape[1], wavelet.shape[0], 
                            wavelet.strides[0], QImage.Format_Grayscale8)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.wavelet_check_display.width(), self.wavelet_check_display.height(), Qt.KeepAspectRatio, Qt.FastTransformation)
            self.wavelet_check_display.setPixmap(scaled_pixmap)
        except Exception as e:
            error(e)

    def update_os(self):
        try:
            self.os_progress_bar.setValue(0)
            color_channel = [0 if self.color_chenel_box.currentText()=='R' else 1 if self.color_chenel_box.currentText()=='B' else 2][0]
            black_crack = -1 if self.crack_color_box.currentText() =='Bright crack' else 1
            size = self.wavelet_size_box.value()
            nOrientations = self.wavelet_norientations_box.value()
            design = "N"
            inflectionPoint = self.wavelet_inflection_point_box.value()
            mnOrder = self.wavelet_mnorder_box.value()
            splineOrder = 3
            overlapFactor = self.wavelet_overlap_factor_box.value()
            dcStdDev = self.wavelet_STD_box.value()
            directional = False
            from time import time
            start_time = time()

            # --- Use the full downsampled image for OS ---
            img_full = self.image_crop_down[:,:,color_channel].copy()  # shape (H_full, W_full)

            # --- Compute the orientation score on the full downsampled image ---
            os_results = ct.os.OrientationScoreTransform(
                img_full / 255 * black_crack, size=size, nOrientations=nOrientations,
                design=design, inflectionPoint=inflectionPoint, mnOrder=mnOrder,
                splineOrder=splineOrder, overlapFactor=overlapFactor,
                dcStdDev=dcStdDev, directional=directional
            )
            '''mask_bin = (self.current_mask > 0)
            xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
            mask_cropped = mask_bin[ymin:ymax, xmin:xmax]
            mask3d = np.broadcast_to(mask_cropped, os_results.shape)
            os_results = np.where(mask3d, os_results, 0)'''
            self.osGFCost = os_results

            print(f"OrientationScoreTransform time: {time() - start_time}")
            self.os_progress_bar.setValue(100)
            self.update_cost_button.setStyleSheet("background-color : lightblue")
            self.show_os_button.setStyleSheet("background-color : lightblue")
        except Exception as e:
            error(e)
            self.update_cost_button.setStyleSheet("background-color : red")
            self.show_os_button.setStyleSheet("background-color : red")
    
    def update_cost(self):
        try:
            self.update_cost_bar.setValue(0)
            lambdaa = self.lambda_box.value()
            p = self.power_box.value()
            ksi = 1
            zeta = 1
            sigmas = self.sigmas_line_edit.text()
            sigmas = [float(i) for i in sigmas.split(sep = ',')]
            sigmas_ext = 1
            start_time = time.time()
            self.multiscalecostLIFExtReg = ct.os.MultiScaleVesselness(self.osGFCost.real,ksi,1,sigmas,"LIF",sigmas_ext = sigmas_ext)
            print(f"MultiScaleVesselness took {time.time() - start_time:.2f} seconds")
            
            start_time = time.time()
            costmultiscale = ct.os.MultiScaleVesselnessFilter(self.multiscalecostLIFExtReg)
            print(f"MultiScaleVesselnessFilter took {time.time() - start_time:.2f} seconds")
            start_time = time.time()
            self.costFunction = ct.os.CostFunction(costmultiscale,lambdaa = lambdaa, p = p)
            print(f"CostFunction took {time.time() - start_time:.2f} seconds")

            if getattr(self, 'current_mask', None) is not None and self.current_mask is not None:
                # Sharpen cost inside mask
                improved_cost = self.costFunction ** 2.0  # (You can tune the exponent as needed)
                # If mask exists, apply it to the cost function
                mask_bin = (self.current_mask > 0)
                xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
                mask_cropped = mask_bin[ymin:ymax, xmin:xmax]
                mask3d = np.broadcast_to(mask_cropped, self.costFunction.shape)
                PENALTY = 5.0
                improved_cost = np.where(mask3d, improved_cost, np.clip(improved_cost * PENALTY, 0, 1))
                self.costFunction = improved_cost
            c00 = np.min(ct.os.Rescale(self.costFunction),axis = 0)
            #c00 = np.max(ct.os.Rescale(self.costFunction), axis=0)
            self.update_cost_bar.setValue(100)
            c00 = c00 - np.min(c00)
            c00 = (c00*255/np.max(c00)).astype(dtype=np.uint8)
            print("c00 shape:", c00.shape)
            qimage = QImage(c00.astype(dtype=np.uint8), c00.shape[1], c00.shape[0], 
                            c00.strides[0], QImage.Format_Grayscale8)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.cost_display.width(), self.cost_display.height(), Qt.KeepAspectRatio, Qt.FastTransformation)
            self.cost_display.setPixmap(scaled_pixmap)
            print("c00 shape:", c00.shape)
            self.midline_track_button.setStyleSheet("background-color : lightblue")
        except Exception as e:
            error(e)
            self.midline_track_button.setStyleSheet("background-color : red")

    def midline_tracking(self):
        try :
            self.tracking_bar.setValue(0)
            w = self.track_width_box.value()
            if self.track_color_box.currentText() == "R":
                color = (255,0,0)
            elif self.track_color_box.currentText() == "G":
                color = (0,255,0)
            elif self.track_color_box.currentText() == "B":
                color = (0,0,255)
            elif self.track_color_box.currentText() == "W":
                color = (255,255,255)

            y_margin = self.y_margin_box.value()
            x_margin = self.x_margin_box.value()
            g11 = self.g11_box.value()
            g22 = self.g22_box.value()
            g33 = self.g33_box.value()
            x_margin = self.x_margin_box.value()
            downsample_factor = self.downsample_factor_box.value()

            track_crop_down = ct.tracking.fast_marching(self.costFunction,self.pts_crop_down[0],self.pts_crop_down[1],g11=g11,g22=g22,g33=g33)
            track_crop_down[0] = track_crop_down[0]-0.5
            track_crop_down[1] = track_crop_down[1]-0.5
            track_crop = track_crop_down.copy()
            track_crop[0] = track_crop_down[0]*downsample_factor
            track_crop[1] = track_crop_down[1]*downsample_factor
            self.track_crop = track_crop
            track = ct.tools.track_crop_to_full(track_crop,self.pts[0],self.pts[1],y_margin,x_margin)
            #print(self.track_crop, track,downsample_factor)
            self.track = track
            #print(self.track)
            pts = np.array(track_crop).transpose(1,0).reshape((-1,1,2)).astype(np.int32)
            im = self.image_crop.astype(np.uint8)
            im = cv2.polylines(im, [pts], False, color, w)
            #print("...")
            qimage = QImage(im, im.shape[1], im.shape[0], 
                            im.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.track_display.width(), self.track_display.height(), Qt.KeepAspectRatio, Qt.FastTransformation)
            self.track_display.setPixmap(scaled_pixmap)
            self.tracking_bar.setValue(100)
            self.update_track_display_button.setStyleSheet("background-color : lightblue")
            self.track_full_screen_button.setStyleSheet("background-color : lightblue")
            self.edge_mask_button.setStyleSheet("background-color : lightblue")
        except Exception as e:
            error(e)
            self.update_track_display_button.setStyleSheet("background-color : red")
            self.track_full_screen_button.setStyleSheet("background-color : red")
            self.edge_mask_button.setStyleSheet("background-color : red")
                
    def edge_mask(self):
        try:
            window_half_size = int(self.edge_filter_size_box.value() / 2)
            black_crack = [-1 if self.crack_color_box.currentText() == 'Bright crack' else 1][0]
            color_channel = [0 if self.color_chenel_box.currentText() == 'R'
                            else 1 if self.color_chenel_box.currentText() == 'B'
                            else 2][0]

            print(f"[EDGE_MASK] window_half_size={window_half_size}, black_crack={black_crack}, color_channel={color_channel}")
            print(f"[EDGE_MASK] self.track shape={np.array(self.track).shape}, sample={np.array(self.track)[:, :5]}")
            print(f"[EDGE_MASK] self.pts={self.pts}, active_bbox={self.active_bbox}, current_source={getattr(self, 'current_source', None)}")

            img_gray = self.original_image[:, :, color_channel] * black_crack
            track = np.array(self.track)

            # Always store as [y, x] in full image coordinates
            if getattr(self, "current_source", None) == "manual":
                # Manual track was stored in crop coords → convert back to full image coords
                xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
                track_full_y = track[0] + ymin
                track_full_x = track[1] + xmin
                track = np.vstack([track_full_y, track_full_x])
                print("[EDGE_MASK] Manual mode - converted crop coords to full image coords")
            else:
                # Auto mode: stored as [y, x] but needs swap + shift
                track = np.vstack([track[1], track[0]])
                target_point = np.array([self.pts[1][1], self.pts[1][0]])
                shift_vector = target_point - track[:, 0]
                track = track + shift_vector[:, np.newaxis]
                print(f"[EDGE_MASK] Auto mode - applied shift: {shift_vector}")

            xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
            self.edge_mask1, self.edge_mask2 = ct.segmentation.edge_masks(img_gray, track)

            print(f"[EDGE_MASK] edge_mask1 stats: min={self.edge_mask1.min()}, max={self.edge_mask1.max()}, shape={self.edge_mask1.shape}")
            print(f"[EDGE_MASK] edge_mask2 stats: min={self.edge_mask2.min()}, max={self.edge_mask2.max()}, shape={self.edge_mask2.shape}")

            # Crop masks
            self.edge_mask1_crop = self.edge_mask1[ymin:ymax, xmin:xmax]
            self.edge_mask2_crop = self.edge_mask2[ymin:ymax, xmin:xmax]
            print(f"[EDGE_MASK] Cropped masks: shape1={self.edge_mask1_crop.shape}, shape2={self.edge_mask2_crop.shape}")

            # Adjust track to crop coordinates
            shifted_track = np.zeros_like(track)
            shifted_track[0] = track[0] - ymin
            shifted_track[1] = track[1] - xmin
            self.adjusted_track = shifted_track
            print(f"[EDGE_MASK] adjusted_track sample={self.adjusted_track[:, :5]}")

            # Normalize for display
            edge_mask1_crop = self.edge_mask1_crop - np.min(self.edge_mask1_crop)
            if np.max(edge_mask1_crop) != 0:
                edge_mask1_crop = (edge_mask1_crop * 255 / np.max(edge_mask1_crop)).astype(dtype=np.uint8)
            else:
                edge_mask1_crop = (edge_mask1_crop * 255).astype(dtype=np.uint8)

            qimage = QImage(edge_mask1_crop, edge_mask1_crop.shape[1], edge_mask1_crop.shape[0],
                            edge_mask1_crop.strides[0], QImage.Format_Grayscale8)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.edge_map_display.width(), self.edge_map_display.height(), Qt.KeepAspectRatio, Qt.FastTransformation)
            self.edge_map_display.setPixmap(scaled_pixmap)
            self.edge_tracks_button.setStyleSheet("background-color : lightblue")
        except Exception as e:
            import traceback
            traceback.print_exc()
            error(e)
            self.edge_tracks_button.setStyleSheet("background-color : red")
        
    def edge_tracks_full_screen(self):
        try:
            w = self.edge_track_width_box.value()
            if self.edge_track_color_box.currentText() == "R":
                c = 'r'
            elif self.edge_track_color_box.currentText() == "G":
                c = 'g'
            elif self.edge_track_color_box.currentText() == "B":
                c = 'b'
            elif self.edge_track_color_box.currentText() == "W":
                c = 'w'

            im = self.image.astype(np.uint8)
            plt.imshow(im)
            plt.plot(self.track_e1[0],self.track_e1[1],color = c,linewidth=w)
            plt.plot(self.track_e2[0],self.track_e2[1],color = c,linewidth=w)
            plt.show()
        except Exception as e:
            error(e)
        
    def draw_segment(self):
        try:
            image_size = self.select_image_size.value()
            x,y = ct.tools.Draw().counturs(self.image[:,:,::-1],image_size)
            if len(x) == 0:
                return
            x = np.concatenate([x,np.array(x[0]).reshape(1)])
            y = np.concatenate([y,np.array(y[0]).reshape(1)])
            self.manuall_x = np.array(x)
            self.manuall_y = np.array(y)

            pts = np.array([x,y]).transpose(1,0).reshape((-1,1,2)).astype(np.int32)
            im = self.image.astype(np.uint8)
            im = cv2.polylines(im, [pts], False, (0, 255, 0), 1)

            qimage = QImage(im, im.shape[1], im.shape[0], 
                            im.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.manual_segment_screen.width(), self.manual_segment_screen.height(), Qt.KeepAspectRatio, Qt.FastTransformation)
            self.manual_segment_screen.setPixmap(scaled_pixmap)
        except Exception as e:
            error(e)
          
    # in select_save_end_points
    def select_save_end_points(self):
        self.select_end_points_manmidlines()
        self.save_annotation()
        self.change_image()

    def save_manual_segment(self):
        """
        Save the currently drawn manual polygon as a new atomic crack (compact mask_crop + mask_bbox).
        After saving, automatically attempt to attach this atomic to the biggest overlapping existing atomic.
        """
        try:
            if not hasattr(self, "manuall_x") or not hasattr(self, "manuall_y"):
                error("No manual polygon to save.")
                return
            if len(self.manuall_x) < 3 or len(self.manuall_y) < 3:
                error("Manual polygon is too small or not closed.")
                return

            mask_full = ct.segmentation.create_mask(self.image, self.manuall_y, self.manuall_x).astype(np.uint8)
            if not np.any(mask_full):
                error("Manual polygon produced an empty mask.")
                return

            H, W = mask_full.shape[:2]
            ys, xs = np.where(mask_full > 0)
            y0, y1 = int(ys.min()), int(ys.max() + 1)
            x0, x1 = int(xs.min()), int(xs.max() + 1)
            crop = mask_full[y0:y1, x0:x1].astype(np.uint8)

            ann = self.annotation.setdefault("annotations", {})
            ac = ann.setdefault("atomic_cracks", {})

            ids = []
            for k in ac.keys():
                try: ids.append(int(k))
                except: pass
            new_id = str(max(ids) + 1 if ids else 0)

            ac[new_id] = {
                "source": "manual",
                "midline": [],                  # no midline now
                "geodesic_edges": {},           # no edges now
                "normal_edge_points": None,
                "mask_crop": crop.tolist(),
                "mask_bbox": [int(x0), int(y0), int(x1 - x0), int(y1 - y0)],
                "user_points": [],
                "user_connections": []
            }

            self.save_annotation()

            # --- NEW: try to attach to the biggest overlapping atomic crack
            self.try_attach_manual_to_existing(new_id, min_overlap_pixels=5)

            # Cleanup
            if hasattr(self, "manuall_x"): del self.manuall_x
            if hasattr(self, "manuall_y"): del self.manuall_y

        except Exception as e:
            error(e)
            
    '''def clear_segmentation(self):
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QListWidget, QPushButton, QHBoxLayout
        import numpy as np, json, cv2, os

        if not hasattr(self, "annotation") or not isinstance(self.annotation, dict):
            error("No annotation data loaded.")
            return

        ann = self.annotation.get("annotations", {})
        atomic_cracks = ann.setdefault("atomic_cracks", {})
        combined_cracks = ann.setdefault("combined_cracks", {})

        masks = []
        labels = []
        items = []

        H, W = self.original_image.shape[:2]

        # --- Atomic cracks ---
        for crack_id, crack in atomic_cracks.items():
            m = reconstruct_full_mask_from_crack(crack, H, W)
            masks.append(m)
            labels.append(f"Atomic {crack_id}" + ("" if np.any(m) else " (empty)"))
            items.append(("atomic", crack_id))

        # --- Combined cracks ---
        for crack_id, crack in combined_cracks.items():
            m = reconstruct_full_mask_from_crack(crack, H, W)
            masks.append(m)
            members = crack.get("members", [])
            labels.append(f"Combined {crack_id} (from: {','.join(map(str, members))})" + ("" if np.any(m) else " (empty)"))
            items.append(("combined", crack_id))

        if not masks:
            error("No saved cracks to delete.")
            return

        # --- Selection dialog ---
        dlg = QDialog(self.MainWindow)
        dlg.setWindowTitle("Select Segments to Delete")
        layout = QVBoxLayout(dlg)
        listwidget = QListWidget()
        listwidget.setSelectionMode(QListWidget.MultiSelection)
        for lbl in labels:
            listwidget.addItem(lbl)
        layout.addWidget(listwidget)

        btns = QHBoxLayout()
        btn_ok = QPushButton("Delete Selected")
        btn_cancel = QPushButton("Cancel")
        btns.addWidget(btn_ok)
        btns.addWidget(btn_cancel)
        layout.addLayout(btns)

        btn_ok.clicked.connect(dlg.accept)
        btn_cancel.clicked.connect(dlg.reject)

        def highlight_selected_segments():
            display = self.original_image.copy()
            for i, m in enumerate(masks):
                color = (255, 0, 0)
                alpha = 0.25
                if listwidget.item(i).isSelected():
                    color = (255, 255, 0)
                    alpha = 0.6
                if np.any(m):
                    overlay = np.zeros_like(display)
                    overlay[m.astype(bool)] = color
                    display = cv2.addWeighted(display, 1, overlay, alpha, 0)
            im = display.astype(np.uint8)
            from PyQt5.QtGui import QImage, QPixmap
            from PyQt5.QtCore import Qt
            qimage = QImage(im, im.shape[1], im.shape[0], im.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(
                self.ImageScreen.width(), self.ImageScreen.height(),
                Qt.KeepAspectRatio, Qt.FastTransformation
            )
            self.ImageScreen.setPixmap(scaled_pixmap)

        listwidget.itemSelectionChanged.connect(highlight_selected_segments)
        highlight_selected_segments()

        if dlg.exec_() == QDialog.Accepted:
            selected_indices = [i.row() for i in listwidget.selectedIndexes()]
            if not selected_indices:
                self.change_image()
                return

            print(f"[DEBUG] clear_segmentation START")
            print(f"  Atomic cracks before = {list(atomic_cracks.keys())}")
            print(f"  Combined cracks before = {list(combined_cracks.keys())}")

            # --- Delete selected ---
            for idx in sorted(selected_indices, reverse=True):
                tpe, crack_id = items[idx]
                if tpe == "atomic":
                    print(f"[DEBUG] Deleting atomic crack_id={crack_id}")
                    atomic_cracks.pop(crack_id, None)
                    for cid, combo in list(combined_cracks.items()):
                        if crack_id in combo.get("members", []):
                            combo["members"] = [m for m in combo["members"] if m != crack_id]
                            if not combo["members"]:
                                combined_cracks.pop(cid, None)
                elif tpe == "combined":
                    print(f"[DEBUG] Deleting combined crack_id={crack_id}")
                    combined_cracks.pop(crack_id, None)

            # --- Reindex cracks ---
            if atomic_cracks:
                new_atomic = {}
                for new_id, crack in enumerate([atomic_cracks[k] for k in sorted(atomic_cracks.keys(), key=lambda x: int(x))]):
                    new_atomic[str(new_id)] = crack
                atomic_cracks.clear()
                atomic_cracks.update(new_atomic)

            if combined_cracks:
                new_combined = {}
                for new_id, crack in enumerate([combined_cracks[k] for k in sorted(combined_cracks.keys(), key=lambda x: int(x))]):
                    new_combined[str(new_id)] = crack
                combined_cracks.clear()
                combined_cracks.update(new_combined)

            self.annotation["annotations"]["atomic_cracks"] = atomic_cracks
            self.annotation["annotations"]["combined_cracks"] = combined_cracks

            # --- Save + refresh ---
            self.save_annotation()
            self.change_image()
        else:
            self.change_image()'''
    
    def clear_segmentation(self):
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QListWidget, QPushButton, QHBoxLayout
        import numpy as np, cv2

        if not hasattr(self, "annotation") or not isinstance(self.annotation, dict):
            error("No annotation data loaded.")
            return

        ann = self.annotation.get("annotations", {})
        atomic_cracks = ann.setdefault("atomic_cracks", {})
        combined_cracks = ann.setdefault("combined_cracks", {})

        masks = []
        labels = []
        items = []

        H, W = self.original_image.shape[:2]

        # --- Atomic cracks only ---
        for crack_id, crack in atomic_cracks.items():
            m = reconstruct_full_mask_from_crack(crack, H, W)
            masks.append(m)
            labels.append(f"Atomic {crack_id}" + ("" if np.any(m) else " (empty)"))
            items.append(("atomic", crack_id))

        if not masks:
            error("No atomic cracks to delete.")
            return

        # --- Selection dialog ---
        dlg = QDialog(self.MainWindow)
        dlg.setWindowTitle("Select Atomic Segments to Delete")
        layout = QVBoxLayout(dlg)
        listwidget = QListWidget()
        listwidget.setSelectionMode(QListWidget.MultiSelection)
        for lbl in labels:
            listwidget.addItem(lbl)
        layout.addWidget(listwidget)

        btns = QHBoxLayout()
        btn_ok = QPushButton("Delete Selected")
        btn_cancel = QPushButton("Cancel")
        btns.addWidget(btn_ok)
        btns.addWidget(btn_cancel)
        layout.addLayout(btns)

        btn_ok.clicked.connect(dlg.accept)
        btn_cancel.clicked.connect(dlg.reject)

        def highlight_selected_segments():
            display = self.original_image.copy()
            for i, m in enumerate(masks):
                color = (255, 0, 0)
                alpha = 0.25
                if listwidget.item(i).isSelected():
                    color = (255, 255, 0)
                    alpha = 0.6
                if np.any(m):
                    overlay = np.zeros_like(display)
                    overlay[m.astype(bool)] = color
                    display = cv2.addWeighted(display, 1, overlay, alpha, 0)
            from PyQt5.QtGui import QImage, QPixmap
            qimage = QImage(display, display.shape[1], display.shape[0],
                            display.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            self.ImageScreen.setPixmap(
                pixmap.scaled(self.ImageScreen.width(), self.ImageScreen.height(),
                            Qt.KeepAspectRatio, Qt.FastTransformation)
            )

        listwidget.itemSelectionChanged.connect(highlight_selected_segments)
        highlight_selected_segments()

        if dlg.exec_() == QDialog.Accepted:
            selected_indices = [i.row() for i in listwidget.selectedIndexes()]
            if not selected_indices:
                self.change_image()
                return

            print(f"[DEBUG] clear_segmentation START")
            print(f"  Atomic cracks before = {list(atomic_cracks.keys())}")

            # --- Delete selected ---
            for idx in sorted(selected_indices, reverse=True):
                tpe, crack_id = items[idx]
                if tpe == "atomic":
                    print(f"[DEBUG] Deleting atomic crack_id={crack_id}")
                    atomic_cracks.pop(crack_id, None)
                    # Remove from combined_cracks members if present
                    for cid, combo in list(combined_cracks.items()):
                        # Remove deleted atomic cracks from members
                        combo["members"] = [m for m in combo.get("members", []) if m in atomic_cracks]

                        # Delete if fewer than 2 members remain
                        if len(combo["members"]) < 2:
                            combined_cracks.pop(cid, None)
                            continue

                        # Get full image size
                        H, W = self.original_image.shape[:2]

                        # --- Rebuild union mask ---
                        union_mask = np.zeros((H, W), dtype=np.uint8)
                        for m_id in combo["members"]:
                            member_crack = atomic_cracks.get(m_id)
                            if member_crack is not None:
                                union_mask |= reconstruct_full_mask_from_crack(member_crack, H, W)

                        if np.any(union_mask):
                            ys, xs = np.where(union_mask > 0)
                            y0, y1 = int(ys.min()), int(ys.max() + 1)
                            x0, x1 = int(xs.min()), int(xs.max() + 1)
                            crop = union_mask[y0:y1, x0:x1].astype(np.uint8)
                            combo["mask_crop"] = crop.tolist()
                            combo["mask_bbox"] = [int(x0), int(y0), int(x1 - x0), int(y1 - y0)]
                        else:
                            combined_cracks.pop(cid, None)

            # --- Reindex atomic cracks only ---
            if atomic_cracks:
                new_atomic = {}
                for new_id, crack in enumerate(
                    [atomic_cracks[k] for k in sorted(atomic_cracks.keys(), key=lambda x: int(x))]
                ):
                    new_atomic[str(new_id)] = crack
                atomic_cracks.clear()
                atomic_cracks.update(new_atomic)

            self.annotation["annotations"]["atomic_cracks"] = atomic_cracks
            self.annotation["annotations"]["combined_cracks"] = combined_cracks

            # --- Save + refresh ---
            self.save_annotation()
            self.change_image()
        else:
            self.change_image()
    
    def edge_tracking(self):
        try:
            color_channel = [0 if self.edge_track_color_box.currentText() == 'R'
                            else 1 if self.edge_track_color_box.currentText() == 'B' else 2][0]
            w = self.edge_track_width_box.value()
            mu = self.mu_box.value()
            l = self.l_box.value()
            p = self.p_box.value()

            res = ct.segmentation.edges_tracking(
                self.image_crop[:, :, color_channel],
                self.pts_crop,
                self.edge_mask1_crop, self.edge_mask2_crop, self.adjusted_track, mu=mu, l=l, p=p,
                return_normal_edges=True
            )

            track_e1, track_e2 = res["geodesic_edges"]
            normal_edges = res["normal_edge_points"]
            normal_edges_clipped = res["normal_edge_points_clipped"]

            # If editing an existing crack, reuse its ID
            if hasattr(self, "current_crack_id") and self.current_crack_id in self.crack_tracks:
                crack_id = self.current_crack_id
            else:
                crack_id = len(self.crack_tracks)
            self.current_crack_id = crack_id

            self.crack_tracks[crack_id] = [track_e1[:, 0], track_e1[:, 1]]
            self.track_e1 = [track_e1[:, 0], track_e1[:, 1]]
            self.track_e2 = [track_e2[:, 0], track_e2[:, 1]]

            # --- Store both crop and full-image normal edges ---
            if not hasattr(self, "normal_edge_points"):
                self.normal_edge_points = {}
            if not hasattr(self, "normal_edge_points_full"):
                self.normal_edge_points_full = {}

            self.normal_edge_points[crack_id] = normal_edges  # crop coords

            xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
            (e1x, e1y), (e2x, e2y) = normal_edges
            e1_global = np.stack([e1x + xmin, e1y + ymin], axis=1)
            e2_global = np.stack([e2x + xmin, e2y + ymin], axis=1)
            self.normal_edge_points_full[crack_id] = {
                "edge1": e1_global.tolist(),
                "edge2": e2_global.tolist()
            }

            if not hasattr(self, "normal_edge_points_clipped"):
                self.normal_edge_points_clipped = {}
            self.normal_edge_points_clipped[crack_id] = normal_edges_clipped

            # --- Draw crop tracks in lower-left panel ---
            pts1 = np.array([track_e1[:, 0], track_e1[:, 1]]).T.reshape((-1, 1, 2)).astype(np.int32)
            pts2 = np.array([track_e2[:, 0], track_e2[:, 1]]).T.reshape((-1, 1, 2)).astype(np.int32)
            im = self.image_crop.astype(np.uint8)
            im = cv2.polylines(im, [pts1], False, (0, 255, 0), w)
            im = cv2.polylines(im, [pts2], False, (0, 255, 0), w)
            qimage = QImage(im, im.shape[1], im.shape[0], im.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.edge_tracks_display.width(), self.edge_tracks_display.height(),
                                        Qt.KeepAspectRatio, Qt.FastTransformation)
            self.edge_tracks_display.setPixmap(scaled_pixmap)

            # --- NEW: Show all cracks' masks in the right-hand Segmentation panel ---
            full_mask_display = np.zeros(self.image.shape[:2], dtype=np.uint8)
            ann = self.annotation.get("annotations", {})
            atomic_cracks = ann.get("atomic_cracks", {})
            for crack in atomic_cracks.values():
                mc = crack.get("mask_crop")
                bb = crack.get("mask_bbox")
                if mc is not None and bb is not None:
                    crop = np.array(mc, dtype=np.uint8)
                    x, y, w_box, h_box = [int(v) for v in bb]
                    x2, y2 = min(x + w_box, self.image.shape[1]), min(y + h_box, self.image.shape[0])
                    w_eff, h_eff = max(0, x2 - x), max(0, y2 - y)
                    if h_eff > 0 and w_eff > 0:
                        crop = (crop > 0).astype(np.uint8)[:h_eff, :w_eff]
                        full_mask_display[y:y + h_eff, x:x + w_eff] |= crop

            # Overlay mask boundaries
            from skimage.segmentation import mark_boundaries
            display_im = (mark_boundaries(self.original_image / 255.0, full_mask_display,
                                        color=(0, 0, 1), background_label=0) * 255).astype(np.uint8)

            qimage = QImage(display_im, display_im.shape[1], display_im.shape[0],
                            display_im.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            scaled_pixmap = pixmap.scaled(self.ImageScreen.width(), self.ImageScreen.height(),
                                        Qt.KeepAspectRatio, Qt.FastTransformation)
            self.ImageScreen.setPixmap(scaled_pixmap)

            self.edge_tracks_full_screen_button.setStyleSheet("background-color : lightblue")
            self.save_current_segment_button.setStyleSheet("background-color : lightblue")

        except Exception as e:
            error(e)
            self.edge_tracks_full_screen_button.setStyleSheet("background-color : red")
            self.save_current_segment_button.setStyleSheet("background-color : red")
   
    # --- optional: moved verbatim (does not touch Qt) ---
    def save_current_segment(self):
        try:
            xmin, ymin, xmax, ymax = [int(round(v)) for v in self.active_bbox]
            print(f"[DEBUG] BBox: {(xmin, ymin, xmax, ymax)}")

            # Build crop mask from the two edges (in crop coords)
            edge_x_crop = np.concatenate((self.track_e1[1][::-1], self.track_e2[1]))
            edge_y_crop = np.concatenate((self.track_e1[0][::-1], self.track_e2[0]))
            mask_crop = ct.segmentation.create_mask(self.image_crop, edge_y_crop, edge_x_crop).astype(np.uint8)
            h, w = mask_crop.shape[:2]
            print(f"[DEBUG] mask_crop shape={mask_crop.shape}, nonzero={int((mask_crop>0).sum())}")

            src = getattr(self, "current_source", "auto")
            track_arr = np.array(self.adjusted_track, dtype=float)

            # Convert midline to full-image coords
            midline_coords = [
                [int(track_arr[1][i] + xmin), int(track_arr[0][i] + ymin)]
                for i in range(track_arr.shape[1])
            ]

            # Prepare annotation dict
            ann = self.annotation.setdefault("annotations", {})
            atomic_cracks = ann.setdefault("atomic_cracks", {})

            # Add full, unclipped normal-edge points (convert to full image coords)
            normal_edges = getattr(self, "normal_edge_points", {}).get(self.current_crack_id)
            normal_edges_full = None
            if normal_edges is not None:
                (e1x, e1y), (e2x, e2y) = normal_edges  # crop coords
                e1_global = np.stack([e1x + xmin, e1y + ymin], axis=1)
                e2_global = np.stack([e2x + xmin, e2y + ymin], axis=1)
                normal_edges_full = {"edge1": e1_global.tolist(), "edge2": e2_global.tolist()}

            # Save crack entry (store ONLY the crop + bbox, not a full-size mask)
            atomic_cracks[str(self.current_crack_id)] = {
                "source": src,
                "midline": midline_coords,
                "geodesic_edges": {
                    "edge1": [[int(self.track_e1[0][i] + xmin), int(self.track_e1[1][i] + ymin)]
                              for i in range(len(self.track_e1[0]))],
                    "edge2": [[int(self.track_e2[0][i] + xmin), int(self.track_e2[1][i] + ymin)]
                              for i in range(len(self.track_e2[0]))]
                },
                "normal_edge_points": normal_edges_full,
                # compact storage
                "mask_crop": mask_crop.tolist(),                 # (h, w) binary array
                "mask_bbox": [int(xmin), int(ymin), int(w), int(h)],  # [x, y, w, h]
                "user_points": getattr(self, "user_points", []),
                "user_connections": getattr(self, "user_connections", [])
            }
            print(f"[DEBUG] atomic_cracks now: {list(atomic_cracks.keys())}")

            # Hint for loaders: use per-crack masks rather than legacy lists
            self.use_masks = True

            # Persist to disk (save_annotation will rebuild & export a combined mask)
            self.save_annotation()

        except Exception as e:
            error(e)
    
    def select_end_points_manmidlines(self):
        self._debug_print_atomic_cracks("select_end_points_manmidlines START")
        if not hasattr(self, "original_image") or self.original_image is None:
            error("No original image found.")
            return

        from PyQt5.QtWidgets import (
            QDialog, QVBoxLayout, QHBoxLayout, QPushButton,
            QSizePolicy, QApplication, QMessageBox, QScrollArea, QLabel
        )

        boxes = self.get_all_bounding_boxes()

        readonly_midlines = {}
        readonly_connections = []
        existing_midlines = {}

        initial_points = list(getattr(self, "user_points", []) or [])
        initial_conns = list(getattr(self, "user_connections", []) or [])
        point_index_map = {tuple(pt): idx for idx, pt in enumerate(initial_points)}

        def ensure_point(pt):
            if tuple(pt) not in point_index_map:
                point_index_map[tuple(pt)] = len(initial_points)
                initial_points.append(pt)
            return point_index_map[tuple(pt)]

        if "annotations" in self.annotation:
            ann = self.annotation["annotations"]

            ann_midlines = ann.get("midlines", {})
            for k_str, pts in ann_midlines.items():
                try:
                    i1, i2 = map(int, k_str.split("_"))
                    if i1 != i2:  # Prevent self-midlines here
                        poly = [tuple(map(float, xy)) for xy in pts]
                        existing_midlines[(min(i1, i2), max(i1, i2))] = poly
                except Exception as e:
                    print(f"[WARN] Failed to parse manual midline {k_str}: {e}")

            for cid, crack in ann.get("atomic_cracks", {}).items():
                if hasattr(self, "current_crack_id") and str(cid) == str(self.current_crack_id):
                    continue

                src = crack.get("source", "auto")
                up = crack.get("user_points", [])
                if len(up) == 2:
                    p1, p2 = tuple(up[0]), tuple(up[1])
                else:
                    ml = crack.get("midline", [])
                    if len(ml) >= 2:
                        p1, p2 = tuple(ml[0]), tuple(ml[-1])
                    else:
                        continue

                idx1 = ensure_point(p1)
                idx2 = ensure_point(p2)

                if idx1 == idx2:
                    continue  # Prevent self-midlines here too

                if src == "manual":
                    poly = crack.get("midline", [])
                    if poly:
                        readonly_midlines[(idx1, idx2)] = [tuple(map(float, xy)) for xy in poly]
                else:
                    readonly_connections.append((p1, p2))

        for (i1, i2), poly in existing_midlines.items():
            start_idx = ensure_point(poly[0])
            end_idx = ensure_point(poly[-1])
            if start_idx != end_idx:
                readonly_midlines[(start_idx, end_idx)] = poly

        readonly_conn_idx = []
        for p1, p2 in readonly_connections:
            idx1 = ensure_point(p1)
            idx2 = ensure_point(p2)
            if idx1 != idx2:
                readonly_conn_idx.append((min(idx1, idx2), max(idx1, idx2)))

        annot = CrackAnnotator(
            image=self.original_image,
            boxes=boxes,
            initial_points=initial_points,
            initial_connections=initial_conns,
            initial_midlines={},
        )

        annot.readonly_midlines = readonly_midlines
        annot.readonly_connections = readonly_conn_idx

        # Also enforce at the widget level:
        # Wrap the original mousePressEvent to prevent bad start/finish overlaps
        # Also enforce at the widget level:
        orig_mousePressEvent = annot.mousePressEvent

        def guarded_mousePressEvent(ev):
            p = annot._to_image_coords(ev.pos())
            point_i = annot._find_point_at(p)

            # Gather extra debug state
            last_pt = annot.polyline[-1] if annot.polyline else None
            last_two_pts = annot.polyline[-2:] if len(annot.polyline) >= 2 else []
            conn_key = None
            if annot._is_drawing and point_i is not None and point_i != annot._start_idx:
                conn_key = annot._sorted(annot._start_idx, point_i)
            exists_midline = conn_key in annot.midlines if conn_key else None
            exists_conn = conn_key in annot.connections if conn_key else None
            exists_readonly_conn = conn_key in annot.readonly_connections if conn_key else None
            exists_readonly_mid = conn_key in annot.readonly_midlines if conn_key else None

            start_pt = annot.points[annot._start_idx] if annot._start_idx is not None and annot._start_idx < len(annot.points) else None

            print(
                f"[GUARDED_PRESS] btn={ev.button()} at {p} | "
                f"point_i={point_i}, start_idx={annot._start_idx}, start_pt={start_pt} | "
                f"_is_drawing={annot._is_drawing}, polyline_mode={annot.polyline_mode} | "
                f"polyline_len={len(annot.polyline)}, last_pt={last_pt}, last_two_pts={last_two_pts} | "
                f"_just_committed_midline={getattr(annot, '_just_committed_midline', False)}, "
                f"_last_polyline_end_idx={getattr(annot, '_last_polyline_end_idx', None)} | "
                f"conn_key={conn_key}, exists_midline={exists_midline}, exists_conn={exists_conn}, "
                f"exists_readonly_conn={exists_readonly_conn}, exists_readonly_mid={exists_readonly_mid}"
            )

            # If not in polyline mode — just pass through immediately
            if not annot.polyline_mode:
                print("[GUARDED_PRESS] Not in polyline_mode — passing through")
                orig_mousePressEvent(ev)
                return

            # --- Prevent immediate restart after a commit on either endpoint of last line ---
            if getattr(annot, "_just_committed_midline", False):
                last_end = getattr(annot, "_last_polyline_end_idx", None)
                last_start = getattr(annot, "_last_polyline_start_idx", None)
                if point_i is not None and point_i in (last_end, last_start):
                    print(
                        f"[GUARDED_PRESS] blocked: click is on endpoint {point_i} of last committed line "
                        f"({last_start}, {last_end}) — skipping to avoid rubberband"
                    )
                    annot._just_committed_midline = False
                    return
                # Reset flag if click is elsewhere
                annot._just_committed_midline = False

            # Polyline mode but NOT drawing yet
            if not annot._is_drawing:
                if point_i is not None and annot._start_idx == point_i:
                    print("[GUARDED_PRESS] blocked: start on same point as last start")
                    return
                print("[GUARDED_PRESS] passing to orig to START polyline")
                orig_mousePressEvent(ev)
                return

            # Polyline mode AND currently drawing
            if point_i is not None and point_i != annot._start_idx:
                print(f"[GUARDED_PRESS] finishing midline via click on endpoint {point_i}, key={conn_key}")
            elif point_i is None:
                print("[GUARDED_PRESS] adding freehand point via click")
            else:
                print("[GUARDED_PRESS] ignored click (same as start idx)")

            orig_mousePressEvent(ev)

        annot.mousePressEvent = guarded_mousePressEvent

        annot.setSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)

        dlg = QDialog(self.MainWindow)
        dlg.setWindowTitle("Endpoints, Connections & Manual Midlines")
        dlg.setWindowModality(Qt.ApplicationModal)
        dlg.setWindowFlags(dlg.windowFlags() | Qt.WindowMaximizeButtonHint)
        layout = QVBoxLayout(dlg)

        mode_btn = QPushButton("Switch to Connection Mode")
        mode_btn.setCheckable(True)
        layout.addWidget(mode_btn)

        manual_btn = QPushButton("Manual Midlines: OFF")
        manual_btn.setCheckable(True)
        manual_btn.setVisible(False)
        layout.addWidget(manual_btn)

        hint = QLabel(
            "Editable: Auto/Manual in black/light-blue.     Read-only: Auto/Manual cracks in gray/biege — cant delete in editor, must delete segment in Delete Segmentations.\n"
            "Click unconnected point in Connection Mode to create new point.        Hover and click in respective mode to delete.\n"
            "Manual: Left-hold on starting point → draw → finish on a different endpoint.       Backspace/Z or Right-hold for fast/slow deletion."
        )
        layout.addWidget(hint)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(annot)
        layout.addWidget(scroll, 1)

        btn_row = QHBoxLayout()
        btn_done, btn_cancel = QPushButton("Done"), QPushButton("Cancel")
        btn_row.addWidget(btn_done)
        btn_row.addWidget(btn_cancel)
        layout.addLayout(btn_row)

        def all_points_in_boxes():
            def in_any(pt):
                x, y = pt
                for xmin, ymin, xmax, ymax in boxes:
                    if xmin <= x <= xmax and ymin <= y <= ymax:
                        return True
                return False
            readonly_point_idxs = set()
            for (i1, i2) in annot.readonly_connections:
                readonly_point_idxs.update([i1, i2])
            for (i1, i2) in annot.readonly_midlines.keys():
                readonly_point_idxs.update([i1, i2])
            bad = [
                pt for idx, pt in enumerate(annot.points)
                if idx not in readonly_point_idxs and not in_any(pt)
            ]
            return (len(bad) == 0, bad)

        def confirm_discard():
            mb = QMessageBox(dlg)
            mb.setIcon(QMessageBox.Warning)
            mb.setWindowTitle("Discard current midline?")
            mb.setText("You're in the middle of drawing a midline. Discard it?")
            mb.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            return mb.exec_() == QMessageBox.Yes

        def update_controls_visibility():
            if annot.polyline_mode:
                mode_btn.setVisible(False)
                manual_btn.setVisible(True)
                manual_btn.setText("Manual Midlines: ON")
                manual_btn.setStyleSheet("background:#79d2e6;")
            else:
                mode_btn.setVisible(True)
                if annot.connection_mode:
                    mode_btn.setText("Switch to Point Mode")
                    mode_btn.setStyleSheet("background:#97e297;")
                else:
                    mode_btn.setText("Switch to Connection Mode")
                    mode_btn.setStyleSheet("background:#e2c297;")
                manual_btn.setVisible(annot.connection_mode and (not annot.all_pairs_saturated()))
                manual_btn.setText("Manual Midlines: OFF")
                manual_btn.setStyleSheet("")

        mode_btn.clicked.connect(lambda: (annot.toggle_mode(), update_controls_visibility()))
        manual_btn.clicked.connect(lambda checked: (
            annot.set_mode_polyline(checked, confirm_cb=confirm_discard),
            update_controls_visibility()
        ))
        update_controls_visibility()

        def on_done():
            if annot.polyline_mode and annot._is_drawing:
                if not confirm_discard():
                    return
                annot.set_mode_polyline(False)

            ok, bad = all_points_in_boxes()
            if not ok:
                QMessageBox.warning(dlg, "Points outside boxes", "All points must be inside a bounding box.")
                return

            self.user_points = annot.points
            self.user_connections = [c for c in annot.connections if c not in annot.readonly_connections]

            self.endpoint_pairs = [
                (self.user_points[i1], self.user_points[i2])
                for (i1, i2) in self.user_connections
            ]

            self.manual_endpoint_pairs = []
            for (i1, i2), poly in annot.midlines.items():
                if i1 != i2:  # Final check to prevent self-midline
                    self.manual_endpoint_pairs.append((self.user_points[i1], self.user_points[i2]))

            self.manual_midlines_tmp = {
                f"{i1}_{i2}": [[float(x), float(y)] for (x, y) in poly]
                for (i1, i2), poly in annot.midlines.items() if i1 != i2
            }

            if hasattr(self, "current_crack_id"):
                crack_id_str = str(self.current_crack_id)
                crack_entry = self.annotation.get("annotations", {}).get("atomic_cracks", {}).setdefault(crack_id_str, {})
                crack_entry["user_points"] = list(self.user_points)
                crack_entry["user_connections"] = list(self.user_connections)

            dlg.accept()

        btn_done.clicked.connect(on_done)
        btn_cancel.clicked.connect(lambda: dlg.reject())

        dlg.showMaximized()
        QApplication.processEvents()
        if dlg.exec_() != QDialog.Accepted:
            return

        print(f"Points: {self.user_points}")
        print(f"Connections: {self.user_connections}")
        print(f"Endpoint pairs: {self.endpoint_pairs}")
        print(f"Manual endpoint pairs: {getattr(self, 'manual_endpoint_pairs', [])}")
        print(f"Midlines saved: {len(self.manual_midlines_tmp)}")
        self.update_image_crop_button.setStyleSheet("background-color: lightblue")
        self._debug_print_atomic_cracks("select_end_points_manmidlines AFTER ACCEPT")
        self.all_selected_points = list(self.user_points)
    
    def run_pipeline(self, multirun=False):
        import gc, json
        import numpy as np
        from PyQt5.QtWidgets import QMessageBox
        from time import time

        def _next_crack_id_str():
            ann = self.annotation.get("annotations", {})
            ac = ann.get("atomic_cracks", {})
            used_ids = sorted(int(k) for k in ac.keys() if k.isdigit())
            
            # Find the first free ID
            next_id = 0
            for uid in used_ids:
                if uid == next_id:
                    next_id += 1
                else:
                    break
            return str(next_id)

        def _ensure_ann():
            self.annotation = self.annotation if isinstance(self.annotation, dict) else {}
            self.annotation.setdefault("annotations", {})
            self.annotation["annotations"].setdefault("atomic_cracks", {})
            self.annotation["annotations"].setdefault("combined_cracks", {})

        gc.collect()
        print("✅ GPU memory freed from CuPy pool")
        print("Running midline pipeline (auto + manual)...")

        boxes = self.get_all_bounding_boxes()
        print(f"Loaded {len(boxes)} bounding boxes: {boxes}")
        if not boxes:
            QMessageBox.critical(None, "No Bounding Boxes",
                "Please draw at least one bounding box before running the pipeline.")
            return

        _ensure_ann()
        ann = self.annotation["annotations"]
        ac_store = ann["atomic_cracks"]

        if not multirun:
            # Let the user pick points/connections/midlines
            self.endpoint_pairs = None
            self.user_connections = None
            self.user_points = None
            self.manual_endpoint_pairs = None
            self.all_selected_points = None  # reset before each run
            print("Calling select_end_points_manmidlines()...")
            self.select_end_points_manmidlines()

        # Merge auto + manual endpoint pairs (global, from annotator)
        all_pairs = []
        if getattr(self, "endpoint_pairs", None):
            print(f"Auto endpoint_pairs: {self.endpoint_pairs}")
            all_pairs.extend([(p, "auto") for p in self.endpoint_pairs])
        if getattr(self, "manual_endpoint_pairs", None):
            print(f"Manual endpoint_pairs: {self.manual_endpoint_pairs}")
            all_pairs.extend([(p, "manual") for p in self.manual_endpoint_pairs])

        if not all_pairs:
            QMessageBox.critical(None, "No Endpoint Pairs",
                "No endpoint pairs selected!\n\nPlease use 'Select Endpoints' and create at least one connection or manual midline before running the pipeline.")
            return

        # Group by bbox (so OS/cost is reused per box)
        box_to_pairs = {}
        for (pair, src) in all_pairs:
            candidates = []
            for bbox in boxes:
                xmin, ymin, xmax, ymax = bbox
                p0, p1 = pair
                if (xmin <= p0[0] <= xmax and ymin <= p0[1] <= ymax and
                    xmin <= p1[0] <= xmax and ymin <= p1[1] <= ymax):
                    area = abs((xmax - xmin) * (ymax - ymin))
                    candidates.append((area, bbox))
            if candidates:
                _, chosen_bbox = min(candidates, key=lambda x: x[0])
                key = tuple(chosen_bbox)
                box_to_pairs.setdefault(key, []).append((pair, src))

        errors = []
        # Make sure we don't blow away memory of previous masks
        if not hasattr(self, "mask"):
            self.mask = []
        if not hasattr(self, "crack_tracks"):
            self.crack_tracks = {}

        for bbox_key, pairs in box_to_pairs.items():
            xmin, ymin, xmax, ymax = bbox_key
            print(f"\n=== Processing bbox {bbox_key} ===")
            print(f"Pairs in this box: {pairs}")

            try:
                # Precompute OS/cost once per box for auto pairs
                auto_pairs = [p for p, s in pairs if s == "auto"]
                if auto_pairs:
                    first_pair = auto_pairs[0]
                    print(f"Precomputing OS/cost for auto pair {first_pair}")
                    self.pts = [np.array(first_pair[0]), np.array(first_pair[1])]
                    self.end_points = self.pts
                    self.active_bbox = list(bbox_key)
                    self.update_image_crop()
                    if getattr(self, "skip_current_segment", False):
                        continue
                    print("os (once per box)")
                    t0 = time(); self.update_os(); print(f"os time: {time()-t0:.2f}s")
                    print("cost (once per box)")
                    t0 = time(); self.update_cost(); print(f"cost time: {time()-t0:.2f}s")

                # Process each pair -> one atomic crack per pair
                for (p0, p1), src in pairs:
                    try:
                        self.active_bbox = list(bbox_key)
                        print(f"\n--- Processing pair {(p0, p1)} (source={src}) ---")

                        # IMPORTANT: make per-crack, pair-local endpoints for saving
                        # These two lines are what ensure each atomic_crack only stores its own pair.
                        pair_user_points = [tuple(p0), tuple(p1)]
                        pair_user_connections = [[0, 1]]  # exactly one connection per crack

                        if src == "manual":
                            # For manual, we reuse the drawn polyline as midline (full-image coords)
                            manual_midlines_dict = getattr(self, "manual_midlines_tmp", {})
                            found_key = None

                            # Make sure we have a durable copy of all selection points from earlier
                            all_points = getattr(self, "all_selected_points", None)
                            if all_points is None:
                                # Fallback: try to use user_points if all_points wasn't stored
                                all_points = getattr(self, "user_points", [])

                            print("\n[DEBUG] --- Matching manual midline ---")
                            print(f"[DEBUG] manual_midlines_tmp keys at runtime: {list(manual_midlines_dict.keys())}")
                            print(f"[DEBUG] all_points at runtime: {all_points}")
                            print(f"[DEBUG] Trying to match p0={p0}  p1={p1}")

                            # manual_midlines_tmp keys are "i_j" based on annotator indices; match geometrically
                            for k, poly in manual_midlines_dict.items():
                                try:
                                    i1, i2 = map(int, k.split("_"))
                                    c_i = tuple(all_points[i1])
                                    c_j = tuple(all_points[i2])
                                    print(f"[DEBUG] Checking key={k}, c_i={c_i}, c_j={c_j}")
                                    if (c_i, c_j) == (p0, p1) or (c_i, c_j) == (p1, p0):
                                        print(f"[DEBUG] Found match for key={k}")
                                        found_key = k
                                        break
                                except Exception as e:
                                    print(f"[DEBUG] Error parsing key={k}: {e}")
                                    pass

                            print(f"[MANUAL] Found key: {found_key}")
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.update_image_crop()
                            if getattr(self, "skip_current_segment", False):
                                continue

                            if found_key:
                                # Convert full-image manual polyline to crop coords and set as self.track
                                poly = np.array(manual_midlines_dict[found_key], dtype=float)  # [[x,y],...]
                                cy = poly[:, 1] - ymin
                                cx = poly[:, 0] - xmin
                                self.track = np.vstack([cy, cx])
                                self.pts_crop = [
                                    np.array(self.pts[0]) - np.array([xmin, ymin]),
                                    np.array(self.pts[1]) - np.array([xmin, ymin])
                                ]
                                downsample = self.downsample_factor_box.value()
                                self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            else:
                                error(f"No manual polyline found for manual crack {p0}→{p1}")
                                return
                        else:
                            # Auto
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.pts_crop = [np.array(pt) - np.array([xmin, ymin]) for pt in self.pts]
                            downsample = self.downsample_factor_box.value()
                            self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            t0 = time(); self.midline_tracking(); print(f"    midline tracking time: {time()-t0:.2f}s")

                        # Build edge masks & geodesic edges for this pair
                        self.current_source = src
                        self.edge_mask()
                        self.edge_tracking()

                        # ======= Assign a brand-new crack ID for THIS pair =======
                        new_cid = _next_crack_id_str()
                        self.current_crack_id = int(new_cid)

                        # Temporarily set *pair-local* globals so save_current_segment writes them into that crack
                        self.user_points = pair_user_points
                        self.user_connections = pair_user_connections

                        # Save segment (midline + edges + mask + per-crack endpoints)
                        self.save_current_segment()

                        # Clear pair-local globals so next crack doesn't accidentally inherit them
                        self.user_points = None
                        self.user_connections = None

                    except Exception as e:
                        errors.append(f"Failed midline for {(p0, p1)}: {e}")
                        continue

            except Exception as e:
                errors.append(f"Failed for bbox {bbox_key}: {e}")
                continue

        # Done with all boxes/pairs
        if errors:
            print("\n".join(errors))
        else:
            print("✔ All endpoint groups processed.")

        # Clear UI temp state (per-run scratch)
        self.endpoint_pairs = None
        self.manual_endpoint_pairs = None

        # Persist JSON
        with open(self.ann_name, 'w') as fp:
            json.dump(self.annotation, fp)

        # Debug print & refresh view
        self._debug_print_atomic_cracks("run_pipeline END")
        self.change_image()
            
    def update_os_cost(self):
        """
        Runs the OS and cost function generation for the current image.
        This is a helper function to quickly generate the OS and cost without running the full pipeline.
        """
        try:
            self.update_image_crop()  # Ensure the crop is set correctly
            self.update_os()
            self.update_cost()
            print("OS and cost function generated successfully.")
        except Exception as e:
            error(e)
            print("Error generating OS or cost function:", e)
            
    def batch_run_pipeline(self):
        """
        Runs the pipeline (full segment generation, clearing endpoints/connections) on EVERY image in the selected folder.
        """
        from PyQt5.QtWidgets import QMessageBox
        
        # Check existence and content
        if not hasattr(self, "image_names") or not self.image_names:
            QMessageBox.warning(self.MainWindow, "Batch Run", "No images loaded. Please select a folder with images first.")
            print("Batch run aborted: no images loaded.")
            return
        
        total = len(self.image_names)
        errors = []
        n_success = 0
        orig_n = self.n

        for idx, fname in enumerate(self.image_names):
            try:
                self.n = idx
                self.change_image()
                # Only run if endpoints and connections are present
                endpoints = getattr(self, "user_points", None)
                connections = getattr(self, "user_connections", None)
                if endpoints and connections:
                    print(f"\n======= Processing image {idx+1}/{total}: {fname} =======")
                    self.run_pipeline(multirun=True)  # Will clear endpoints on success
                    n_success += 1
                    #return
                else:
                    print(f"  [SKIP] No endpoints/connections for this image.")
            except Exception as e:
                errors.append(f"Image {fname}: {e}")

        self.n = orig_n
        self.change_image()
        summary = f"Batch pipeline run complete.\nSuccessful: {n_success}/{total}\n"
        if errors:
            summary += f"\nErrors:\n" + "\n".join(errors)
        print(summary)
        QMessageBox.information(self.MainWindow, "Batch pipeline finished", summary)

    # crack_tool_v2.py  --- CrackToolsApplication.combine_segments  (REPLACE WHOLE METHOD)
    def combine_segments(self):
        """
        Combine multiple atomic cracks into one combined crack **only if** they intersect
        and the union is a single connected component.

        - Multi-select dialog w/ live highlight
        - Blocks if any selected crack has zero overlap with the others
        - Blocks if the union has >1 connected component
        - Writes combined entry: {"source":"combined","members":[...],"mask_crop","mask_bbox"}
        """
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QListWidget, QPushButton, QHBoxLayout, QMessageBox
        from PyQt5.QtGui import QImage, QPixmap
        import numpy as np, cv2

        if not hasattr(self, "annotation") or not isinstance(self.annotation, dict):
            error("No annotation data loaded.")
            return
        ann = self.annotation.setdefault("annotations", {})
        atomic_cracks = ann.setdefault("atomic_cracks", {})
        combined_cracks = ann.setdefault("combined_cracks", {})

        if not atomic_cracks:
            error("No atomic cracks to combine.")
            return

        H, W = self.original_image.shape[:2]

        # --- Helpers
        def mask_from_crack(crack):
            mc = crack.get("mask_crop"); bb = crack.get("mask_bbox")
            if mc is not None and bb is not None:
                crop = np.array(mc, dtype=np.uint8)
                x, y, w, h = [int(v) for v in bb]
                x2, y2 = min(x + w, W), min(y + h, H)
                w_eff, h_eff = max(0, x2 - x), max(0, y2 - y)
                if h_eff > 0 and w_eff > 0:
                    crop = (crop > 0).astype(np.uint8)[:h_eff, :w_eff]
                    m = np.zeros((H, W), dtype=np.uint8)
                    m[y:y+h_eff, x:x+w_eff] = crop
                    return m
            full = np.array(crack.get("mask", []), dtype=np.uint8)
            if full.size == H * W and full.shape == (H, W):
                return (full > 0).astype(np.uint8)
            return np.zeros((H, W), dtype=np.uint8)

        def endpoints_key(crack):
            up = crack.get("user_points", []) or []
            uc = crack.get("user_connections", []) or []
            if len(up) == 2 and any(list(c) == [0,1] or list(c) == [1,0] for c in uc):
                a = tuple(map(float, up[0])); b = tuple(map(float, up[1]))
                return tuple(sorted([a, b]))
            return None

        atom_ids_sorted = sorted(atomic_cracks.keys(), key=lambda s: int(s))
        labels = [f"Atomic {cid}" for cid in atom_ids_sorted]

        # --- Dialog
        dlg = QDialog(self.MainWindow); dlg.setWindowTitle("Combine Segments")
        layout = QVBoxLayout(dlg)

        listwidget = QListWidget(); listwidget.setSelectionMode(QListWidget.MultiSelection)
        for lbl in labels: listwidget.addItem(lbl)
        layout.addWidget(listwidget)

        btns = QHBoxLayout()
        btn_ok = QPushButton("Combine Selected"); btn_cancel = QPushButton("Cancel")
        btns.addWidget(btn_ok); btns.addWidget(btn_cancel); layout.addLayout(btns)
        btn_ok.clicked.connect(dlg.accept); btn_cancel.clicked.connect(dlg.reject)

        # --- Live highlight
        def highlight():
            display = self.original_image.copy()
            for i, cid in enumerate(atom_ids_sorted):
                crack = atomic_cracks[cid]
                m_full = mask_from_crack(crack)
                if np.any(m_full):
                    color = (255, 0, 0); alpha = 0.25
                    if listwidget.item(i).isSelected():
                        color = (255, 255, 0); alpha = 0.6
                    overlay = np.zeros_like(display)
                    overlay[m_full.astype(bool)] = color
                    display = cv2.addWeighted(display, 1, overlay, alpha, 0)
            im = display.astype(np.uint8)
            qimage = QImage(im, im.shape[1], im.shape[0], im.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            scaled = pixmap.scaled(self.ImageScreen.width(), self.ImageScreen.height(),
                                Qt.KeepAspectRatio, Qt.FastTransformation)
            self.ImageScreen.setPixmap(scaled)

        listwidget.itemSelectionChanged.connect(highlight); highlight()

        if dlg.exec_() != QDialog.Accepted:
            self.change_image()
            return

        selected_rows = [i.row() for i in listwidget.selectedIndexes()]
        if len(selected_rows) < 2:
            error("Select at least two atomic segments to combine.")
            self.change_image()
            return
        selected_ids = [atom_ids_sorted[i] for i in selected_rows]

        # --- Disallow duplicate endpoint-pair merges (order-insensitive)
        keys = {}
        for cid in selected_ids:
            k = endpoints_key(atomic_cracks[cid])
            if k is not None:
                if k in keys:
                    QMessageBox.critical(self.MainWindow, "Cannot Combine",
                        f"Selected segments {keys[k]} and {cid} share the same endpoints. This combine is blocked.")
                    self.change_image(); return
                keys[k] = cid

        # --- Require pairwise overlap & single connected component
        masks = {cid: mask_from_crack(atomic_cracks[cid]) for cid in selected_ids}
        union_mask = np.zeros((H, W), dtype=np.uint8)
        for m in masks.values(): union_mask |= (m > 0).astype(np.uint8)

        # (a) every selected must overlap at least one other selected
        for cid in selected_ids:
            others = np.zeros((H, W), dtype=np.uint8)
            for oid, om in masks.items():
                if oid == cid: continue
                others |= (om > 0).astype(np.uint8)
            if np.count_nonzero(masks[cid] & others) == 0:
                QMessageBox.critical(self.MainWindow, "Cannot Combine",
                    f"Selected segment {cid} does not intersect with any of the others.")
                self.change_image(); return

        # (b) union must be a single connected component
        num_labels, labels_im = cv2.connectedComponents((union_mask > 0).astype(np.uint8))
        # num_labels counts background as 1 label ⇒ components = num_labels - 1
        if num_labels - 1 > 1:
            QMessageBox.critical(self.MainWindow, "Cannot Combine",
                "The union of selected segments is not connected (multiple components).")
            self.change_image(); return

        if not np.any(union_mask):
            error("The union of the selected masks is empty — nothing to combine.")
            self.change_image(); return

        ys, xs = np.where(union_mask > 0)
        y0, y1 = int(ys.min()), int(ys.max() + 1)
        x0, x1 = int(xs.min()), int(xs.max() + 1)
        crop = union_mask[y0:y1, x0:x1].astype(np.uint8)

        # --- Allocate a new combined id
        cmb_ids = []
        for k in combined_cracks.keys():
            try: cmb_ids.append(int(k))
            except: pass
        new_cmb_id = str(max(cmb_ids) + 1 if cmb_ids else 0)

        combined_cracks[new_cmb_id] = {
            "source": "combined",
            "members": [str(c) for c in selected_ids],
            "midline": [],
            "geodesic_edges": {},
            "mask_crop": crop.tolist(),
            "mask_bbox": [int(x0), int(y0), int(x1 - x0), int(y1 - y0)]
        }

        self.save_annotation()
        self.change_image()

    # crack_tool_v2.py  --- add to class CrackToolsApplication
    def clear_combined_cracks(self):
        """
        Delete (some or all) combined cracks; atomic cracks remain untouched.
        In the dialog:
        - All combined cracks are shown in yellow by default
        - Selected ones are shown in red
        """
        from PyQt5.QtWidgets import QDialog, QVBoxLayout, QListWidget, QPushButton, QHBoxLayout
        from PyQt5.QtGui import QImage, QPixmap
        import numpy as np, cv2

        ann = self.annotation.setdefault("annotations", {})
        combined = ann.setdefault("combined_cracks", {})
        if not combined:
            error("No combined cracks to delete.")
            return

        keys_sorted = sorted(combined.keys(), key=lambda s: int(s))
        labels = []
        H, W = self.original_image.shape[:2]
        for cid in keys_sorted:
            members = combined[cid].get("members", [])
            labels.append(f"Combined {cid}  (members: {','.join(map(str, members))})")

        dlg = QDialog(self.MainWindow)
        dlg.setWindowTitle("Clear (Delete) Combined Cracks")
        layout = QVBoxLayout(dlg)
        lw = QListWidget()
        lw.setSelectionMode(QListWidget.MultiSelection)
        for lbl in labels:
            lw.addItem(lbl)
        layout.addWidget(lw)

        btns = QHBoxLayout()
        ok = QPushButton("Delete Selected")
        cancel = QPushButton("Cancel")
        btns.addWidget(ok)
        btns.addWidget(cancel)
        layout.addLayout(btns)
        ok.clicked.connect(dlg.accept)
        cancel.clicked.connect(dlg.reject)

        # Highlight function
        def highlight():
            disp = self.original_image.copy()
            for i, cid in enumerate(keys_sorted):
                mask = reconstruct_full_mask_from_crack(combined[cid], H, W)
                if not np.any(mask):
                    continue
                overlay = np.zeros_like(disp)
                if lw.item(i).isSelected():
                    overlay[mask.astype(bool)] = (255, 0, 0)  # red if selected
                    alpha = 0.6
                else:
                    overlay[mask.astype(bool)] = (255, 255, 0)  # yellow if not selected
                    alpha = 0.4
                disp = cv2.addWeighted(disp, 1, overlay, alpha, 0)
            qimage = QImage(disp, disp.shape[1], disp.shape[0], disp.strides[0], QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            self.ImageScreen.setPixmap(
                pixmap.scaled(self.ImageScreen.width(), self.ImageScreen.height(),
                            Qt.KeepAspectRatio, Qt.FastTransformation)
            )

        lw.itemSelectionChanged.connect(highlight)
        highlight()

        if dlg.exec_() == QDialog.Accepted:
            sel = [r.row() for r in lw.selectedIndexes()]
            for idx in sorted(sel, reverse=True):
                combined.pop(keys_sorted[idx], None)
            self.save_annotation()
            self.change_image()
        else:
            self.change_image()


if __name__ == "__main__":
    import sys
    import time
    app = QtWidgets.QApplication(sys.argv)
    font = QtGui.QFont()
    font.setPointSize(7)
    app.setFont(font)
    MainWindow = QtWidgets.QMainWindow()
    ui = CrackToolsApplication()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())