# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cracktools as ct
from helpers.layout import Ui_MainWindow
from helpers.metrics import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import Qt
import skimage
import numpy as np
import cv2
import matplotlib.pyplot as plt
import json
import os
from skimage.segmentation import mark_boundaries
import os
from PyQt5.QtWidgets import QListWidgetItem
from shapely import geometry, ops
import pandas as pd

from crackutils import *
from manual_drawing import *
from track_segment_pipeline import *
from helpers.crackhelpers import *
from helpers import metrics
from helpers.metrics import *
from combine_clear_segments import *
import cracktools as ct

from concurrent.futures import ProcessPoolExecutor, as_completed
import itertools, pandas as pd, os
from edge_workers import *

from rs3_split import run_rs3_variants_split
from edge_workers import *
#from crackutils import CrackUtils

from helpers.endpoint_annotator import CrackAnnotator
min_crop_size = 16   
class CrackToolsApplication(ManualDrawing, TrackSegmentPipeline, CombineClearSegments, CrackUtils, Ui_MainWindow):
    def setupUi(self, MainWindow):
        super().setupUi(MainWindow)
        
        #Select Image Tab
        self.MainWindow = MainWindow
        self.SelectFolderButton.clicked.connect(self.select_folder)
        self.PreviousImageButton.clicked.connect(self.previous_image)
        self.NextImageButton.clicked.connect(self.next_image)
        self.files_list.itemSelectionChanged.connect(self.name_selected)
        
        self.combine_segments_button.clicked.connect(self.combine_segments)
        #self.calculate_metrics_button.clicked.connect(lambda: self.run_mask_metrics(display=True))
        self.calculate_metrics_button.clicked.connect(lambda: self.run_midline_and_mask_metrics(tau_px=3.0, crack_id=None))
        self.batch_metrics_button.clicked.connect(lambda: self.batch_run_metrics_global)
        
        
        self.draw_box_button.clicked.connect(self.draw_box)
        self.save_b_button.clicked.connect(self.save_box)
        
        self.clear_boxes_button.clicked.connect(self.clear_boxes)
        self.clear_segmentation_button.clicked.connect(self.clear_segmentation)
        self.clear_combined_cracks_button.clicked.connect(self.clear_combined_cracks)




        #Tracking Tab
        self.select_points_button.clicked.connect(self.select_save_end_points)
        self.update_image_crop_button.clicked.connect(self.update_image_crop)
        self.wavelet_button.clicked.connect(self.check_wavelet)
        self.middle_point_button.clicked.connect(self.select_middle_point)
        self.middpoint_update_button.clicked.connect(self.update_midpoint_image)
        self.BatchPipelineButton.clicked.connect(self.batch_run_pipeline)
        self.update_os_button.clicked.connect(self.update_os)
        self.update_cost_button.clicked.connect(self.update_os_cost)
        self.midline_track_button.clicked.connect(self.midline_tracking)
        # self.save_current_segment_button.clicked.connect(self.save_current_segment)
        self.save_current_segment_button.hide()

        # Repurpose the OS button for full pipeline
        try:
            self.update_os_button.clicked.disconnect()
        except Exception:
            pass
        self.update_os_button.setText("Run Pipeline")
        self.update_os_button.clicked.connect(self.run_pipeline)




        #Segmentation Tab
        self.edge_mask_button.clicked.connect(self.edge_mask)
        self.edge_tracks_button.clicked.connect(self.edge_tracking)
        self.update_track_display_button.clicked.connect(self.update_track_display)
        self.track_full_screen_button.clicked.connect(self.track_full_screen)
        self.edge_tracks_full_screen_button.clicked.connect(self.edge_tracks_full_screen)
 
       
       
        
        #Add segment manually tab
        self.draw_segment_button.clicked.connect(lambda: self.draw_segment('add'))
        self.erase_segment_button.clicked.connect(self.erase_segment)
        self.reset_segment_button.clicked.connect(self.reset_canvas)
        self.save_manuall_segment_button.clicked.connect(self.save_manual_segment)
        self.manual_segment_full_screen_button.clicked.connect(self.manual_segment_full_screen)

        self.n = -1
        self.saved = False

        self.update_image_crop_button.setStyleSheet("background-color : red")
        self.middle_point_button.setStyleSheet("background-color : red")
        self.middpoint_update_button.setStyleSheet("background-color : red")
        self.update_os_button.setStyleSheet("background-color : red")
        self.update_cost_button.setStyleSheet("background-color : red")
        self.midline_track_button.setStyleSheet("background-color : red")
        self.update_track_display_button.setStyleSheet("background-color : red")
        self.track_full_screen_button.setStyleSheet("background-color : red")
        self.edge_mask_button.setStyleSheet("background-color : red")
        self.edge_tracks_button.setStyleSheet("background-color : red")
        self.edge_tracks_full_screen_button.setStyleSheet("background-color : red")
        self.save_current_segment_button.setStyleSheet("background-color : red")
        self.draw_segment_button.setStyleSheet("background-color : red")
        self.erase_segment_button.setStyleSheet("background-color : orange")
        self.reset_segment_button.setStyleSheet("background-color : lightblue")
        self.save_manuall_segment_button.setStyleSheet("background-color : lightgreen")
        
        self.show_os_button.setStyleSheet("background-color : red")
        
        #self.mask_pipeline_button.setStyleSheet("background-color : red")
        
    def run_pipeline(self, multirun=False):
        import gc, json
        import numpy as np
        from PyQt5.QtWidgets import QMessageBox
        from time import time

        # ---- helpers ---------------------------------------------------------
        def _ensure_ann():
            # make sure base structure exists
            if not hasattr(self, "annotation") or not isinstance(self.annotation, dict):
                self.annotation = {}
            ann = self.annotation.setdefault("annotations", {})
            ann.setdefault("atomic_cracks", {})
            ann.setdefault("combined_cracks", {})
            # scrub stray non-numeric keys
            bad_keys = [k for k in ann["atomic_cracks"].keys() if not str(k).isdigit()]
            for bk in bad_keys:
                ann["atomic_cracks"].pop(bk, None)
            return ann

        def _next_crack_id_str():
            """
            Return the lowest non-negative id that is NOT used in saved atomic_cracks.
            This ignores any in-memory caches so deleted ids are reused.
            """
            ann = self.annotation.get("annotations", {})
            ac = ann.get("atomic_cracks", {})
            used = sorted(int(k) for k in ac.keys() if str(k).isdigit())
            nxt = 0
            for k in used:
                if k == nxt:
                    nxt += 1
                elif k > nxt:
                    break
            return str(nxt)

        # ---- start -----------------------------------------------------------
        gc.collect()
        print("✅ GPU memory freed from CuPy pool")
        print("Running midline pipeline (auto + manual)...")

        # reset scratch between runs so ids don't leak/inflate
        self.current_crack_id = None
        self.crack_tracks = {}        # in-memory geodesic paths per id (scratch only)

        ann = _ensure_ann()
        ac_store = ann["atomic_cracks"]

        boxes = self.get_all_bounding_boxes()
        print(f"Loaded {len(boxes)} bounding boxes: {boxes}")
        if not boxes:
            QMessageBox.critical(None, "No Bounding Boxes",
                "Please draw at least one bounding box before running the pipeline.")
            return

        if not multirun:
            # Let the user pick points/connections/midlines
            self.endpoint_pairs = None
            self.user_connections = None
            self.user_points = None
            self.manual_endpoint_pairs = None
            self.all_selected_points = None  # reset before each run
            print("Calling select_end_points_manmidlines()...")
            self.select_end_points_manmidlines()

        # Merge auto + manual endpoint pairs (global, from annotator)
        all_pairs = []
        if getattr(self, "endpoint_pairs", None):
            print(f"Auto endpoint_pairs: {self.endpoint_pairs}")
            all_pairs.extend([(p, "auto") for p in self.endpoint_pairs])

        if getattr(self, "manual_endpoint_pairs", None):
            print(f"Manual endpoint_pairs: {self.manual_endpoint_pairs}")
            all_pairs.extend([(p, "manual") for p in self.manual_endpoint_pairs])

        if not all_pairs:
            QMessageBox.critical(
                None, "No Endpoint Pairs",
                "No endpoint pairs selected!\n\nPlease use 'Select Endpoints' and create at least one connection or manual midline before running the pipeline."
            )
            return

        # Group by bbox (so OS/cost is reused per box)
        box_to_pairs = {}
        for (pair, src) in all_pairs:
            candidates = []
            for bbox in boxes:
                xmin, ymin, xmax, ymax = bbox
                p0, p1 = pair
                if (xmin <= p0[0] <= xmax and ymin <= p0[1] <= ymax and
                    xmin <= p1[0] <= xmax and ymin <= p1[1] <= ymax):
                    area = abs((xmax - xmin) * (ymax - ymin))
                    candidates.append((area, bbox))
            if candidates:
                _, chosen_bbox = min(candidates, key=lambda x: x[0])
                key = tuple(chosen_bbox)
                box_to_pairs.setdefault(key, []).append((pair, src))

        errors = []

        # Make sure we don't blow away memory of previous masks
        if not hasattr(self, "mask"):
            self.mask = []

        for bbox_key, pairs in box_to_pairs.items():
            xmin, ymin, xmax, ymax = bbox_key
            print(f"\n=== Processing bbox {bbox_key} ===")
            print(f"Pairs in this box: {pairs}")

            try:
                # Precompute OS/cost once per box for auto pairs
                auto_pairs = [p for p, s in pairs if s == "auto"]
                if auto_pairs:
                    first_pair = auto_pairs[0]
                    print(f"Precomputing OS/cost for auto pair {first_pair}")
                    self.pts = [np.array(first_pair[0]), np.array(first_pair[1])]
                    self.end_points = self.pts
                    self.active_bbox = list(bbox_key)
                    self.update_image_crop()
                    if getattr(self, "skip_current_segment", False):
                        continue
                    print("os (once per box)")
                    t0 = time(); self.update_os(); print(f"os time: {time()-t0:.2f}s")
                    print("cost (once per box)")
                    t0 = time(); self.update_cost(); print(f"cost time: {time()-t0:.2f}s")

                # Process each pair -> one atomic crack per pair
                for (p0, p1), src in pairs:
                    try:
                        self.active_bbox = list(bbox_key)
                        print(f"\n--- Processing pair {(p0, p1)} (source={src}) ---")

                        # Per-crack, pair-local endpoints for saving
                        pair_user_points = [tuple(p0), tuple(p1)]
                        pair_user_connections = [[0, 1]]  # exactly one connection per crack

                        if src in ("manual", "manual_poly"):
                            # For manual, we reuse the drawn polyline as midline (full-image coords)
                            manual_midlines_dict = getattr(self, "manual_midlines_tmp", {})
                            found_key = None

                            # Durable copy of selection points from earlier
                            all_points = getattr(self, "all_selected_points", None)
                            if all_points is None:
                                all_points = getattr(self, "user_points", [])

                            print("\n[DEBUG] --- Matching manual midline ---")
                            print(f"[DEBUG] manual_midlines_tmp keys at runtime: {list(manual_midlines_dict.keys())}")
                            print(f"[DEBUG] all_points at runtime: {all_points}")
                            print(f"[DEBUG] Trying to match p0={p0}  p1={p1}")

                            # manual_midlines_tmp keys are "i_j" from annotator indices; match geometrically
                            for k, poly in manual_midlines_dict.items():
                                try:
                                    i1, i2 = map(int, k.split("_"))
                                    c_i = tuple(all_points[i1])
                                    c_j = tuple(all_points[i2])
                                    print(f"[DEBUG] Checking key={k}, c_i={c_i}, c_j={c_j}")
                                    if (c_i, c_j) == (p0, p1) or (c_i, c_j) == (p1, p0):
                                        print(f"[DEBUG] Found match for key={k}")
                                        found_key = k
                                        break
                                except Exception as e:
                                    print(f"[DEBUG] Error parsing key={k}: {e}")

                            print(f"[MANUAL] Found key: {found_key}")
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.update_image_crop()
                            if getattr(self, "skip_current_segment", False):
                                continue

                            if found_key:
                                # Convert full-image manual polyline to crop coords and set as self.track
                                poly = np.array(manual_midlines_dict[found_key], dtype=float)  # [[x,y],...]
                                cy = poly[:, 1] - ymin
                                cx = poly[:, 0] - xmin
                                self.track = np.vstack([cy, cx])
                                self.pts_crop = [
                                    np.array(self.pts[0]) - np.array([xmin, ymin]),
                                    np.array(self.pts[1]) - np.array([xmin, ymin])
                                ]
                                downsample = self.downsample_factor_box.value()
                                self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            else:
                                msg = f"No manual polyline found for manual crack {p0}→{p1}"
                                print("ERROR:", msg)
                                errors.append(msg)
                                continue
                        else:
                            # Auto mode
                            self.pts = [np.array(p0), np.array(p1)]
                            self.end_points = self.pts
                            self.pts_crop = [np.array(pt) - np.array([xmin, ymin]) for pt in self.pts]
                            downsample = self.downsample_factor_box.value()
                            self.pts_crop_down = [p / downsample for p in self.pts_crop]
                            t0 = time(); self.midline_tracking(); print(f"    midline tracking time: {time()-t0:.2f}s")

                            # --- normalize track like generate_auto_variant_for_manual ---
                            if getattr(self, "track", None) is not None:
                                try:
                                    tr = np.asarray(self.track, float)
                                    if tr.shape[0] == 2:
                                        track_xy = tr.T
                                    else:
                                        track_xy = tr

                                    p0g = np.asarray(p0, float)
                                    p1g = np.asarray(p1, float)

                                    # reverse if needed (ensure start = p0)
                                    d_start_p0 = np.linalg.norm(track_xy[0] - p0g)
                                    d_start_p1 = np.linalg.norm(track_xy[0] - p1g)
                                    if d_start_p1 < d_start_p0:
                                        track_xy = track_xy[::-1]
                                        print(f"[PIPE ALIGN] reversed path so first sample anchors at p0 (d_start_p0={d_start_p0:.2f}, d_start_p1={d_start_p1:.2f})")
                                    else:
                                        print(f"[PIPE ALIGN] path already starts near p0 (d_start_p0={d_start_p0:.2f}, d_start_p1={d_start_p1:.2f})")

                                    # translate so first point == p0
                                    delta = p0g - track_xy[0]
                                    track_xy = track_xy + delta

                                    # convert to local coords (crop relative)
                                    xmin, ymin, xmax, ymax = bbox_key
                                    track_local = track_xy - np.array([xmin, ymin])
                                    track_local[:,0] = np.clip(track_local[:,0], 0, xmax - xmin - 1)
                                    track_local[:,1] = np.clip(track_local[:,1], 0, ymax - ymin - 1)
                                    self.track = track_local.T

                                    print(f"[PIPE ALIGN] normalized track: start Δ={np.linalg.norm(track_local[0] - (p0g - np.array([xmin, ymin]))):.2f}px")
                                except Exception as e:
                                    print(f"[PIPE ALIGN] ⚠ failed to normalize: {e}")
                        
                        # ======= Assign a brand-new crack ID for THIS pair (gap-free) =======
                        new_cid = _next_crack_id_str()
                        self.current_crack_id = int(new_cid)

                        # Geodesic edges & masks for this pair
                        self.current_source = src
                        self.edge_mask()
                        self.edge_tracking()

                        # Pair-local globals so save_current_segment writes them into that crack
                        self.user_points = pair_user_points
                        self.user_connections = pair_user_connections

                        # Save segment (midline + edges + mask + per-crack endpoints)
                        self.save_current_segment()

                        # Clear pair-local globals so next crack doesn't inherit them
                        self.user_points = None
                        self.user_connections = None

                    except Exception as e:
                        errors.append(f"Failed midline for {(p0, p1)}: {e}")
                        continue

            except Exception as e:
                errors.append(f"Failed for bbox {bbox_key}: {e}")
                continue

        # Done with all boxes/pairs
        if errors:
            print("\n".join(errors))
        else:
            print("✔ All endpoint groups processed.")

        # Clear UI temp state (per-run scratch)
        self.endpoint_pairs = None
        self.manual_endpoint_pairs = None

        # Persist JSON
        with open(self.ann_name, 'w') as fp:
            json.dump(self.annotation, fp)
            
        self.auto_combine_segments()

        # Debug print & refresh view
        self._debug_print_atomic_cracks("run_pipeline END")
        self.change_image()
            
    #TODO: actually implement this
    def batch_run_pipeline(self):
        """
        Runs the pipeline (full segment generation, clearing endpoints/connections) on EVERY image in the selected folder.
        """
        from PyQt5.QtWidgets import QMessageBox
        
        # Check existence and content
        if not hasattr(self, "image_names") or not self.image_names:
            QMessageBox.warning(self.MainWindow, "Batch Run", "No images loaded. Please select a folder with images first.")
            print("Batch run aborted: no images loaded.")
            return
        
        total = len(self.image_names)
        errors = []
        n_success = 0
        orig_n = self.n

        for idx, fname in enumerate(self.image_names):
            try:
                self.n = idx
                self.change_image()
                # Only run if endpoints and connections are present
                endpoints = getattr(self, "user_points", None)
                connections = getattr(self, "user_connections", None)
                if endpoints and connections:
                    print(f"\n======= Processing image {idx+1}/{total}: {fname} =======")
                    self.run_pipeline(multirun=True)  # Will clear endpoints on success
                    n_success += 1
                    #return
                else:
                    print(f"  [SKIP] No endpoints/connections for this image.")
            except Exception as e:
                errors.append(f"Image {fname}: {e}")

        self.n = orig_n
        self.change_image()
        summary = f"Batch pipeline run complete.\nSuccessful: {n_success}/{total}\n"
        if errors:
            summary += f"\nErrors:\n" + "\n".join(errors)
        print(summary)
        QMessageBox.information(self.MainWindow, "Batch pipeline finished", summary)
  
    ###################################################################
    ##    METRICS FUNCTIONS
    ###################################################################
    
    '''def run_mask_metrics(self, display=True, save_edges_json=False):
        """
        1) Mask IoU/F1/precision/recall for current image.
        2) Delegates crack width/normal comparison to compare_widths_for_cracks().
        """
        import os, numpy as np, pandas as pd

        # ---- guards
        if not hasattr(self, "image") or self.image is None:
            print("⚠️ No image loaded — skipping mask metrics."); return
        if not hasattr(self, "annotation") or not self.annotation:
            print("⚠️ No annotation loaded — skipping mask metrics."); return
        if not hasattr(self, "current_mask") or self.current_mask is None:
            print("⚠️ No ground truth mask available — skipping mask metrics."); return

        ann = self.annotation.get("annotations", {})
        H, W = self.image.shape[:2]

        # ---- 1) image-level mask metrics
        pred_mask = build_combined_mask(ann.get("atomic_cracks", {}), H, W)
        metrics = self.compute_mask_metrics(self.current_mask, pred_mask)

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        metrics_dir = os.path.join(self.save_folder, "metrics")
        os.makedirs(metrics_dir, exist_ok=True)

        mask_csv_path = os.path.join(metrics_dir, "mask_metrics.csv")
        row = {"image": base_name, **metrics}
        if os.path.exists(mask_csv_path):
            df = pd.read_csv(mask_csv_path)
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
        else:
            df = pd.DataFrame([row])
        df.to_csv(mask_csv_path, index=False)

        vis_path = os.path.join(metrics_dir, base_name + "_iou_overlay.png")
        #self.save_mask_comparison_plot(self.current_mask, pred_mask, vis_path, show=display)

        # ---- 2) per-crack width comparison
        summary_csv = os.path.join(metrics_dir, "width_metrics.csv")
        diffs_csv   = os.path.join(metrics_dir, "width_diffs.csv")

        width_rows, diffs_rows = self.compare_widths_for_cracks(
            ann, self.current_mask, base_name, metrics_dir,
            display=display
        )

        # save summary
        if width_rows:
            dfw = pd.DataFrame(width_rows)
            if os.path.exists(summary_csv):
                dfw_old = pd.read_csv(summary_csv)
                dfw = pd.concat([dfw_old, dfw], ignore_index=True)
            dfw.to_csv(summary_csv, index=False)

        # save diffs
        if diffs_rows:
            dfd = pd.DataFrame(diffs_rows)
            if os.path.exists(diffs_csv):
                dfd_old = pd.read_csv(diffs_csv)
                dfd = pd.concat([dfd_old, dfd], ignore_index=True)
            dfd.to_csv(diffs_csv, index=False)

        print(f"✅ Saved metrics → {mask_csv_path}, {summary_csv}, {diffs_csv}")'''
                
    '''def batch_run_metrics(
        self,
        sample_frac=0.20,            # take ~20% of images
        max_images=10,               # cap for sanity
        seed=0,
        edge_grid=None,              # None → default grid (below)
        g_variants=None,             # None → default RS3 grid already inside generate_auto_variants...
        cpu_max_workers=8
    ):
        """
        1) Randomly sample a subset of images.
        2) For each image: for each *manual* subcrack:
            - run edge param sweep (edge_mask/edge_tracking), pick 'best' params,
            - run RS3 g-variants with those fixed edge params,
            - save per-variant metrics + overlay of all autos vs manual,
            - compute mask IoU + width diffs for the image.
        3) Build dataset summary CSVs + compact plots.
        """
        import numpy as np, random, os, pandas as pd

        if not getattr(self, "image_names", []):
            print("[batch-metrics] no images loaded"); return

        rng = random.Random(seed)
        idxs = list(range(len(self.image_names)))
        rng.shuffle(idxs)
        k = max(1, int(len(idxs) * float(sample_frac)))
        idxs = idxs[:min(k, max_images)]

        if edge_grid is None:
            edge_grid = {
                "window_half_size": [35, 45, 55],
                "mu": [0, 5],
                "l":  [2, 5],
                "p":  [6, 14],
            }

        results_summary = []

        orig_n = self.n
        try:
            for t, i in enumerate(idxs, 1):
                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [batch-metrics] {t}/{len(idxs)}: {base_name} ======")

                # per-image metrics dir (will also hold per-crack subfolders)
                metrics_dir = os.path.join(self.save_folder, "metrics", base_name)
                os.makedirs(metrics_dir, exist_ok=True)

                # iterate manual atomics
                ann = self.annotation.get("annotations", {})
                atomic = ann.get("atomic_cracks", {}) or {}

                for cid, crack in atomic.items():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    man_xy = metrics._finite_xy(crack.get("midline", []))
                    if len(man_xy) < 2: 
                        continue

                    # 1) Edge param sweep for this subcrack → pick best
                    df_sweep = self.sweep_edges_with_executor(cid, grid=edge_grid, max_workers=cpu_max_workers)
                    if df_sweep is None or df_sweep.empty:
                        print(f"[batch-metrics] sweep empty for cid={cid}")
                        continue

                    # rank sweep (smaller chamfer/hausdorff, larger coverage)
                    rank = df_sweep.sort_values(["chamfer_mean","hausdorff","coverage"],
                                                ascending=[True,True,False]).head(1)
                    best_edge = dict(
                        window_half_size = int(rank.iloc[0]["param_window_half_size"]),
                        mu = float(rank.iloc[0]["param_mu"]),
                        l  = int(rank.iloc[0]["param_l"]),
                        p  = int(rank.iloc[0]["param_p"]),
                    )
                    # store sweep
                    crack_dir = os.path.join(metrics_dir, f"cid{cid}")
                    os.makedirs(crack_dir, exist_ok=True)
                    df_sweep.to_csv(os.path.join(crack_dir, "edge_sweep.csv"), index=False)

                    # 2) RS3 variants with these fixed edge params (+ overlay of ALL autos)
                    pack = self.generate_auto_variants_for_manual_parallel(
                        cid,
                        g_variants=g_variants,
                        edge_params_fixed=best_edge,
                        cpu_max_workers=cpu_max_workers,
                        force_recompute=True
                    )

                # 3) Per-image mask+width metrics + plots
                per_image = self.compute_mask_and_width_metrics_for_image(display=False)
                results_summary.append({"image": base_name, **per_image.get("mask_means", {}), **per_image.get("width_means", {})})

            # 4) Dataset summary + plots
            self.summarize_dataset_metrics()

            # Write high-level summary CSV
            if results_summary:
                out = os.path.join(self.save_folder, "metrics", "_summary", "per_image_means.csv")
                pd.DataFrame(results_summary).to_csv(out, index=False)
                print(f"[batch-metrics] wrote → {out}")

            print("[batch-metrics] ✅ done")

        finally:
            self.n = orig_n
            self.change_image()'''
       
    '''def run_midline_and_mask_metrics(self, tau_px=3.0, crack_id=None, display=True, do_param_sweep=True):
        """
        Per-image metrics driver:
        - (optional) edge param sweep per manual subcrack → best edge params
        - RS3 auto variants with those params (or fixed defaults)
        - save per-variant CSV + overlays (all autos vs manual) under metrics/<image>/cid<id>/
        - compute midline metrics for manual vs best-auto → metrics/<image>/midline_metrics.csv
        - compute mask IoU + width diffs (plots + CSVs) → metrics/<image>/
        """
        import os, numpy as np, pandas as pd, cv2
        from crackutils import CrackUtils

        if not getattr(self, "annotation", None):
            print("⚠️ No annotation loaded"); return
        if getattr(self, "original_image", None) is None:
            print("⚠️ No image loaded"); return

        ann_all = self.annotation.setdefault("annotations", {})
        atomic = ann_all.setdefault("atomic_cracks", {})

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        image_metrics_dir = os.path.join(self.save_folder, "metrics", base_name)
        os.makedirs(image_metrics_dir, exist_ok=True)

        print(f"\n[metrics] Running full metrics for {base_name}")

        # default edge params if sweep is disabled or fails
        fixed_edge_default = {"window_half_size": 45, "mu": 0, "l": 5, "p": 14}

        midline_rows = []

        # iterate manual subcracks (optionally filter one id)
        for cid, crack in atomic.items():
            if (crack_id is not None) and (cid != str(crack_id)):
                continue
            src = (crack.get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue

            man_xy = metrics._finite_xy(crack.get("midline", []))
            if len(man_xy) < 2:
                continue

            # per-crack folder
            crack_dir = os.path.join(image_metrics_dir, f"cid{cid}")
            os.makedirs(crack_dir, exist_ok=True)

            # ---- 1) (optional) edge sweep to pick best edge params for this subcrack
            best_edge = dict(fixed_edge_default)
            if do_param_sweep:
                try:
                    df_sweep = self.sweep_edges_with_executor(
                        cid,
                        grid={
                            "window_half_size": [35, 45, 55],
                            "mu": [0, 5],
                            "l":  [2, 5],
                            "p":  [6, 14],
                        },
                        max_workers=8
                    )
                    if df_sweep is not None and not df_sweep.empty:
                        df_sweep.to_csv(os.path.join(crack_dir, "edge_sweep.csv"), index=False)
                        rank = df_sweep.sort_values(
                            ["chamfer_mean", "hausdorff", "coverage"],
                            ascending=[True, True, False]
                        ).head(1)
                        best_edge = {
                            "window_half_size": int(rank.iloc[0]["param_window_half_size"]),
                            "mu": float(rank.iloc[0]["param_mu"]),
                            "l":  int(rank.iloc[0]["param_l"]),
                            "p":  int(rank.iloc[0]["param_p"]),
                        }
                        print(f"[metrics] cid={cid} best edge params = {best_edge}")
                    else:
                        print(f"[metrics] cid={cid} sweep empty → using defaults {best_edge}")
                except Exception as e:
                    print(f"[metrics] cid={cid} sweep failed → using defaults {best_edge}. Error: {e}")

            # ---- 2) RS3 variants (with chosen edge params). Saves overlays + per-variant CSVs internally.
            pack = self.generate_auto_variants_for_manual_parallel(
                cid,
                edge_params_fixed=best_edge,
                cpu_max_workers=8,
                force_recompute=True
            )
            if not pack:
                print(f"[metrics] cid={cid} no variants produced")
                continue

            # ---- 3) Midline metrics: manual vs BEST auto variant
            try:
                bid = pack.get("best_variant_id", None)
                if bid is None:
                    print(f"[metrics] cid={cid} has no best_variant_id, skipping midline metrics")
                else:
                    v = pack["variants"].get(f"v{bid}", {})
                    auto_xy = metrics._finite_xy(v.get("midline", []))
                    if len(auto_xy) >= 2:
                        mm = metrics.compute_midline_metrics(auto_xy, man_xy, tau=tau_px)
                        mm.update({"image": base_name, "crack_id": cid, "best_variant_id": bid})
                        midline_rows.append(mm)

                        # quick console sanity
                        n = min(len(man_xy), len(auto_xy))
                        start_d = float(np.linalg.norm(man_xy[0]  - auto_xy[0])) if n>0 else np.nan
                        end_d   = float(np.linalg.norm(man_xy[-1] - auto_xy[-1])) if n>0 else np.nan
                        print(f"[metrics cid={cid}] startΔ={start_d:.2f} endΔ={end_d:.2f} "
                            f"chamfer={mm.get('chamfer_mean', np.nan):.2f}")
                    else:
                        print(f"[metrics] cid={cid} best variant has no midline points")
            except Exception as e:
                print(f"[metrics] cid={cid} midline metrics failed: {e}")

        # ---- 4) Save per-image midline metrics CSV (manual vs best auto)
        if midline_rows:
            pd.DataFrame(midline_rows).to_csv(
                os.path.join(image_metrics_dir, "midline_metrics.csv"), index=False
            )

        # ---- 5) Mask IoU + width diffs (plots + CSVs) for this image
        try:
            self.compute_mask_and_width_metrics_for_image(display=display)
        except Exception as e:
            print(f"[metrics] mask/width stage failed: {e}")

        print("[metrics] done")
        self.change_image()'''
        
    
        
    def generate_auto_manual_midline(self, crack_id, cache_key=None, display=False):
        """
        Recreate the 'all autos vs manual' overlay from cached variants,
        useful if you disabled recompute or just want the plot.
        """
        import os, numpy as np, cv2, matplotlib.pyplot as plt
        from crackutils import CrackUtils

        ann = self.annotation.get("annotations", {}).get("atomic_cracks", {})
        crack = ann.get(str(crack_id))
        if not crack:
            print(f"[plot] crack {crack_id} not found"); return

        cache_key = cache_key or metrics._auto_cache_key(self)
        pack = crack.get("variants", {}).get("auto", {}).get(cache_key)
        if not pack:
            print(f"[plot] no cached variants under key={cache_key}"); return

        x, y, w, h = map(int, crack["mask_bbox"])
        self.active_bbox = [x, y, x+w, y+h]
        self.update_image_crop()
        crop_rgb = self.image_crop.copy()
        if crop_rgb.ndim == 2:
            crop_rgb = cv2.cvtColor(crop_rgb, cv2.COLOR_GRAY2BGR)

        man_xy = np.asarray(crack.get("midline", []), float)
        man_xy_crop = np.column_stack([man_xy[:,0]-x, man_xy[:,1]-y]) if len(man_xy)>=2 else np.empty((0,2))

        # plot
        plt.figure(figsize=(6,6))
        plt.imshow(cv2.cvtColor(crop_rgb, cv2.COLOR_BGR2RGB))
        if len(man_xy_crop) >= 2:
            plt.plot(man_xy_crop[:,0], man_xy_crop[:,1], 'k-', lw=4, label="manual")
            plt.plot(man_xy_crop[:,0], man_xy_crop[:,1], 'w-', lw=2)

        colors = plt.cm.tab20.colors
        for i,(k,v) in enumerate(sorted(pack["variants"].items())):
            auto = np.asarray(v.get("midline", []), float)
            if len(auto) < 2: continue
            auto_crop = np.column_stack([auto[:,0]-x, auto[:,1]-y])
            plt.plot(auto_crop[:,0], auto_crop[:,1], '-', lw=2, color=colors[i%len(colors)], label=k)

        plt.legend(ncol=2, fontsize=8)
        plt.axis("equal"); plt.tight_layout()
        out_dir = os.path.join(self.save_folder, "metrics", os.path.splitext(os.path.basename(self.name))[0], f"cid{crack_id}")
        os.makedirs(out_dir, exist_ok=True)
        out_png = os.path.join(out_dir, "midlines_overlay_legend_replot.png")
        plt.savefig(out_png, dpi=180)
        if display: plt.show()
        else: plt.close()
        print(f"[plot] saved → {out_png}")

    

    def extract_edge_inputs_for_subcrack(self, crack_id, color_channel=None):
        """
        Faithfully reconstructs the context that run_pipeline + edge_mask would have set
        for a manual crack, so edge_param_worker sees exactly the same inputs.
        Automatically reverses midline if needed to align with p0→p1.
        """
        import numpy as np
        ann = self.annotation["annotations"]["atomic_cracks"][crack_id]
        x, y, w, h = map(int, ann["mask_bbox"])
        self.active_bbox = [x, y, x + w, y + h]

        # Determine color channel
        if color_channel is None:
            color_channel = (
                0 if self.edge_track_color_box.currentText() == "R"
                else 1 if self.edge_track_color_box.currentText() == "B"
                else 2
            )

        # --- use manual midline directly ---
        man_xy_g = metrics._finite_xy(ann["midline"])
        if len(man_xy_g) < 2:
            print(f"[extract_edge_inputs_for_subcrack] ⚠ no valid manual midline for {crack_id}")
            return None

        # --- define endpoints exactly like run_pipeline ---
        self.pts = [np.array(man_xy_g[0]), np.array(man_xy_g[-1])]
        self.end_points = self.pts

        # --- now run the real crop creation ---
        self.update_image_crop()
        if getattr(self, "skip_current_segment", False):
            return None

        # --- compute local track in [y,x] form consistent with edge_mask ---
        track_local_yx = np.vstack([
            man_xy_g[:, 1] - y,  # y
            man_xy_g[:, 0] - x   # x
        ])

        # --- Flip if start/end order mismatched (ensure start = p0) ---
        # Convert [y,x] → [x,y] for comparison with pts_crop
        start_xy = track_local_yx[:, 0][::-1]
        end_xy = track_local_yx[:, -1][::-1]
        d_start_p0 = np.linalg.norm(start_xy - self.pts_crop[0])
        d_start_p1 = np.linalg.norm(start_xy - self.pts_crop[1])
        if d_start_p1 < d_start_p0:
            print(f"[extract_edge_inputs_for_subcrack] Reversing midline for crack {crack_id}")
            track_local_yx = track_local_yx[:, ::-1]

        # --- optional manual normals (crop coords) ---
        man_normals_crop = None
        if "normal_edge_points_full" in ann:
            e1 = np.asarray(ann["normal_edge_points_full"]["edge1"], float)
            e2 = np.asarray(ann["normal_edge_points_full"]["edge2"], float)
            e1c = np.column_stack([e1[:, 0] - x, e1[:, 1] - y])
            e2c = np.column_stack([e2[:, 0] - x, e2[:, 1] - y])
            man_normals_crop = [[e1c[:, 0], e1c[:, 1]], [e2c[:, 0], e2c[:, 1]]]

        # --- extract grayscale crop ---
        gray = self.image_crop[:, :, color_channel].astype(np.float32)

        # --- return payload identical in shape to edge_mask() context ---
        return dict(
            image_crop_gray=gray,
            pts_crop=self.pts_crop,
            adjusted_track=track_local_yx,
            manual_midline_global=man_xy_g,
            auto_midline_global=None,
            bbox=(x, y, w, h),
            manual_normals_crop=man_normals_crop,
        )

    def debug_edge_sweep_once(self, crack_id=None, max_workers=8):
        """
        Convenience wrapper: pick first manual crack if none given, run sweep, save CSV.
        """
        import os
        ann = self.annotation["annotations"]["atomic_cracks"]
        if crack_id is None:
            # pick the first manual parent
            for cid, ck in ann.items():
                src = (ck.get("source") or "").lower()
                if not src.startswith("auto") and src != "combined":
                    crack_id = cid
                    break
        if crack_id is None:
            print("[edge-sweep] no manual crack found")
            return

        df = self.sweep_edges_with_executor(crack_id, max_workers=max_workers)
        out_dir = os.path.join(self.save_folder, "metrics")
        os.makedirs(out_dir, exist_ok=True)
        out_csv = os.path.join(out_dir, f"edge_sweep_cid{crack_id}.csv")
        df.to_csv(out_csv, index=False)
        print(f"[edge-sweep] wrote → {out_csv}")
        
    def summarize_dataset_metrics(self):
        """
        Walk metrics/*/* CSVs and produce overall means + a few compact plots.
        """
        import os, glob, pandas as pd, matplotlib.pyplot as plt

        root = os.path.join(self.save_folder, "metrics")
        if not os.path.isdir(root): 
            print("[summarize] no metrics directory yet"); return

        # collect mask_metrics + width_metrics
        mask_csvs  = glob.glob(os.path.join(root, "*", "mask_metrics.csv"))
        width_csvs = glob.glob(os.path.join(root, "*", "width_metrics.csv"))

        out_dir = os.path.join(root, "_summary"); os.makedirs(out_dir, exist_ok=True)

        # --- mask
        if mask_csvs:
            dfm = pd.concat([pd.read_csv(p) for p in mask_csvs], ignore_index=True)
            dfm.to_csv(os.path.join(out_dir, "mask_metrics_all.csv"), index=False)
            m = dfm.mean(numeric_only=True)

            # bar plot for IoU means
            plt.figure(figsize=(4,3))
            vals = [m.get("iou_manual_vs_gt", float("nan")), m.get("iou_auto_vs_gt", float("nan"))]
            plt.bar(["manual_vs_gt","auto_vs_gt"], vals)
            plt.ylim(0,1); plt.ylabel("IoU")
            plt.title("Mean Mask IoU (dataset)")
            plt.tight_layout(); plt.savefig(os.path.join(out_dir, "mask_iou_means.png"), dpi=160); plt.close()

        # --- width
        if width_csvs:
            dfw = pd.concat([pd.read_csv(p) for p in width_csvs], ignore_index=True)
            dfw.to_csv(os.path.join(out_dir, "width_metrics_all.csv"), index=False)
            m = dfw.mean(numeric_only=True)

            # compact bar plot
            keep = ["width_diff_mae","width_diff_rmse","width_diff_mean","width_diff_std"]
            present = [k for k in keep if k in dfw.columns]
            plt.figure(figsize=(5,3))
            plt.bar(present, [m[k] for k in present])
            plt.xticks(rotation=20)
            plt.title("Mean width differences (edge - mask)")
            plt.tight_layout(); plt.savefig(os.path.join(out_dir, "width_means.png"), dpi=160); plt.close()

        print(f"[summarize] wrote summaries → {out_dir}")
    
    def sweep_edges_with_executor(self, crack_id, grid=None, max_workers=8):
        """
        Run a small CPU param sweep on edge_mask/edge_tracking for one sub-crack.
        Returns a DataFrame and also prints a short summary.
        """
        from edge_workers import edge_param_worker  # top-level worker module
        base = self.extract_edge_inputs_for_subcrack(crack_id)
        if base is None:
            print("[sweep] could not prep payload base")
            return pd.DataFrame()

        if grid is None:
            '''grid = {
                "window_half_size": [12, 20, 28],
                "mu": [3, 5],
                "l":  [2, 3],
                "p":  [6],           # fix first pass
            }'''
            grid = {
                "window_half_size": [35, 50],   # centered at 45 (≈ 90/2)
                "mu": [0, 5],                        # include your 0 and the robust 5
                "l":  [1, 2, 5],                     # include 5 per your fixed choice
                "p":  [6, 14],                   # new=6, old=12, your 14
            }

        keys = list(grid.keys())
        combos = list(itertools.product(*[grid[k] for k in keys]))

        rows = []
        with ProcessPoolExecutor(max_workers=max_workers) as ex:
            futs = []
            for c in combos:
                params = {k:v for k,v in zip(keys, c)}
                payload = dict(base)          # shallow copy ok; arrays are read-only
                payload["params"] = params
                futs.append(ex.submit(edge_param_worker, payload))

            for fut in as_completed(futs):
                try:
                    rows.append(fut.result())
                except Exception as e:
                    print("[sweep] worker failed:", e)

        df = pd.DataFrame(rows)

        # --- normalize column names (important!) ---
        if not df.empty:
            rename_map = {
                k: f"param_{k}"
                for k in ["window_half_size", "mu", "l", "p"]
                if k in df.columns
            }
            df.rename(columns=rename_map, inplace=True)

            # quick peek
            keep = [
                "param_window_half_size", "param_mu", "param_l", "param_p",
                "chamfer_mean", "hausdorff", "angle_err_deg", "coverage",
                "directional_bias", "curvature_rms_ratio", "local_thickness_corr"
            ]
            existing = [c for c in keep if c in df.columns]
            print(df[existing].sort_values(["chamfer_mean", "hausdorff"]).head(8))

        return df
    
    def generate_auto_variants_for_manual_parallel(
        self,
        crack_id,
        g_variants=None,
        cache_key=None,
        force_recompute=True,
        cpu_max_workers=None,
        color_channel=None,
        edge_params_fixed=None,   # if None → default (w=45, μ=0, l=5, p=14)
    ):
        import os, numpy as np, pandas as pd, cv2, traceback
        from crackutils import CrackUtils
        from rs3_split import run_rs3_variants_split, _variant_desc, plot_midlines_overlay_all
        from edge_workers import edge_param_worker

        # ---- look up manual crack + cache bucket ----
        ann = self.annotation.setdefault("annotations", {})
        atomic = ann.setdefault("atomic_cracks", {})
        crack = atomic.get(crack_id)
        if not crack:
            print(f"[AUTO {crack_id}] ❌ not found"); return None
        src = (crack.get("source") or "").lower()
        if src.startswith("auto") or src == "combined":
            print(f"[AUTO {crack_id}] skip non-manual"); return None

        cache_key = cache_key or metrics._auto_cache_key(self)
        variants_root = crack.setdefault("variants", {}).setdefault("auto", {})
        if cache_key in variants_root and not force_recompute:
            print(f"[AUTO {crack_id}] using cached {cache_key}")
            return variants_root[cache_key]

        # ---- bbox & endpoints ----
        bb = crack.get("mask_bbox")
        if not bb or len(bb) != 4:
            print(f"[AUTO {crack_id}] no bbox"); return None
        x, y, w, h = map(int, bb)
        xmin, ymin, xmax, ymax = x, y, x + w, y + h

        man_xy_g = metrics._finite_xy(crack.get("midline", []))
        if len(man_xy_g) >= 2:
            p0, p1 = np.array(man_xy_g[0], float), np.array(man_xy_g[-1], float)
        else:
            up = crack.get("user_points", [])
            if not up or len(up) < 2:
                print(f"[AUTO {crack_id}] missing endpoints"); return None
            p0, p1 = np.array(up[0], float), np.array(up[-1], float)

        self.active_bbox = [xmin, ymin, xmax, ymax]
        self.pts = [p0.copy(), p1.copy()]
        self.end_points = self.pts

        # ---- OS/Cost once (GPU path) ----
        try:
            self.update_image_crop()
            self.update_os()
            self.update_cost()
            os_cost = self.costFunction
        except Exception as e:
            traceback.print_exc()
            print(f"[AUTO {crack_id}] ❌ OS/COST stage failed: {e}")
            return None

        down = self.downsample_factor_box.value() if hasattr(self, "downsample_factor_box") else getattr(self, "down", 1) or 1
        p0_down_xy = np.asarray(self.pts_crop_down[0], float)
        p1_down_xy = np.asarray(self.pts_crop_down[1], float)

        # ---- g-variants to try ----
        if g_variants is None:
            vals = (20, 25, 30, 40, 50, 70)
            g_variants = [{"g11": 1.0, "g22": v, "g33": v} for v in vals]
            g_variants += [{"g11": 1.0, "g22": 25, "g33": 35}, {"g11": 1.0, "g22": 35, "g33": 25}]

        # ---- run RS3 in split mode (CPU parallel) ----
        fm_results = run_rs3_variants_split(
            ct=__import__('cracktools'),
            os_cost=os_cost,
            p0_down_xy=p0_down_xy,
            p1_down_xy=p1_down_xy,
            g_variants=g_variants,
            down=int(down),
            bbox_xyxy=[xmin, ymin, xmax, ymax],
            cpu_max_workers=cpu_max_workers or min(os.cpu_count() or 8, 16),
            mp_start_method="spawn",
        )

        # ---- edge worker base payload ----
        if color_channel is None:
            color_channel = (0 if self.edge_track_color_box.currentText() == "R"
                            else 1 if self.edge_track_color_box.currentText() == "B"
                            else 2)
        gray = self.image_crop[:, :, color_channel].astype(np.float32)
        pts_crop = self.pts_crop
        if edge_params_fixed is None:
            edge_params_fixed = {"window_half_size": 45, "mu": 0, "l": 5, "p": 14}

        base_payload = dict(
            image_crop_gray=gray,
            pts_crop=pts_crop,
            manual_midline_global=man_xy_g,
            auto_midline_global=None,
            bbox=(x, y, w, h),
            manual_normals_crop=None,
            params=edge_params_fixed,
        )

        image_name = os.path.splitext(os.path.basename(self.name))[0]
        crack_dir  = os.path.join(self.save_folder, "metrics", image_name, f"cid{crack_id}")
        os.makedirs(crack_dir, exist_ok=True)

        variants_out, metrics_rows = {}, {}
        # also keep crop-local midlines for plotting
        var_local_xy_by_id = {}
        variant_labels_by_id = {}

        # manual (crop coords) for plotting
        man_xy_crop = None
        if len(man_xy_g) >= 2:
            mg = np.asarray(man_xy_g, float)
            man_xy_crop = np.column_stack([mg[:,0]-x, mg[:,1]-y])

        for vid, r in enumerate(fm_results):
            if not r.get("ok"):
                print(f"[AUTO {crack_id}] v{vid} ❌ {r.get('error')}")
                continue

            track_xy = np.asarray(r["track_full_xy"], float).T  # (N,2) [x,y]
            # ensure start==p0, then anchor to p0
            d0 = np.linalg.norm(track_xy[0] - p0)
            d1 = np.linalg.norm(track_xy[0] - p1)
            if d1 < d0:
                track_xy = track_xy[::-1]
            track_xy = track_xy + (p0 - track_xy[0])

            # local coords
            track_local_yx = np.vstack([track_xy[:, 1] - y, track_xy[:, 0] - x])   # [y,x] for edge worker
            track_crop_xy  = np.column_stack([track_xy[:,0] - x, track_xy[:,1] - y])  # [x,y] for plotting

            payload = dict(base_payload)
            payload["adjusted_track"] = track_local_yx
            ew = edge_param_worker(payload)

            # label with real params
            desc = _variant_desc(vid, g_variants[vid], edge_params_fixed)
            variant_labels_by_id[vid] = desc["label"]

            # store variant + any normals the worker returns
            vrec = {
                "midline": metrics._to_py(track_xy),
                "mask_bbox": [xmin, ymin, w, h],
                "params": desc,  # stash the params with the variant
            }
            if ew and isinstance(ew, dict):
                for k in ("normal_edge_points_full", "normal_edge_points"):
                    if k in ew and ew[k]:
                        vrec[k] = metrics._to_py(ew[k])

                # copy metrics row + params
                if ew.get("status") == "ok":
                    row = dict(ew)
                    row.update({
                        "image": image_name,
                        "crack_id": crack_id,
                        "variant_id": vid,
                        **{k: desc[k] for k in ("g11","g22","g33","win","mu","ell","p")}
                    })
                    metrics_rows[vid] = row

            variants_out[f"v{vid}"] = vrec
            var_local_xy_by_id[vid] = track_crop_xy

            print(f"[AUTO {crack_id}] v{vid} len={len(track_xy)} "
                f"startΔ={np.linalg.norm(track_xy[0]-p0):.2f} endΔ={np.linalg.norm(track_xy[-1]-p1):.2f}")

        # ---- pick best, write CSV (with params in the table) ----
        best_variant_id = None
        if metrics_rows:
            df = pd.DataFrame(list(metrics_rows.values()))
            df = df.sort_values(["chamfer_mean","hausdorff","coverage"], ascending=[True,True,False])
            best_variant_id = int(df.iloc[0]["variant_id"])
            df.to_csv(os.path.join(crack_dir, "rs3_variants.csv"), index=False)

            # quick bar of chamfer
            import matplotlib.pyplot as plt
            plt.figure(figsize=(6,3))
            plt.bar(df["variant_id"].astype(str), df["chamfer_mean"])
            plt.title(f"Chamfer by variant — {image_name} cid{crack_id}")
            plt.xlabel("variant"); plt.ylabel("chamfer_mean")
            plt.tight_layout()
            plt.savefig(os.path.join(crack_dir, "chamfer_by_variant.png"), dpi=160)
            plt.close()

        # ---- overlays (OpenCV-style and Matplotlib legend) ----
        crop_rgb = self.image_crop.copy()
        if crop_rgb.ndim == 2:
            crop_rgb = cv2.cvtColor(crop_rgb, cv2.COLOR_GRAY2BGR)

        # Simple OpenCV overlay (kept for continuity)
        im_overlay = crop_rgb.copy()
        if isinstance(man_xy_crop, np.ndarray) and len(man_xy_crop) >= 2:
            pts = np.round(man_xy_crop).astype(np.int32).reshape(-1,1,2)
            cv2.polylines(im_overlay, [pts], False, (0,0,0), 5, lineType=cv2.LINE_AA)
            cv2.polylines(im_overlay, [pts], False, (255,255,255), 2, lineType=cv2.LINE_AA)
        # also draw each auto in a thin colored line (we’ll still generate the nice legend plot below)
        color_cycle = [
            "#e41a1c","#377eb8","#4daf4a","#984ea3","#ff7f00",
            "#a65628","#f781bf","#999999","#1b9e77","#d95f02",
        ]
        for i,(vid, xy) in enumerate(sorted(var_local_xy_by_id.items())):
            if xy is None or len(xy) < 2: continue
            col = color_cycle[i % len(color_cycle)]
            bgr = tuple(int(col.lstrip("#")[j:j+2], 16) for j in (4,2,0))
            pts = np.round(xy).astype(np.int32).reshape(-1,1,2)
            cv2.polylines(im_overlay, [pts], False, bgr, 2, lineType=cv2.LINE_AA)
        cv2.imwrite(os.path.join(crack_dir, "midlines_overlay.png"), im_overlay)

        # Matplotlib overlay + legend that shows real params per vN
        plot_midlines_overlay_all(
            image_crop_rgb=crop_rgb,
            man_local_xy=man_xy_crop if man_xy_crop is not None else np.empty((0,2)),
            var_local_xy_by_id=var_local_xy_by_id,
            variant_labels_by_id=variant_labels_by_id,
            save_overlay_png=os.path.join(crack_dir, "midlines_overlay.png"),
            save_legend_png=os.path.join(crack_dir, "midlines_overlay_legend.png"),
        )

        packed = {
            "g_variants": g_variants,
            "variants": variants_out,
            "best_variant_id": best_variant_id
        }
        variants_root[cache_key] = packed

        if getattr(self, "ann_name", None):
            try:
                safe_json_dump(self.annotation, self.ann_name)
                print(f"[AUTO {crack_id}] 💾 cached → {self.ann_name}")
            except Exception as e:
                print(f"[AUTO {crack_id}] ⚠ cache save failed: {e}")

        print(f"[AUTO {crack_id}] ✅ {len(variants_out)} variants (best={best_variant_id}) "
            f"using {cpu_max_workers or min(os.cpu_count() or 8,16)} workers")
        return packed

    def compute_mask_and_width_metrics_for_image(self, display=False):
        """
        For the current image:
        - compute IoU/manual-vs-GT and (if available) auto-vs-GT,
        - compute width diffs (edge vs mask) per crack and save plots,
        - write per-image CSVs, plus return summary dict.
        """
        import os, numpy as np, pandas as pd

        if getattr(self, "current_mask", None) is None:
            print("[mask/width] no GT mask loaded for this image"); 
            return {}

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        metrics_dir = os.path.join(self.save_folder, "metrics", base_name)
        os.makedirs(metrics_dir, exist_ok=True)

        ann = self.annotation.get("annotations", {})
        atomic = ann.get("atomic_cracks", {}) or {}
        H, W = self.original_image.shape[:2]

        # --- mask IoUs (manual + any auto variant present)
        mask_rows = []
        for cid, crack in atomic.items():
            src = (crack.get("source") or "").lower()
            if src.startswith("auto"): 
                continue  # skip evaluation of the auto-only entries here

            # manual
            m_manual = metrics._reconstruct_full_mask(crack, H, W)
            row = {"image": base_name, "crack_id": cid}
            row["iou_manual_vs_gt"] = metrics.mask_iou(m_manual, self.current_mask)

            # if you want an auto vs GT too (pick 'best' cache if exists)
            vroot = crack.get("variants", {}).get("auto", {})
            for ck, pack in vroot.items():
                bid = pack.get("best_variant_id")
                if bid is None: 
                    continue
                best = pack["variants"].get(f"v{bid}", {})
                mm = metrics._reconstruct_full_mask(best, H, W)
                row["iou_auto_vs_gt"] = metrics.mask_iou(mm, self.current_mask)
                break  # only first cache key

            mask_rows.append(row)

        if mask_rows:
            dfm = pd.DataFrame(mask_rows)
            dfm.to_csv(os.path.join(metrics_dir, "mask_metrics.csv"), index=False)

        # --- widths: use your compare_widths_for_cracks helper, which also plots per crack
        width_rows, _ = metrics.compare_widths_for_cracks(ann, self.current_mask, base_name, metrics_dir, display=display)
        if width_rows:
            pd.DataFrame(width_rows).to_csv(os.path.join(metrics_dir, "width_metrics.csv"), index=False)

        # return image-level means (so caller can aggregate across dataset)
        out = {}
        if mask_rows:
            out["mask_means"] = pd.DataFrame(mask_rows).mean(numeric_only=True).to_dict()
        if width_rows:
            out["width_means"] = pd.DataFrame(width_rows).mean(numeric_only=True).to_dict()
        return out
    
    #####################################
    # New functions
    #####################################
    def batch_run_metrics_global(
        self,
        sample_frac=0.15,          # % of images to use for global calibration
        max_images=15,             # cap for calibration phase
        seed=0,
        edge_grid=None,            # if None → sensible default below
        g_variants=None,           # if None → defaults inside generate_auto_variants_for_manual_parallel
        cpu_max_workers=8,
        apply_to_sample=False      # False → apply global params to ALL images; True → sampled set only
    ):
        """
        GLOBAL METRICS DRIVER (one image in memory at a time, no manual edge precompute needed).

        Phase A (calibration): learn ONE global edge-parameter set from a subset of images by
        sweeping edge params against *manual midlines* (reconstructs edge worker payloads internally).

        Phase B (application): for each image:
            - run RS3 auto variants for each manual atomic crack using the global edge params,
            - select best variant and persist per-variant table,
            - build AUTO combined masks with the *same member IDs* as manual combined,
            - compute final per-image IoU/width metrics,
            - export training supervision (manual GT widths from mask + auto-best edge artifacts).

        Saves:
        metrics/_summary/global_edge_sweep_all.csv
        metrics/_summary/global_best_edge_params.json
        metrics/<image>/edge_params_used.json
        metrics/<image>/cid<id>/rs3_variants.csv
        metrics/<image>/combined/combined_metrics.csv
        metrics/<image>/{mask_metrics.csv,width_metrics.csv}
        metrics/<image>/supervision/cid<id>/* (training artifacts)
        """
        import os, json, random
        import numpy as np, pandas as pd

        if not getattr(self, "image_names", []):
            print("[global-metrics] no images loaded"); return

        rng  = random.Random(seed)
        idxs = list(range(len(self.image_names)))
        rng.shuffle(idxs)
        k = max(1, int(len(idxs) * float(sample_frac)))
        idxs_sample = idxs[:min(k, max_images)]

        if edge_grid is None:
            edge_grid = {
                "window_half_size": [35, 45, 55],
                "mu": [0, 5],
                "l":  [2, 5],
                "p":  [6, 14],
            }

        print(f"[global-metrics] calibration on {len(idxs_sample)} images")

        sweep_rows = []
        orig_n = self.n

        try:
            # -------- Phase A: global calibration (no manual precompute needed) --------
            for t, i in enumerate(idxs_sample, 1):
                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [calibrate] {t}/{len(idxs_sample)}: {base_name} ======")

                ann = self.annotation.get("annotations", {}) or {}
                atomic = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    continue

                for cid, crack in atomic.items():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined": 
                        continue
                    man_xy = metrics._finite_xy(crack.get("midline", []))
                    if len(man_xy) < 2: 
                        continue

                    # Uses your existing sweep that reconstructs payload from manual midline.
                    df_sweep = self.sweep_edges_with_executor(
                        cid, grid=edge_grid, max_workers=cpu_max_workers
                    )
                    if df_sweep is None or df_sweep.empty:
                        continue

                    df_sweep = df_sweep.copy()
                    df_sweep["image"]    = base_name
                    df_sweep["crack_id"] = cid
                    sweep_rows.append(df_sweep)

            if not sweep_rows:
                print("[global-metrics] ❌ no sweep rows gathered — aborting.")
                return

            df_all = pd.concat(sweep_rows, ignore_index=True)

            summ_dir = os.path.join(self.save_folder, "metrics", "_summary")
            os.makedirs(summ_dir, exist_ok=True)
            df_all.to_csv(os.path.join(summ_dir, "global_edge_sweep_all.csv"), index=False)

            param_cols = ["param_window_half_size","param_mu","param_l","param_p"]
            keep_cols  = param_cols + ["chamfer_mean","hausdorff","coverage"]
            sub = df_all[[c for c in keep_cols if c in df_all.columns]].dropna()

            g = (sub.groupby(param_cols, as_index=False)
                    .agg({"chamfer_mean":"mean","hausdorff":"mean","coverage":"mean"}))

            g = g.sort_values(["chamfer_mean","hausdorff","coverage"],
                            ascending=[True, True, False])

            best = g.iloc[0].to_dict()
            global_best_edge = {
                "window_half_size": int(best["param_window_half_size"]),
                "mu": float(best["param_mu"]),
                "l":  int(best["param_l"]),
                "p":  int(best["param_p"]),
            }

            with open(os.path.join(summ_dir, "global_best_edge_params.json"), "w") as f:
                json.dump(global_best_edge, f, indent=2)

            print(f"[global-metrics] ✅ global best edge params = {global_best_edge}")

        finally:
            self.n = orig_n
            self.change_image()

        # -------- Phase B: apply to images (one at a time) --------
        print("[global-metrics] applying global params to images…")
        apply_idxs = idxs_sample if apply_to_sample else list(range(len(self.image_names)))

        try:
            for t, i in enumerate(apply_idxs, 1):
                self.n = i
                self.change_image()
                base_name = os.path.splitext(os.path.basename(self.name))[0]
                print(f"\n====== [apply] {t}/{len(apply_idxs)}: {base_name} ======")

                image_dir = os.path.join(self.save_folder, "metrics", base_name)
                os.makedirs(image_dir, exist_ok=True)

                # log the params used for this image
                try:
                    with open(os.path.join(image_dir, "edge_params_used.json"), "w") as f:
                        json.dump(global_best_edge, f, indent=2)
                except Exception as e:
                    print(f"[apply] could not write edge_params_used.json: {e}")

                ann = self.annotation.get("annotations", {}) or {}
                atomic  = ann.get("atomic_cracks", {}) or {}
                if not atomic:
                    continue

                # 1) per-manual atomics: RS3 variants with global edge params
                for cid, crack in atomic.items():
                    src = (crack.get("source") or "").lower()
                    if src.startswith("auto") or src == "combined":
                        continue
                    man_xy = metrics._finite_xy(crack.get("midline", []))
                    if len(man_xy) < 2:
                        continue

                    _ = self.generate_auto_variants_for_manual_parallel(
                        crack_id=cid,
                        g_variants=g_variants,
                        edge_params_fixed=global_best_edge,
                        cpu_max_workers=cpu_max_workers,
                        force_recompute=True
                    )

                # 2) build combined auto masks mirroring manual membership
                try:
                    self._build_combined_auto_masks_same_indices(cache_key=metrics._auto_cache_key(self))
                except Exception as e:
                    print(f"[apply] combined auto-mask build failed: {e}")

                # 3) final per-image IoU/width metrics
                try:
                    self.compute_mask_and_width_metrics_for_image(display=False)
                except Exception as e:
                    print(f"[apply] mask/width stage failed: {e}")

                # 4) export training supervision (manual GT widths from mask + auto-best artifacts)
                try:
                    self.export_training_supervision_for_image(cache_key=metrics._auto_cache_key(self))
                except Exception as e:
                    print(f"[apply] supervision export failed: {e}")

            self.summarize_dataset_metrics()
            print("[global-metrics] ✅ finished")

        finally:
            self.n = orig_n
            self.change_image()


    def run_metrics_on_current_image_quick(
        self,
        edge_grid=None,            # if None → default grid below
        g_variants=None,           # if None → defaults inside generate_auto_variants_for_manual_parallel
        cpu_max_workers=8,
        do_edge_calibrate=True     # True → sweep THIS image to pick best single edge-param tuple
    ):
        """
        FAST iteration for the *current* image:

        - (optional) Calibrate one best edge-param tuple on THIS image
        by sweeping manual atomic cracks and aggregating metrics.
        - Run RS3 auto variants per manual crack with that fixed tuple.
        - Build combined AUTO masks using the exact same members as manual combined cracks.
        - Compute mask IoU + width diffs for the image.
        - Export training supervision (manual GT widths from mask + auto-best artifacts).

        Returns: {"image": <name>, "best_edge": {...}}.
        """
        import os, json, numpy as np, pandas as pd
        

        if getattr(self, "original_image", None) is None:
            print("[quick] no image loaded"); 
            return {}

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        print(f"\n[quick] metrics for current image: {base_name}")

        if edge_grid is None:
            edge_grid = {
                "window_half_size": [35, 45, 55],
                "mu": [0, 5],
                "l":  [2, 5],
                "p":  [6, 14],
            }

        ann = self.annotation.get("annotations", {}) or {}
        atomic = ann.get("atomic_cracks", {}) or {}
        image_dir = os.path.join(self.save_folder, "metrics", base_name)
        os.makedirs(image_dir, exist_ok=True)

        # --- choose best edge params for THIS image (optional)
        best_edge = {"window_half_size":45, "mu":0.0, "l":5, "p":14}
        if do_edge_calibrate:
            sweep_rows = []
            for cid, crack in atomic.items():
                src = (crack.get("source") or "").lower()
                if src.startswith("auto") or src == "combined":
                    continue
                man_xy = metrics._finite_xy(crack.get("midline", []))
                if len(man_xy) < 2:
                    continue

                df_sweep = self.sweep_edges_with_executor(
                    cid, grid=edge_grid, max_workers=cpu_max_workers
                )
                if df_sweep is None or df_sweep.empty:
                    continue
                sweep_rows.append(df_sweep)

            if sweep_rows:
                df = pd.concat(sweep_rows, ignore_index=True)
                param_cols = ["param_window_half_size","param_mu","param_l","param_p"]
                sub = df[[c for c in (param_cols+["chamfer_mean","hausdorff","coverage"]) if c in df.columns]].dropna()
                g = (sub.groupby(param_cols, as_index=False)
                        .agg({"chamfer_mean":"mean","hausdorff":"mean","coverage":"mean"}))
                g = g.sort_values(["chamfer_mean","hausdorff","coverage"], ascending=[True,True,False])
                row = g.iloc[0].to_dict()
                best_edge = {
                    "window_half_size": int(row["param_window_half_size"]),
                    "mu": float(row["param_mu"]),
                    "l":  int(row["param_l"]),
                    "p":  int(row["param_p"]),
                }

        # persist params used for this image
        try:
            with open(os.path.join(image_dir, "edge_params_used.json"), "w") as f:
                json.dump(best_edge, f, indent=2)
        except Exception as e:
            print(f"[quick] could not write edge_params_used.json: {e}")

        print(f"[quick] using edge params: {best_edge}")

        # --- RS3 auto variants with fixed best_edge
        for cid, crack in atomic.items():
            src = (crack.get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue
            man_xy = metrics._finite_xy(crack.get("midline", []))
            if len(man_xy) < 2:
                continue

            _ = self.generate_auto_variants_for_manual_parallel(
                crack_id=cid,
                g_variants=g_variants,
                edge_params_fixed=best_edge,
                cpu_max_workers=cpu_max_workers,
                force_recompute=True
            )

        # --- combined AUTO masks mirroring manual membership
        try:
            self._build_combined_auto_masks_same_indices(cache_key=metrics._auto_cache_key(self))
        except Exception as e:
            print(f"[quick] combined auto-mask build failed: {e}")

        # --- final per-image IoU/width metrics
        try:
            self.compute_mask_and_width_metrics_for_image(display=False)
        except Exception as e:
            print(f"[quick] mask/width stage failed: {e}")

        # --- export supervision (manual GT widths + auto-best artifacts)
        try:
            self.export_training_supervision_for_image(cache_key=metrics._auto_cache_key(self))
        except Exception as e:
            print(f"[quick] supervision export failed: {e}")

        print("[quick] ✅ done")
        return {"image": base_name, "best_edge": best_edge}


    def _build_combined_auto_masks_same_indices(self, cache_key=None):
        """
        Build *AUTO* combined masks that mirror manual combined_cracks membership.
        The union is over the *best auto variant* masks of each member atomic crack.

        Saves per-image:
        metrics/<image>/combined/combined_<cid>_auto.png
        metrics/<image>/combined/combined_<cid>_manual.png
        metrics/<image>/combined/combined_metrics.csv
        """
        import os, cv2, numpy as np, pandas as pd
        

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        image_dir = os.path.join(self.save_folder, "metrics", base_name)
        out_dir   = os.path.join(image_dir, "combined")
        os.makedirs(out_dir, exist_ok=True)

        ann = self.annotation.get("annotations", {}) or {}
        atomic   = ann.get("atomic_cracks", {}) or {}
        combined = ann.get("combined_cracks", {}) or {}
        if not combined:
            return

        H, W = self.original_image.shape[:2]
        rows = []
        cache_key = cache_key or metrics._auto_cache_key(self)

        for cmb_id, cmb in combined.items():
            members = cmb.get("members", []) or []
            if not members:
                continue

            m_manual = metrics._reconstruct_full_mask(cmb, H, W)

            m_auto = np.zeros((H, W), np.uint8)
            for mid in members:
                crack = atomic.get(mid)
                if not crack:
                    continue
                pack = crack.get("variants", {}).get("auto", {}).get(cache_key)
                if not pack:
                    continue
                bid = pack.get("best_variant_id")
                if bid is None:
                    continue
                best = pack["variants"].get(f"v{bid}", {})
                mm = metrics._reconstruct_full_mask(best, H, W)
                if mm is not None:
                    m_auto |= (mm > 0).astype(np.uint8)

            cv2.imwrite(os.path.join(out_dir, f"combined_{cmb_id}_manual.png"),
                        (m_manual>0).astype(np.uint8)*255)
            cv2.imwrite(os.path.join(out_dir, f"combined_{cmb_id}_auto.png"),
                        (m_auto>0).astype(np.uint8)*255)

            row = {"image": base_name, "combined_id": cmb_id}
            if getattr(self, "current_mask", None) is not None:
                row["iou_manual_vs_gt"] = metrics.mask_iou(m_manual, self.current_mask)
                row["iou_auto_vs_gt"]   = metrics.mask_iou(m_auto,   self.current_mask)
            rows.append(row)

        if rows:
            pd.DataFrame(rows).to_csv(os.path.join(out_dir, "combined_metrics.csv"), index=False)
            print(f"[combined] wrote → {os.path.join(out_dir, 'combined_metrics.csv')}")


    def export_training_supervision_for_image(self, cache_key=None, normal_half_span=32.0, step=0.5):
        """
        Export per-crack supervision artifacts for training/analysis.

        For each *manual* atomic crack:
        - manual_midline.csv
        - manual_mask.png (single-crack GT mask)
        - manual_gt_width_samples.csv (widths from GT mask along manual midline normals)
        - auto_best_midline.csv        (if best variant exists)
        - auto_best_normals_edge1.csv, auto_best_normals_edge2.csv (if present)
        - auto_best_params.json
        - auto_best_width_samples.csv  (if both auto edges present)

        All files saved under: metrics/<image>/supervision/cid<id>/
        """
        import os, json
        import numpy as np
        import pandas as pd
        import cv2
        

        def _ensure_dir(p):
            os.makedirs(p, exist_ok=True); return p

        def _resample_polyline(xy, step=1.0):
            xy = np.asarray(xy, float)
            if len(xy) < 2: return xy
            d = np.sqrt(((xy[1:] - xy[:-1])**2).sum(1))
            s = np.concatenate([[0.0], np.cumsum(d)])
            L = s[-1]
            if L <= 1e-6: return xy
            n = max(2, int(np.ceil(L/step))+1)
            s_new = np.linspace(0, L, n)
            # linear interpolate
            x = np.interp(s_new, s, xy[:,0])
            y = np.interp(s_new, s, xy[:,1])
            return np.column_stack([x,y])

        def _bilinear_sample(img01, pts_xy):
            # img01: HxW float {0,1}; pts_xy: Nx2 (x,y) floats
            H, W = img01.shape
            x = pts_xy[:,0].clip(0, W-1)
            y = pts_xy[:,1].clip(0, H-1)
            x0 = np.floor(x).astype(int); x1 = np.minimum(x0+1, W-1)
            y0 = np.floor(y).astype(int); y1 = np.minimum(y0+1, H-1)
            fx = x - x0; fy = y - y0
            Ia = img01[y0, x0]
            Ib = img01[y0, x1]
            Ic = img01[y1, x0]
            Id = img01[y1, x1]
            return (Ia*(1-fx)*(1-fy) + Ib*fx*(1-fy) + Ic*(1-fx)*fy + Id*fx*fy)

        def _edges_from_mask_along_normals(mid_xy, mask_bin, half_span=32.0, ds=0.5):
            # Returns DataFrame with per-sample mid/edge coords + width (px).
            xy = _resample_polyline(mid_xy, step=1.0)
            if len(xy) < 2: return pd.DataFrame()
            # tangents
            v = np.gradient(xy, axis=0)
            nrm = np.stack([-v[:,1], v[:,0]], axis=1)
            nrm_len = np.linalg.norm(nrm, axis=1, keepdims=True) + 1e-9
            n = nrm / nrm_len

            ts = np.arange(-half_span, half_span+1e-6, ds)  # sample offsets
            rows = []
            for i, p in enumerate(xy):
                line = p[None,:] + ts[:,None]*n[i:i+1,:]     # (T,2)
                vals = _bilinear_sample(mask_bin.astype(float), line)
                # pick leftmost ≥0.5 and rightmost ≥0.5 indices
                on = np.where(vals >= 0.5)[0]
                if len(on) == 0:
                    rows.append([i, p[0], p[1], np.nan, np.nan, np.nan, np.nan, np.nan])
                    continue
                il, ir = on[0], on[-1]
                xl, yl = line[il]
                xr, yr = line[ir]
                width = np.hypot(xr - xl, yr - yl)
                rows.append([i, p[0], p[1], xl, yl, xr, yr, width])

            return pd.DataFrame(rows, columns=[
                "sample_idx","mid_x","mid_y","edgeL_x","edgeL_y","edgeR_x","edgeR_y","width_px"
            ])

        if getattr(self, "current_mask", None) is None:
            print("[supervision] no GT mask loaded for this image"); 
            return

        base_name = os.path.splitext(os.path.basename(self.name))[0]
        image_dir = os.path.join(self.save_folder, "metrics", base_name)
        sup_root  = _ensure_dir(os.path.join(image_dir, "supervision"))

        H, W = self.original_image.shape[:2]
        mask_bin = (self.current_mask > 0).astype(np.uint8)

        ann = self.annotation.get("annotations", {}) or {}
        atomic = ann.get("atomic_cracks", {}) or {}
        cache_key = cache_key or metrics._auto_cache_key(self)

        for cid, crack in atomic.items():
            src = (crack.get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue

            man_xy = metrics._finite_xy(crack.get("midline", []))
            if len(man_xy) < 2:
                continue

            # paths
            out_dir = _ensure_dir(os.path.join(sup_root, f"cid{cid}"))

            # ---- Manual GT: midline + single-crack mask + width samples from mask
            pd.DataFrame(man_xy, columns=["x","y"]).to_csv(
                os.path.join(out_dir, "manual_midline.csv"), index=False
            )

            m_manual = metrics._reconstruct_full_mask(crack, H, W)
            cv2.imwrite(os.path.join(out_dir, "manual_mask.png"),
                        (m_manual>0).astype(np.uint8)*255)

            try:
                df_gt = _edges_from_mask_along_normals(
                    mid_xy=man_xy, mask_bin=mask_bin, half_span=normal_half_span, ds=step
                )
                if not df_gt.empty:
                    df_gt.to_csv(os.path.join(out_dir, "manual_gt_width_samples.csv"), index=False)
            except Exception as e:
                print(f"[supervision] GT widths failed for cid={cid}: {e}")

            # ---- Auto best variant artifacts (if exist)
            pack = crack.get("variants", {}).get("auto", {}).get(cache_key)
            if pack:
                bid = pack.get("best_variant_id")
                if bid is not None:
                    best = pack["variants"].get(f"v{bid}", {})

                    # midline
                    auto_xy = np.asarray(best.get("midline", []), dtype=float)
                    if auto_xy.size >= 4:
                        pd.DataFrame(auto_xy, columns=["x","y"]).to_csv(
                            os.path.join(out_dir, "auto_best_midline.csv"), index=False
                        )

                    # params
                    params = best.get("params", {})
                    try:
                        with open(os.path.join(out_dir, "auto_best_params.json"), "w") as f:
                            json.dump(params, f, indent=2)
                    except Exception as e:
                        print(f"[supervision] write params failed for cid={cid}: {e}")

                    # normals/edge points (if edge worker provided them)
                    ne = best.get("normal_edge_points_full") or best.get("normal_edge_points")
                    if isinstance(ne, dict):
                        e1 = np.asarray(ne.get("edge1", []), float)
                        e2 = np.asarray(ne.get("edge2", []), float)
                        if e1.size >= 4:
                            pd.DataFrame(e1, columns=["x","y"]).to_csv(
                                os.path.join(out_dir, "auto_best_normals_edge1.csv"), index=False
                            )
                        if e2.size >= 4:
                            pd.DataFrame(e2, columns=["x","y"]).to_csv(
                                os.path.join(out_dir, "auto_best_normals_edge2.csv"), index=False
                            )
                        # If both edges present and aligned by index, dump per-sample widths
                        try:
                            if e1.size >= 4 and e2.size >= 4:
                                n = min(len(e1), len(e2))
                                w = np.hypot(e1[:n,0]-e2[:n,0], e1[:n,1]-e2[:n,1])
                                df_auto_w = pd.DataFrame({
                                    "idx": np.arange(n),
                                    "edge1_x": e1[:n,0], "edge1_y": e1[:n,1],
                                    "edge2_x": e2[:n,0], "edge2_y": e2[:n,1],
                                    "width_px": w
                                })
                                df_auto_w.to_csv(os.path.join(out_dir, "auto_best_width_samples.csv"), index=False)
                        except Exception as e:
                            print(f"[supervision] auto width export failed for cid={cid}: {e}")


    def run_midline_and_mask_metrics(self, tau_px=3.0, crack_id=None, display=True, do_param_sweep=True):
        """
        DEPRECATED wrapper kept for UI/back-compat.
        Delegates to run_metrics_on_current_image_quick(), then writes midline_metrics.csv
        (manual vs *best auto*) using cached best-variant results.
        """
        import os, numpy as np, pandas as pd
        

        # 1) run new quick pipeline
        _ = self.run_metrics_on_current_image_quick(
            edge_grid=None,
            g_variants=None,
            cpu_max_workers=8,
            do_edge_calibrate=bool(do_param_sweep)
        )

        # 2) re-materialize midline_metrics.csv (legacy expectation)
        base_name = os.path.splitext(os.path.basename(self.name))[0]
        image_dir = os.path.join(self.save_folder, "metrics", base_name)
        ann = self.annotation.get("annotations", {}) or {}
        atomic = ann.get("atomic_cracks", {}) or {}

        rows = []
        cache_key = metrics._auto_cache_key(self)
        for cid, crack in atomic.items():
            if (crack_id is not None) and (cid != str(crack_id)):
                continue
            src = (crack.get("source") or "").lower()
            if src.startswith("auto") or src == "combined":
                continue

            man_xy = metrics._finite_xy(crack.get("midline", []))
            if len(man_xy) < 2:
                continue

            pack = crack.get("variants", {}).get("auto", {}).get(cache_key)
            if not pack:
                continue
            bid = pack.get("best_variant_id")
            if bid is None:
                continue
            best = pack["variants"].get(f"v{bid}", {})
            auto_xy = metrics._finite_xy(best.get("midline", []))
            if len(auto_xy) < 2:
                continue

            mm = metrics.compute_midline_metrics(auto_xy, man_xy, tau=tau_px)
            mm.update({"image": base_name, "crack_id": cid, "best_variant_id": bid})
            rows.append(mm)

        if rows:
            os.makedirs(image_dir, exist_ok=True)
            pd.DataFrame(rows).to_csv(os.path.join(image_dir, "midline_metrics.csv"), index=False)

        if display:
            try:
                self.compute_mask_and_width_metrics_for_image(display=True)
            except Exception as e:
                print(f"[metrics] mask/width stage failed: {e}")
    
    
    
if __name__ == "__main__":
    import sys
    from time import time
    app = QtWidgets.QApplication(sys.argv)
    font = QtGui.QFont()
    font.setPointSize(7)
    app.setFont(font)
    MainWindow = QtWidgets.QMainWindow()
    ui = CrackToolsApplication()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())