# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cracktools as ct
from helpers.layout import Ui_MainWindow
from helpers.metrics import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import Qt
import skimage
import numpy as np
import cv2
import matplotlib
matplotlib.use("Agg")   # fastest non-GUI backend for PNG/PDF/SVG export
matplotlib.rcParams.update({
    "figure.max_open_warning": 0,
    "text.kerning_factor": 0,
    "font.family": "DejaVu Sans",
    "axes.unicode_minus": False,
})
import matplotlib.pyplot as plt
plt.ioff()   # no interactive figure updates

import json
import os
from skimage.segmentation import mark_boundaries
import os
from PyQt5.QtWidgets import QListWidgetItem
from shapely import geometry, ops
import pandas as pd

from crackutils import *
from manual_drawing import *
from track_segment_pipeline import *
from helpers.crackhelpers import *
#from helpers import *
from helpers import plot_metrics
from helpers import metrics
from helpers import save_load_files
from combine_clear_segments import *
import cracktools as ct

from concurrent.futures import ProcessPoolExecutor, as_completed
import itertools, pandas as pd, os
from edge_workers import *

from rs3_split import run_rs3_variants_split
from edge_workers import *
from combiner import *


#from crackutils import CrackUtils
DEBUG_SAVE_LIGHT = True   # True → only high-res compact outputs
from helpers.endpoint_annotator import CrackAnnotator
min_crop_size = 16   
class MetricsEngine(TrackSegmentPipeline, CrackUtils):
    