[project]
name = "crack-width-baselines"
version = "0.1.0"
channels = ["rapidsai", "conda-forge"]
platforms = ["linux-64"]
authors = ["Adam Camerer <ajc3xc@umsystem.edu>"]

[dependencies]
python = "==3.10"
cuda-version = "==11.8"
cudatoolkit = "==11.8"

# GPU
cupy = "*"
cucim = "==23.4.0"

# Core
numpy = "<2"
pandas = "*"
scikit-image = "*"
scipy = "*"
scikit-learn = "*"
matplotlib = "*"
pillow = "*"
networkx = "*"   # sknw depends on this
pip = "*"

[pypi-dependencies]
pandarallel = "*"
sknw = "*"

[tasks]
run = "python width_baseline_creator.py --help"
